### ISSUE TITLE
Revise when trowing AbortedException, PrematureCloseException and InternalNettyException

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#1039]
Related to https://github.com/spring-projects/spring-framework/issues/24596

https://github.com/reactor/reactor-netty/commit/5059f86a8e3c6e00d0859d56f869f704019cef61#diff-03cecb2a278ad2453fcf6a85575dae60

**Comment by Dariusz91** [comment]
Hello @violetagg, any news about this issue? We've been experiencing a problem similar to the one described in https://github.com/spring-projects/spring-framework/issues/24596.

We are using Spring Boot Webflux 2.2.5.RELEASE and reactor-netty 0.9.6.RELEASE. Sometimes our client is closing connection because of timeout and we're getting something like this in our logs:

```
[e26eee7f-8975910] Error [java.lang.UnsupportedOperationException] for HTTP GET "/status/ping", but ServerHttpResponse already committed (200 OK)
```
and:
```
reactor.netty.ReactorNetty$InternalNettyException: java.nio.channels.ClosedChannelException
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ReadOperationHandler#handle(ServerWebExchange) [DispatcherHandler]
Stack trace:
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.write(CombinedChannelDuplexHandler.java:526)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at reactor.netty.http.server.HttpTrafficHandler.write(HttpTrafficHandler.java:269)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1104)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadL
```

**Comment by violetagg** [comment]
@Dariusz91 For the moment this is scheduled for [0.9.8.RELEASE](https://github.com/reactor/reactor-netty/milestone/69)
