### ISSUE TITLE
Netty Server handles HTTP 204(no content) with response body

### ISSUE THREAD

**Issue by zhangzhijiang** [reactor/reactor-netty#1057]
Hi,
I am working a application using Spring Boot WebFlux to call a third party API. that API returns 204 (No content) with a message in the body for a GET when item not found (see attached screenshot below).
I understand that the third-party API shouldn't return 204 for item not found, even return 204 it must not have a body. but changing that API is not an option. I am trying to see if I can find a solution on Netty side.

If the GET is called for the first time the message body from HTTP204 seems stay in the buffer, not get cleared. if the GET is called for the second time Netty is trying to parse the message from buffer to a HTTP version. and errored out for the following stack(See Actual Behavior section below)

![image](https://user-images.githubusercontent.com/12143209/78710272-ea20d000-78c9-11ea-9f65-6f725cc56340.png)

## Expected Behavior

In my opinion Netty Server should clear the data buffer for scenario that HTTP 204 (NO CONTENT) has message in a response body.

## Actual Behavior

java.lang.IllegalArgumentException: invalid version format: {"MESSAGE":"INVALID
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:120) ~[netty-codec-http-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:77) ~[netty-codec-http-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.http.HttpResponseDecoder.createMessage(HttpResponseDecoder.java:118) ~[netty-codec-http-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:210) ~[netty-codec-http-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:202) ~[netty-codec-http-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470) [netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219) [netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266) [netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]

## Steps to Reproduce

I am not able to simulate the API that returns 204 with response body. My client code is simple as following:

```java
@Test
public void repoCase() {
 webClient
                .get()
                .uri()
                .retrieve()
                .bodyToMono(Product.class)
}
```

## Possible Solution

No sure if this is bug to fix , or to enhance.

## Your Environment

Spring Boot 2.2.5
The third-party API is built using .net 

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...): 3.3.3
* JVM version (`javar -version`): openJDK 1.8
* OS and version (eg `uname -a`): Windows 10

**Comment by violetagg** [comment]
@zhangzhijiang 
According to the specification

https://tools.ietf.org/html/rfc7231#section-6.3.5

```
A 204 response is terminated by the first empty line after the header
   fields because it cannot contain a message body.
```

We cannot read the body.
Even in your example above there is no `Content-Length`/`Transfer-Encoding` headers that will give us information for the body that is coming.

I would say that your remote peer is violating the specification and not only for 204 response code, but also how the response body should be sent.

**Comment by zhangzhijiang** [comment]
Thanks for looking into this. I understand it is their API violates the HTTP specification. but the interesting thing is that I assume all the other clients are able to deal with this response. even if I use RestTemplate from Spring to call the same API it will not give any error. only use WebClient call first time ok, second time error, third time ok, fourth time error...and so on. we are working on make them to fix the API but I also look for another workaround as plan-b. Cheers,Mark

**Comment by violetagg** [comment]
@rstoyanchev Can you comment how `RestTemplate` supports that use case?
