### ISSUE TITLE
java.io.IOException: Connection closed prematurely

### ISSUE THREAD

**Issue by yangchenjava** [reactor/reactor-netty#1074]
```java
...
cloud:
    gateway:
      httpclient:
        connect-timeout: 45000
        response-timeout: 60s
        pool:
          type: fixed
          acquire-timeout: 60000
          max-connections: 20
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedMethods: "*"
            allowedOrigins: "*"
            exposedHeaders:
              - Authorization
      routes:
        - id: web-ris-user
          uri: lb://web-ris-general
...
```
this is 0.7.15.release
```java
java.io.IOException: Connection closed prematurely
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundClose(HttpClientOperations.java:278) ~[reactor-netty-0.7.15.RELEASE.jar!/:0.7.15.RELEASE]
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:115) ~[reactor-netty-0.7.15.RELEASE.jar!/:0.7.15.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282) ~[netty-codec-http-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[RAD] 2020-04-22 14:30:07,333 [reactor-http-nio-2] WARN [org.springframework.boot.autoconfigure.web.reactive.error.DefaultErrorWebExceptionHandler] - Failed to handle request [POST http://192.168.1.161:9527/search/study/all]
java.io.IOException: Connection closed prematurely
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundClose(HttpClientOperations.java:278) ~[reactor-netty-0.7.15.RELEASE.jar!/:0.7.15.RELEASE]
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:115) ~[reactor-netty-0.7.15.RELEASE.jar!/:0.7.15.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282) ~[netty-codec-http-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

this is 0.9.6.release
```java
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/general/dict/studymethod" [ExceptionHandlingWebHandler]
```

## Your Environment

* spring cloud:Finchley.SR4 or Hoxton.SR3, spring cloud gateway
* Reactor version(s) used:0.7.15.release or 0.9.6.release
* JVM version (`javar -version`):jdk1.8.0_161
* OS and version (eg `uname -a`):windows10

**Comment by violetagg** [comment]
@yangchenjava please provide a reproducible example. Try to take a tcpdump to see which component closes the connection

**Comment by yangchenjava** [comment]
@violetagg It's not going to happen all the time，so I dot kown how to fix it

**Comment by violetagg** [comment]
@yangchenjava then try to debug it. (tcpdump might help)
There might be several causes about this. Check these issues:

#1008
#564 (comment)
#1038

**Comment by yangchenjava** [comment]
oh I also run nginx on this gateway server at the same time , I don't know if it's related to this.

**Comment by violetagg** [comment]
@yangchenjava What happens if you move Nginx on a separate host?

**Comment by violetagg** [comment]
Closing the issue. We can reopen it if this is needed.
