### ISSUE TITLE
Spring webflux WebClient with Keystore/Truststore

### ISSUE THREAD

**Issue by voodemsanthosh** [reactor/reactor-netty#1102]
Hello Spring Guys,

I am trying to create a webclient object to use my keystore and truststore to call external API with https.

I am following below example to create Webclient.
            https://github.com/reactor/reactor-netty/issues/640#issuecomment-478738139

on my success build, using http://localhost:8080 getting below error,

`
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f6c696e6b2d6170692d73746174757320485454502f312e310d0a417574686f72697a6174696f6e3a2042617369632063335a766232526c6254704d4d57357263484a76646d6c6b5a58493d0d0a557365722d4167656e743a2
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1198) ~[netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266) ~[netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	... 17 common frames omitted
`

JVM version (e.g. java -version)
openjdk version "1.8.0_19."

OS version (e.g. uname -a)
Mac Mojave

**Comment by violetagg** [comment]
@voodemsanthosh You are trying `http://localhost:8080` or `https://localhost:8080`

`http` vs `https`

**Comment by voodemsanthosh** [comment]
> @voodemsanthosh You are trying `http://localhost:8080` or `https://localhost:8080`
> 
> `http` vs `https`

Sorry my bad. I have set server.ssl properties in config file which forcing to enable localhost also secure. Now my issue got resolve with help of https://github.com/reactor/reactor-netty/issues/640#issuecomment-478738139.

we are good to close this issue. Thank you @violetagg
