### ISSUE TITLE
Spring Flux - ConnectTimeoutException 

### ISSUE THREAD

**Issue by ramk90** [reactor/reactor-netty#1167]
I got the following issues only when we increased the request throughput higher. I have just started with Spring flux and looking for some understanding on the following case

io.netty.channel.ConnectTimeoutException: connection timed out: 
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
at java.lang.Thread.run(Thread.java:811)

**Comment by violetagg** [comment]
@ramk90 Please specify the versions that you use and also the settings for the connection pool and connection timeout

**Comment by violetagg** [comment]
@ramk90 Closing this issue, We can reopen it when you provide more information.
For questions please use [Gitter](https://gitter.im/reactor/reactor-netty) or [StackOverflow](https://stackoverflow.com/questions/tagged/reactor-netty)
