### ISSUE TITLE
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: DefaultFileRegion

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#12]
See [SPR-14975](https://jira.spring.io/browse/SPR-14975) for more details and a repro project.
Note that this is as well failing the Spring Framework CI on `RequestMappingMessageConversionIntegrationTests.resource()`.

**Comment by bclozel** [comment]
Issue has been introduced in 2077df311d42e5340107ae43d56fe5f318d44188

**Comment by bclozel** [comment]
It seems the same issue also happens on the client side with the following exception:


```
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: DefaultHttpRequest
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:345) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:749) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:741) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:827) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:734) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:749) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:812) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:805) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:842) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at reactor.ipc.netty.http.HttpOperations.sendHeadersAndSubscribe(HttpOperations.java:223) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.http.HttpOperations$MonoSendHeaders.subscribe(HttpOperations.java:325) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.core.publisher.MonoThenSupply$MonoConcatIgnoreManager.drain(MonoThenSupply.java:149) ~[reactor-core-3.0.0.BUILD-SNAPSHOT.jar:na]
	at reactor.core.publisher.MonoThenSupply.subscribe(MonoThenSupply.java:54) ~[reactor-core-3.0.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:535) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.http.client.HttpClientOperations.onChannelActive(HttpClientOperations.java:436) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.channel.PooledClientContextHandler.connectOrAcquire(PooledClientContextHandler.java:185) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.channel.PooledClientContextHandler.lambda$operationComplete$0(PooledClientContextHandler.java:143) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
Caused by: java.lang.IllegalStateException: unexpected message type: DefaultHttpRequest
	at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:69) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:145) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	... 26 common frames omitted

```

**Comment by rwinch** [comment]
Another example of this occurring is in the spring-security-reactive sample's [SecurityTests](https://github.com/spring-projects/spring-security-reactive/blob/a318d27e54d7bb5c72179a4a86bb1bbe9c2f2928/sample/src/test/java/sample/SecurityTests.java)

If I run a single test, it works. However as soon as a second test is ran it fails with:

```

io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: DefaultHttpRequest
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:345) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:749) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:741) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:827) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:734) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:749) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:812) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:805) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:842) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at reactor.ipc.netty.http.HttpOperations.sendHeadersAndSubscribe(HttpOperations.java:223) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.http.HttpOperations$MonoSendHeaders.subscribe(HttpOperations.java:325) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.core.publisher.MonoThenSupply$MonoConcatIgnoreManager.drain(MonoThenSupply.java:149) ~[reactor-core-3.0.0.BUILD-SNAPSHOT.jar:na]
	at reactor.core.publisher.MonoThenSupply.subscribe(MonoThenSupply.java:54) ~[reactor-core-3.0.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:535) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.http.client.HttpClientOperations.onChannelActive(HttpClientOperations.java:436) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.channel.PooledClientContextHandler.connectOrAcquire(PooledClientContextHandler.java:185) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at reactor.ipc.netty.channel.PooledClientContextHandler.lambda$operationComplete$0(PooledClientContextHandler.java:143) ~[reactor-netty-0.6.0.BUILD-SNAPSHOT.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
Caused by: java.lang.IllegalStateException: unexpected message type: DefaultHttpRequest
	at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:69) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:145) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	... 26 common frames omitted
```

**Comment by bclozel** [comment]
This is now fixed, thanks!
