### ISSUE TITLE
Getting a lot of `PrematureCloseException : Connection prematurely closed BEFORE response`

### ISSUE THREAD

**Issue by igr** [reactor/reactor-netty#1217]
version: **v0.9.7**

We are receiving a lot of:

```
reactor.core.ReactiveException: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
    at reactor.core.Exceptions.propagate(Exceptions.java:393)
    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
    at reactor.core.publisher.Mono.block(Mono.java:1678)
```

The client is built like this:

```java
        final ConnectionProvider connectionProvider =
            ConnectionProvider.builder("platform-client-connection-pool-fixed")
                .maxConnections(1_000)
                .pendingAcquireTimeout(Duration.ofMillis(30_000))
                .maxIdleTime(Duration.ofMillis(120))
                .build();

        final TcpClient mainTcpClient = TcpClient.create(connectionProvider)
            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 15_000)
            .doOnConnected(conn -> conn
                .addHandlerLast(new ReadTimeoutHandler(
                    120_000,
                    TimeUnit.MILLISECONDS))
                .addHandlerLast(new WriteTimeoutHandler(
                    500,
                    TimeUnit.MILLISECONDS))
                .addHandler(new IdleStateHandler(
                    2_000,
                    500, 5000,
                    TimeUnit.MILLISECONDS)));

        final HttpClient httpClient = HttpClient.from(mainTcpClient)
            .keepAlive(true)
            .wiretap(true)
            .compress(true);

        return WebClient.builder()
            .exchangeStrategies(ExchangeStrategies.builder().codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(-1)).build())
            .baseUrl(url)
            .filter(errorHandlingFilter(platformService))
            .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON)
            .clientConnector(new ReactorClientHttpConnector(httpClient))
            .build();
```

and the filter is:
```java
    private ExchangeFilterFunction errorHandlingFilter(final PlatformService service) {
        return ExchangeFilterFunction.ofResponseProcessor(clientResponse -> {
            if (!isErrorStatusCode(clientResponse)) {
                return Mono.just(clientResponse);
            }

            final Optional<org.springframework.http.MediaType> mediaType = clientResponse.headers().contentType();
            boolean jsonResponse = true;

            if (mediaType.isPresent()) {
                final org.springframework.http.MediaType mt = mediaType.get();

                if (!mt.getType().equals("application") && !mt.getSubtype().equals("json")) {
                    jsonResponse = false;
                }
            }

            if (!clientResponse.statusCode().is5xxServerError()) {
                return clientResponse
                    .bodyToMono(String.class)
                    .flatMap(s -> Mono.error(new UpstreamException(s, service)));
            }

            if (!jsonResponse) {
                return clientResponse
                    .bodyToMono(String.class)
                    .flatMap(e -> Mono.error(new UpstreamException(e, service)));
            }

            return clientResponse
                .bodyToMono(RuntimeException.class)
                .flatMap(e -> Mono.error(new UpstreamException(e, service)));
        });
    }

```

Errors are happening randomly, but **all the time**.

DEBUG LOG:

```
3041011 [reactor-http-kqueue-138] DEBUG r.netty.http.client.HttpClient - [id: 0xe27945ea, L:/100.64.0.1:56184 ! R:xxx:443] INACTIVE
3041012 [reactor-http-kqueue-138] DEBUG r.n.r.PooledConnectionProvider - [id: 0xe27945ea, L:/100.64.0.1:56184 ! R:xxx:443] onStateChange(GET{uri=/data-store/portfolios/14?includeSummary=true, connection=PooledConnection{channel=[id: 0xe27945ea, L:/100.64.0.1:56184 ! R:xxx:443]}}, [response_incomplete])
3041013 [reactor-http-kqueue-138] WARN  r.n.http.client.HttpClientConnect - [id: 0xe27945ea, L:/100.64.0.1:56184 ! R:xxx:443] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
3041013 [reactor-http-kqueue-138] DEBUG r.netty.http.client.HttpClient - [id: 0xe27945ea, L:/100.64.0.1:56184 ! R:xxx:443] UNREGISTERED
3041013 [reactor-http-kqueue-138] DEBUG r.n.r.PooledConnectionProvider - [id: 0x896ef363] Created a new pooled channel, now 456 active connections and 0 inactive connections
```

**Comment by CantosSong** [comment]
Webclient needs to actively close TCP.
You can set the TCP timeout.

**Comment by violetagg** [comment]
@igr Are you able to test Reactor Netty latest release (0.9.10.RELEASE)

**Comment by igr** [comment]
Yes. I think Ive tried 0.9.9 with the same results; however let me try the latest one.

**Comment by igr** [comment]
I got only 4 errors in 1.5 hour tests - significantly less then yesterday, when I got maybe 200s of them:

```
Searching 1 file for "PrematureCloseException"

/Users/igr/Downloads/l3/eiq.log:
 505609  1360021 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/100.64.0.1:56671 ! R:xxx:443] onStateChange(GET{uri=/data-store/portfolios/10?includeSummary=true, connection=PooledConnection{channel=[id: 0x70d20cd1, L:/100.64.0.1:56671 ! R:xxx:443]}}, [response_incomplete])
 505610  1360021 [reactor-http-kqueue-6] WARN  r.n.http.client.HttpClientConnect - [id: 0x70d20cd1, L:/100.64.0.1:56671 ! R:xxx:443] The connection observed an error
 505611: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
 505612  1360021 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/100.64.0.1:56671 ! R:xxx:443] UNREGISTERED
 505613  1360022 [reactor-http-kqueue-15] DEBUG r.n.r.PooledConnectionProvider - [id: 0xb66cccbb, L:/100.64.0.1:56694 - R:xxx:443] Channel acquired, now 2 active connections and 0 inactive connections
 .....
 509672  1369505 [reactor-http-kqueue-8] DEBUG r.n.r.PooledConnectionProvider - [id: 0xb0654506, L:/100.64.0.1:56712 ! R:xxx:443] onStateChange(GET{uri=/data-store/portfolios/34?includeSummary=true, connection=PooledConnection{channel=[id: 0xb0654506, L:/100.64.0.1:56712 ! R:xxx:443]}}, [response_incomplete])
 509673  1369505 [reactor-http-kqueue-8] WARN  r.n.http.client.HttpClientConnect - [id: 0xb0654506, L:/100.64.0.1:56712 ! R:xxx:443] The connection observed an error
 509674: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
 509675  1369505 [reactor-http-kqueue-8] DEBUG r.netty.http.client.HttpClient - [id: 0xb0654506, L:/100.64.0.1:56712 ! R:xxx:443] UNREGISTERED
 509676  1369506 [reactor-http-kqueue-1] DEBUG r.netty.http.client.HttpClient - [id: 0x6550088d, L:/100.64.0.1:56737 - R:xxx:443] CLOSE
 .....
 512005  1376918 [reactor-http-kqueue-7] DEBUG r.n.r.PooledConnectionProvider - [id: 0x2d6d0876, L:/100.64.0.1:56749 ! R:xxx:443] onStateChange(GET{uri=/data-store/portfolios/34?includeSummary=true, connection=PooledConnection{channel=[id: 0x2d6d0876, L:/100.64.0.1:56749 ! R:xxx:443]}}, [response_incomplete])
 512006  1376918 [reactor-http-kqueue-7] WARN  r.n.http.client.HttpClientConnect - [id: 0x2d6d0876, L:/100.64.0.1:56749 ! R:xxx:443] The connection observed an error
 512007: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
 512008  1376918 [reactor-http-kqueue-7] DEBUG r.netty.http.client.HttpClient - [id: 0x2d6d0876, L:/100.64.0.1:56749 ! R:xxx:443] UNREGISTERED
 512009  1376918 [reactor-http-kqueue-14] DEBUG r.netty.http.client.HttpClient - [id: 0xbcc8c855, L:/100.64.0.1:56765 - R:xxx:443] USER_EVENT: SslHandshakeCompletionEvent(SUCCESS)
 .....
 512311  1377510 [reactor-http-kqueue-8] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd3b4d776, L:/100.64.0.1:56751 ! R:xxx:443] onStateChange(GET{uri=/data-store/portfolios/25?includeSummary=true, connection=PooledConnection{channel=[id: 0xd3b4d776, L:/100.64.0.1:56751 ! R:xxx:443]}}, [response_incomplete])
 512312  1377511 [reactor-http-kqueue-8] WARN  r.n.http.client.HttpClientConnect - [id: 0xd3b4d776, L:/100.64.0.1:56751 ! R:xxx:443] The connection observed an error
 512313: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
 512314  1377511 [reactor-http-kqueue-8] DEBUG r.netty.http.client.HttpClient - [id: 0xd3b4d776, L:/100.64.0.1:56751 ! R:xxx:443] UNREGISTERED
 512315  1377511 [reactor-http-kqueue-2] DEBUG r.n.r.PooledConnectionProvider - [id: 0x463f21b5] Created a new pooled channel, now 4 active connections and 0 inactive connections

4 matches in 1 file
```

**Comment by igr** [comment]
However, we are still registering the very same issues in the Sentry.io.

I wish there is more I can tell. I can't figure is the issue is with the client or the server is really closing connections. We will rewrite our client with old RestTemplate, and try the same.

**Comment by violetagg** [comment]
@igr If it is possible, can you give the logs per channel id? Let say not only when the connection is closed but also the previous logs. Take one channel id let say `id: 0x70d20cd1` and the logs for this id. You can remove the information that is confidential.

**Comment by igr** [comment]
Here
```
1354385 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1] Created a new pooled channel, now 2 active connections and 0 inactive connections
1354385 [reactor-http-kqueue-6] DEBUG reactor.netty.tcp.SslProvider - [id: 0x70d20cd1] SSL enabled using engine SSLEngineImpl and SNI internal.com:443
1354385 [reactor-http-kqueue-6] DEBUG r.netty.channel.BootstrapHandlers - [id: 0x70d20cd1] Initialized pipeline DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.sslReader = reactor.netty.tcp.SslProvider$SslReadHandler), (BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer#0 = reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.decompressor = io.netty.handler.codec.http.HttpContentDecompressor), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
1354387 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1] REGISTERED
1354387 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1] CONNECT: internal.com/xxx.xx.zz.x:443
1354404 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] Registering pool release on close event for channel
1354404 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] Channel connected, now 2 active connections and 0 inactive connections
1354404 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] ACTIVE
1354784 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1354784 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1354785 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1354785 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1354790 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1355012 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] USER_EVENT: SslHandshakeCompletionEvent(SUCCESS)
1355012 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] onStateChange(PooledConnection{channel=[id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443]}, [connected])
1355012 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443]}}, [configured])
1355013 [reactor-http-kqueue-6] DEBUG reactor.netty.ReactorNetty - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] Added decoder [ReadTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.sslHandler, reactor.left.loggingHandler, reactor.left.httpCodec, reactor.left.decompressor, ReadTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
1355013 [reactor-http-kqueue-6] DEBUG reactor.netty.ReactorNetty - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] Added decoder [WriteTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.sslHandler, reactor.left.loggingHandler, reactor.left.httpCodec, reactor.left.decompressor, ReadTimeoutHandler, WriteTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
1355013 [reactor-http-kqueue-6] DEBUG reactor.netty.ReactorNetty - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] Added encoder [IdleStateHandler] at the beginning of the user pipeline, full pipeline: [reactor.left.sslHandler, reactor.left.loggingHandler, reactor.left.httpCodec, reactor.left.decompressor, IdleStateHandler, ReadTimeoutHandler, WriteTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
1355013 [reactor-http-kqueue-6] DEBUG r.n.http.client.HttpClientConnect - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] Handler is being applied: {uri=https://internal.com/data-store/portfolios/10?includeSummary=true, method=GET}
1355013 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] onStateChange(GET{uri=/data-store/portfolios/10?includeSummary=true, connection=PooledConnection{channel=[id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443]}}, [request_prepared])
1355013 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] WRITE: 1024B
1355013 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] FLUSH
1355014 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] WRITE: 0B
1355014 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] FLUSH
1355014 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] onStateChange(GET{uri=/data-store/portfolios/10?includeSummary=true, connection=PooledConnection{channel=[id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443]}}, [request_sent])
1355014 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1360019 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] USER_EVENT: SslCloseCompletionEvent(SUCCESS)
1360019 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1360019 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1360020 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443] Channel closed, now 1 active connections and 1 inactive connections
1360020 [reactor-http-kqueue-6] DEBUG reactor.netty.ReactorNetty - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443] Non Removed handler: ReadTimeoutHandler, context: ChannelHandlerContext(ReadTimeoutHandler, [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443]), pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.decompressor = io.netty.handler.codec.http.HttpContentDecompressor), (IdleStateHandler = io.netty.handler.timeout.IdleStateHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
1360020 [reactor-http-kqueue-6] DEBUG reactor.netty.ReactorNetty - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443] Non Removed handler: WriteTimeoutHandler, context: ChannelHandlerContext(WriteTimeoutHandler, [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443]), pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.decompressor = io.netty.handler.codec.http.HttpContentDecompressor), (IdleStateHandler = io.netty.handler.timeout.IdleStateHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
1360020 [reactor-http-kqueue-6] DEBUG reactor.netty.ReactorNetty - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443] Non Removed handler: IdleStateHandler, context: ChannelHandlerContext(IdleStateHandler, [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443]), pipeline: DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.decompressor = io.netty.handler.codec.http.HttpContentDecompressor), (IdleStateHandler = io.netty.handler.timeout.IdleStateHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
1360021 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443] INACTIVE
1360021 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443] onStateChange(GET{uri=/data-store/portfolios/10?includeSummary=true, connection=PooledConnection{channel=[id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443]}}, [response_incomplete])
1360021 [reactor-http-kqueue-6] WARN  r.n.http.client.HttpClientConnect - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443] The connection observed an error
1360021 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 ! R:internal.com/xxx.xx.zz.x:443] UNREGISTERED
```

**Comment by violetagg** [comment]
@igr Can you tell us what's the time between these

```
1355014 [reactor-http-kqueue-6] DEBUG r.n.r.PooledConnectionProvider - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] onStateChange(GET{uri=/data-store/portfolios/10?includeSummary=true, connection=PooledConnection{channel=[id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443]}}, [request_sent])
1355014 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
1360019 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] USER_EVENT: SslCloseCompletionEvent(SUCCESS)
1360019 [reactor-http-kqueue-6] DEBUG r.netty.http.client.HttpClient - [id: 0x70d20cd1, L:/xxx.xx.xx.x:56671 - R:internal.com/xxx.xx.zz.x:443] READ COMPLETE
```

and also what time did you configure for `ReadTimeoutHandler` and `IdleStateHandler`?

**Comment by igr** [comment]
The first column @violetagg is the timestamp. Please see the first message, have all my timings there

**Comment by violetagg** [comment]
@igr What's the point to have ReadTimeoutHandler + IdleStateHandler with different time?

```
            .doOnConnected(conn -> conn
                .addHandlerLast(new ReadTimeoutHandler(
                    120_000,
                    TimeUnit.MILLISECONDS))
                .addHandlerLast(new WriteTimeoutHandler(
                    500,
                    TimeUnit.MILLISECONDS))
                .addHandler(new IdleStateHandler(
                    2_000,
                    500, 5000,
                    TimeUnit.MILLISECONDS)));
```

So from the logs there is 5min delay. Did you check whether the server sent the response successfully?

**Comment by igr** [comment]
Don't know about the timing, I was trying different options I saw online as I am desperate :) Would you be so kind to propose what would be better values instead?

I am not able to see the response, unfortunately. Our code gets exception, and we throws it further. The upstream is not under my control.

**Comment by violetagg** [comment]
@igr So from the logs I see the following Netty pipeline

```
full pipeline: [reactor.left.sslHandler, reactor.left.loggingHandler, reactor.left.httpCodec, reactor.left.decompressor, IdleStateHandler, ReadTimeoutHandler, WriteTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
```

From Netty javadoc https://netty.io/4.1/api/io/netty/handler/timeout/IdleStateHandler.html
`Triggers an IdleStateEvent when a Channel has not performed read, write, or both operation for a while...`
So basically you need another handler (see the full javadoc there is an example) that will do something when such an event is sent. From the pipeline above I do not think there is a handler that will process these events.

https://netty.io/4.1/api/io/netty/handler/timeout/ReadTimeoutHandler.html
`Raises a ReadTimeoutException when no data was read within a certain period of time...`

We will close the connection if such exception is thrown.

Do you see ReadTimeoutExceptions in the logs. This might be the reason for `Connection prematurely closed ....`.
You need to find a way to track why your upstream didn't send a response within the time that you defined as read timeout.

**Comment by igr** [comment]
Thats the thing, I don't see any other exception, like ReadTimeoutException.

Ok, thank you. I believe you can close the issue now.

**Comment by violetagg** [comment]
@igr I'm closing this issue, if it appears to be Reactor Netty problem, we can reopen it.

**Comment by igr** [comment]
Ok, just to share: after switching to RestTemplate, we are getting the following errors:

```
 504 Gateway Timeout: [{"message": "Network error communicating with endpoint"}]
```

However, not the same volume of it.

**Comment by violetagg** [comment]
@igr So with the latest Reactor Netty you said you see 4 errors, what's the number with RestTemplate < 4 or > 4?

**Comment by igr** [comment]
Unfortunately, I don't have precise numbers as I don't have much insight in our infrastructure. I am collecting errors with Sentry and I am seeing that after switching to RestTemplate we now have 504s.

Before we had _maybe_ 4x more PrematureCloseException's. But, as said, I can't be very exact with the numbers; moreover, I've been changing the reactor client configuration on a daily basis.

For now, I will continue monitoring our infrastructure.

I am 100% sure that our upstream servers are closing connections, but I am not sure if there is an _additional_ issue with the client itself :(

**Comment by violetagg** [comment]
@igr ok we can reopen this if it is Reactor Netty issue.

**Comment by lkgamor** [comment]
@igr I had the same issue that I kept battling with for 5 days wondering what exactly I had done wrong after a new feature deployment. I finally had my Eureka moment.

So in my *Dockerfile* I had exposed the default port *8080*. 

[![enter image description here][1]][1]
Which meant the tomcat server in my application image would always be available on that port. My container also had to be running on port 8080 (inside my .yml file) 
[![enter image description here][2]][2]

before I apply the port mapping directive to map the external port 9003 on my linux host to the 8080 in the container.
[![enter image description here][3]][3]

What I missed was that, during the deployment of the services using the **docker-compose file**, I forgot to change the **server.port** in the application.yml file to 8080 so that the port mapping could happen. I left it as 9003 *(because I was using 9003 on my local machine to test the app)* which meant anytime I started the containers using docker-compose, my service port was mapped as
> ***0.0.0.0:9003 -> 9003/tcp*** instead of ***0.0.0.0:9003 -> 8080/tcp***.

This was why the api-gateway kept throwing the 

> PrematureCloseException: Connection prematurely closed

 because there was actually no internal port 9003 found in the container instance of my microservice for the 9003 on the linux host to map to.

I just had to change the **9003** in my application.yml to **8080** and that was all.

  [1]: https://i.stack.imgur.com/p6AIg.png
  [2]: https://i.stack.imgur.com/PS954.png
  [3]: https://i.stack.imgur.com/IGCZc.png
