### ISSUE TITLE
Websocket handshake 404 

### ISSUE THREAD

**Issue by Hinsteny** [reactor/reactor-netty#1220]
reactor-netty(in spring-cloud-gateway) with istio do websocket forwarding will occured an  exception -- `Invalid handshake response getStatus: 404 Not Found`;

Websocket service calling chain, as blew

clinet ---> nginx ---> spring-cloud-gateway(reactor-netty) [ _**istio-sidecar**_] ---> background-service [_**istio-sidecar**_]

istio 1.6.1

## Expected Behavior

- [ √] clinet ---> nginx [ _**istio-sidecar**_]  ---> background-service [_**istio-sidecar**_]

- [ √] clinet ---> nginx ---> spring-cloud-gateway(reactor-netty)  ---> background-service [_**istio-sidecar**_]

- [ X] clinet ---> nginx ---> spring-cloud-gateway(reactor-netty) [ _**istio-sidecar**_] ---> background-service [_**istio-sidecar**_]

## Actual Behavior
I need the spring-cloud-gateway(reactor-netty) with istio to work properly together; 

## Steps to Reproduce
exception stack 
```
2020-07-24 16:42:54.624|DEBUG|TID:N/A|reactor-http-epoll-3|io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker[192]|[id: 0xc78ed948, L:/127.0.0.1:80 - R:/127.0.0.1:36890] WebSocket version V13 server handshake
2020-07-24 16:42:54.625|DEBUG|TID:N/A|reactor-http-epoll-3|io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker[153]|WebSocket version 13 server handshake key: websocket, response: qVby4apnn2tTYtB1nPPVYUn68gY=
2020-07-24 16:42:54.625|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.resources.PooledConnectionProvider[254]|[id: 0x17d919d2] Created a new pooled channel, now 1 active connections and 0 inactive connections
2020-07-24 16:42:54.626|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.channel.BootstrapHandlers[254]|[id: 0x17d919d2] Initialized pipeline DefaultChannelPipeline{(BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2020-07-24 16:42:54.626|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.resources.PooledConnectionProvider[249]|[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80] Registering pool release on close event for channel
2020-07-24 16:42:54.627|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.resources.PooledConnectionProvider[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80] Channel connected, now 1 active connections and 0 inactive connections
2020-07-24 16:42:54.627|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.resources.PooledConnectionProvider[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80] onStateChange(PooledConnection{channel=[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80]}, [connected])
2020-07-24 16:42:54.627|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.resources.PooledConnectionProvider[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80]}}, [configured])
2020-07-24 16:42:54.627|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.http.client.HttpClientConnect[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80] Handler is being applied: {uri=ws://urine.doctorwork-dev/v1/websocket/b05c6bb573c34571ae6dd221e9a7afec/1201010120010819, method=GET}
2020-07-24 16:42:54.627|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.resources.PooledConnectionProvider[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80] onStateChange(GET{uri=/v1/websocket/b05c6bb573c34571ae6dd221e9a7afec/1201010120010819, connection=PooledConnection{channel=[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80]}}, [request_prepared])
2020-07-24 16:42:54.627|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.ReactorNetty[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80] Added encoder [reactor.left.httpAggregator] at the beginning of the user pipeline, full pipeline: [reactor.left.httpCodec, reactor.left.httpAggregator, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
2020-07-24 16:42:54.627|DEBUG|TID:N/A|reactor-http-epoll-3|io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13[212]|WebSocket version 13 client handshake key: /E+TwsAZX3LpvZ09WpWe7Q==, expected response: xgdvrdHRgEmyx2067RpqvmCH3bY=
2020-07-24 16:42:57.325| WARN|TID:N/A|reactor-http-epoll-3|reactor.netty.http.client.HttpClientConnect[299]|[id: 0x17d919d2, L:/172.18.33.166:57110 - R:urine.doctorwork-dev/172.18.199.109:80] The connection observed an error
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: Invalid handshake response getStatus: 404 Not Found
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:274)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:302)
	at reactor.netty.http.client.WebsocketClientOperations.onInboundNext(WebsocketClientOperations.java:119)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
2020-07-24 16:42:57.326|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.http.server.HttpServerOperations[259]|[id: 0xc78ed948, L:/127.0.0.1:80 - R:/127.0.0.1:36890] Outbound error happened
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: Invalid handshake response getStatus: 404 Not Found
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:274)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ http://sword-gateway-server-istio/v1/websocket/b05c6bb573c34571ae6dd221e9a7afec/1201010120010819 [ReactorNettyRequestUpgradeStrategy]
Stack trace:
		at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:274)
		at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:302)
		at reactor.netty.http.client.WebsocketClientOperations.onInboundNext(WebsocketClientOperations.java:119)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Unknown Source)
2020-07-24 16:42:57.327|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.resources.PooledConnectionProvider[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 ! R:urine.doctorwork-dev/172.18.199.109:80] Channel closed, now 0 active connections and 0 inactive connections
2020-07-24 16:42:57.327|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.ReactorNetty[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 ! R:urine.doctorwork-dev/172.18.199.109:80] Non Removed handler: reactor.left.httpAggregator, context: null, pipeline: DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (ws-encoder = io.netty.handler.codec.http.websocketx.WebSocket13FrameEncoder), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2020-07-24 16:42:57.327|DEBUG|TID:N/A|reactor-http-epoll-3|reactor.netty.resources.PooledConnectionProvider[254]|[id: 0x17d919d2, L:/172.18.33.166:57110 ! R:urine.doctorwork-dev/172.18.199.109:80] onStateChange(ws{uri=/v1/websocket/b05c6bb573c34571ae6dd221e9a7afec/1201010120010819, connection=PooledConnection{channel=[id: 0x17d919d2, L:/172.18.33.166:57110 ! R:urine.doctorwork-dev/172.18.199.109:80]}}, [disconnecting])
```

## Possible Solution
I had debuged in my local, and found if i do a breakPoint at reactor.netty.internal.shaded.reactor.pool.SimplePool<POOLABLE> 155 line, then the forwarding is right;
```
155# allocator.subscribe((newInstance) -> {
                            borrower.deliver(this.createSlot(newInstance));
                        }, (e) -> {
```
io.netty.channel.epoll.AbstractEpollChannel  169 line

```
169#            if (!wasActive && active) {
                        pipeline().fireChannelActive();
                    }

```

## Your Environment

* Reactor version(s) used: reactor-netty-0.9.6.RELEASE.jar
* spring-cloud-starter-gateway versions :2.2.2
* spring-cloud-starter-gateway versions :2.2.2
* netty-transport-native-epoll: 4.1.48.Final-linux-x86_64
* istio: 1.6.1
*  (`javar -version`): 1.8
* OS and version (eg `uname -a`): 10.15.6
   Linux-server: Linux version 4.14.105-19-0008 (root@TENCENT64.site) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC))

**Comment by violetagg** [comment]
@Hinsteny Do you think it might be related to this issue https://github.com/spring-cloud/spring-cloud-gateway/issues/1834 ?

**Comment by violetagg** [comment]
@Hinsteny Were you able to check whether the proposed fix in Spring Gateway issue fixes your issue?

**Comment by violetagg** [comment]
@Hinsteny I'm closing this issue. If the problem appears in Reactor Netty we can reopen it.

**Comment by Orefa** [comment]
@violetagg I think this is the same problem, please reopen the problem 
https://github.com/spring-cloud/spring-cloud-gateway/issues/2115

**Comment by violetagg** [comment]
@Orefa I created a PR (#1635) that fixed the mentioned SCG issue.

**Comment by Jerry29** [comment]
Hi @violetagg , Any help on https://github.com/spring-cloud/spring-cloud-gateway/issues/2283

**Comment by violetagg** [comment]
@Jerry29 I replied in the mentioned SCG issue, but let me copy here the answer for a completeness.

According to the specification the header names are case-insensitive 

https://datatracker.ietf.org/doc/html/rfc7230#section-3.2

```
Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.
```

**Comment by Jerry29** [comment]
Yeah I agree, but what i am trying to access is a camera's web. It seems they are expecting the headers to be case sensitive. Is there a way I can override these three headers ?

**Comment by violetagg** [comment]
@Jerry29 Let's continue the discussion in SCG issue and not spam this one anymore.
