### ISSUE TITLE
Graceful shutdown and connection kept alive

### ISSUE THREAD

**Issue by jkuhnv** [reactor/reactor-netty#1247]
We experience 500 Internal server errors when sending requests to an application during graceful shutdown In our spring boot application. We are able to reproduce this behavior in a browser when the request is sent with "Connection: keep-alive" header.

The conditions are following:
- browser tab1: a long time taking request
- browser tab2: many short time taking requests

## Expected Behavior
All idle existing connections are closed. _Any_ new request is refused during graceful shutdown.

## Actual Behavior
The shutdown signal is sent during the long request is being active. The graceful shutdown is activated and the application waits until the long request is processed. But the application is still receiving and processing another requests from the same browser (tab2). Trying to connect from different browser is correctly refused.

## Steps to Reproduce
Generate spring gateway application in initializr. Add following bean:

```java
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import javax.annotation.PreDestroy;
import java.util.concurrent.TimeUnit;

@Component
public class SlowDestroyBean {
    @PreDestroy
    public void destroy() throws InterruptedException {
        LoggerFactory.getLogger("SlowDestroyBean").info("destroy - start");
        TimeUnit.SECONDS.sleep(2);
        LoggerFactory.getLogger("SlowDestroyBean").info("destroy - end");
    }
}
```

with following configuration in application.yaml:
```
server:
  shutdown: graceful

spring:
  cloud:
    gateway:
      routes:
      - id: httpbin
        uri: http://httpbin.org:80
        predicates:
          - Path=/httpbin/**
        filters:
          - RewritePath=/httpbin(/)?(.*)?, /$2
```
[gracefulshutdown.zip](https://github.com/reactor/reactor-netty/files/5027845/gracefulshutdown.zip)

Long request: http://localhost:8080/httpbin/delay/10
Quick request: http://localhost:8080/httpbin/headers

Here is a log where the scenario is caught (executed with access log turned on):
```
$ java -Dreactor.netty.http.server.accessLogEnabled=true -jar build/libs/gracefulshutdown-0.0.1-SNAPSHOT.jar
...
2020-08-04 17:27:17.819  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:17 +0200] "GET /httpbin/headers HTTP/1.1" 200 916 8080 146 ms
2020-08-04 17:27:19.291  INFO 34211 --- [extShutdownHook] o.s.b.w.embedded.netty.GracefulShutdown  : Commencing graceful shutdown. Waiting for active requests to complete
2020-08-04 17:27:20.429  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:20 +0200] "GET /httpbin/headers HTTP/1.1" 200 916 8080 142 ms
2020-08-04 17:27:21.093  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:20 +0200] "GET /httpbin/headers HTTP/1.1" 200 916 8080 146 ms
2020-08-04 17:27:21.980  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:21 +0200] "GET /httpbin/headers HTTP/1.1" 200 916 8080 163 ms
2020-08-04 17:27:22.723  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:22 +0200] "GET /httpbin/headers HTTP/1.1" 200 916 8080 146 ms
2020-08-04 17:27:23.447  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:23 +0200] "GET /httpbin/headers HTTP/1.1" 200 916 8080 142 ms
2020-08-04 17:27:24.886  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:24 +0200] "GET /httpbin/headers HTTP/1.1" 200 916 8080 147 ms
2020-08-04 17:27:25.711  INFO 34211 --- [ctor-http-nio-2] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:15 +0200] "GET /httpbin/delay/10 HTTP/1.1" 200 1063 8080 10148 ms
2020-08-04 17:27:25.711  INFO 34211 --- [ netty-shutdown] o.s.b.w.embedded.netty.GracefulShutdown  : Graceful shutdown complete
2020-08-04 17:27:25.715  INFO 34211 --- [extShutdownHook] SlowDestroyBean                          : destroy - start
2020-08-04 17:27:25.743  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:25 +0200] "GET /httpbin/headers HTTP/1.1" 200 916 8080 161 ms
2020-08-04 17:27:26.670 ERROR 34211 --- [ctor-http-nio-3] a.w.r.e.AbstractErrorWebExceptionHandler : [238a1ee7-14]  500 Server Error for HTTP GET "/httpbin/headers"

org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'defaultValidator': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:212) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/httpbin/headers" [ExceptionHandlingWebHandler]
Stack trace:
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:212) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:90) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:192) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at com.sun.proxy.$Proxy57.forExecutables(Unknown Source) ~[na:na]
		at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:99) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
		at org.springframework.cloud.gateway.config.HttpClientProperties$$EnhancerBySpringCGLIB$$dd5ff8d.getConnectTimeout(<generated>) ~[spring-cloud-gateway-core-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
		at org.springframework.cloud.gateway.config.GatewayAutoConfiguration$NettyConfiguration.lambda$gatewayHttpClient$4(GatewayAutoConfiguration.java:642) ~[spring-cloud-gateway-core-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
		at reactor.netty.http.client.HttpClientTcpConfig.tcpConfiguration(HttpClientTcpConfig.java:38) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at reactor.netty.http.client.HttpClientHeaders.tcpConfiguration(HttpClientHeaders.java:44) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at reactor.netty.http.client.HttpClient.request(HttpClient.java:974) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter(NettyRoutingFilter.java:140) ~[spring-cloud-gateway-core-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:138) ~[spring-cloud-gateway-core-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
		at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44) ~[spring-cloud-gateway-core-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:118) ~[spring-cloud-gateway-core-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:274) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:851) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:274) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:851) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onNext(MonoFilterWhen.java:140) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onSubscribe(MonoFilterWhen.java:103) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:441) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:243) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:91) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:38) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.request(FluxDematerialize.java:120) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:228) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onSubscribe(FluxDematerialize.java:70) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:441) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:211) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar!/:3.3.8.RELEASE]
		at reactor.netty.http.server.HttpServerHandle.onStateChange(HttpServerHandle.java:65) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:514) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at reactor.netty.tcp.TcpServerBind$ChildObserver.onStateChange(TcpServerBind.java:267) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:462) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:170) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at reactor.netty.http.server.AccessLogHandler.channelRead(AccessLogHandler.java:51) ~[reactor-netty-0.9.10.RELEASE.jar!/:0.9.10.RELEASE]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-08-04 17:27:26.683  INFO 34211 --- [ctor-http-nio-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [04/Aug/2020:17:27:26 +0200] "GET /httpbin/headers HTTP/1.1" 500 307 8080 135 ms
2020-08-04 17:27:27.720  INFO 34211 --- [extShutdownHook] SlowDestroyBean                          : destroy - end

```

## Your Environment
* Reactor-netty version: 2.3.2
* Reactor-core version: 3.3.8
* netty: 4.1.51
* JVM version (`javar -version`): openjdk version "11.0.8" 2020-07-14
* OS and version: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by jkuhnv** [comment]
What I forgot to mention is that our service runs in kubernetes where the current behavior prevent us doing safe rolling update.

When searching the internet, it looks like when a pod receives a term signal, kube-proxy doesn't change routing rules for active connections (my understanding is that this might be the case for keep-alive connections) and requests may still reach the pod already in shutdown process. 

This manifests especially if there is at least one long request, typically a file upload.

**Comment by jkuhnv** [comment]
This is a nice article about how it works in k8s related to a pod shutdown
https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
At the end, there are following steps what should an application do:
- stop accepting new connections
- close all keep-alive connections that aren’t in the middle of a request
- wait for all active requests to finish, and then
- shut down completely
I believe that the issue I'm talking about is related to the second step.

**Comment by violetagg** [comment]
@jkuhnv I'm working on this. I can reproduce it.

**Comment by violetagg** [comment]
@jkuhnv If you are able please test 0.9.12.BUILD-SNAPSHOT

**Comment by jkuhnv** [comment]
Looks good! 👍
