### ISSUE TITLE
readAddress(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by uzdz** [reactor/reactor-netty#1299]
Hello developer:
At present, when my program uses lettuce, the following exception will be thrown in the next request after a long time of no operation.

Here is my client configuration and exception information.For security, IP information has been erased.

```yaml
spring:
  redis:
    # redis数据库索引（默认为0）
    database: 1
    # redis服务器地址（默认为localhost）
    host: xxx.xxx.xx
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: 123456
    # redis连接超时时间（单位为毫秒）
    timeout: 10000
    # redis连接池配置
    lettuce:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: -1
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: -1
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
```

```txt
exception; nested exception is io.lettuce.core.RedisException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.setEx(LettuceStringCommands.java:232)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.setEx(DefaultedRedisConnection.java:308)
	at org.springframework.data.redis.core.DefaultValueOperations$4.potentiallyUsePsetEx(DefaultValueOperations.java:268)
	at org.springframework.data.redis.core.DefaultValueOperations$4.doInRedis(DefaultValueOperations.java:261)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:256)
```

However, after an exception occurs, the following log will be output. It seems that a reconnection operation has occurred, and subsequent business operations can normally request redis.

```txt
2020-08-31 16:39:25.171 [lettuce-eventExecutorLoop-1-2] INFO  i.l.c.p.ConnectionWatchdog [log:171]     - Reconnecting, last destination was xxx.xx.xx.xx/xxx.xx.xx.xx:6379
2020-08-31 16:39:25.177 [lettuce-epollEventLoop-6-1] INFO  i.l.c.p.ReconnectionHandler [lambda$null$4:188]     - Reconnected to xxx.xx.xx.xx:6379
```

The version of springboot we use is:

```xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.0.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
    </parent>
```

The version of lettuce used internally is:

```txt
5.3.0.RELEASE
```

I can't find the exception, so what is the reason for this situation?

**Comment by violetagg** [comment]
@uzdz May be you need to open an issue in Lettuce project. I do not see here any Reactor Netty code.

**Comment by uzdz** [comment]
This is the reply from lettuce. Can you ask the reason for this error? I might be able to find out for myself.

```txt
(Connection reset by peer) is a server-side state change without following the full TCP close procedure. Typically, that is when the server process dies or if active network components terminate the connection because of inactivity. See https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean for further reference. There's nothing really we can do from our side.
```

**Comment by Zhengxiuhang** [comment]
@uzdz may be you can try custom socket options `keepalive` as true from lettuce

here is my code

```Java
@Bean
    public LettuceClientConfigurationBuilderCustomizer lettuceClientConfigurationBuilderCustomizer(@Autowired RedisProperties redisProperties) {
        return clientConfigurationBuilder -> {
            ClusterClientOptions.Builder builder = ClusterClientOptions.builder();
            RedisProperties.Lettuce.Cluster.Refresh refreshProperties = redisProperties.getLettuce().getCluster().getRefresh();
            ClusterTopologyRefreshOptions.Builder refreshBuilder = ClusterTopologyRefreshOptions.builder();
            if (refreshProperties.getPeriod() != null) {
                refreshBuilder.enablePeriodicRefresh(refreshProperties.getPeriod());
            }
            if (refreshProperties.isAdaptive()) {
                refreshBuilder.enableAllAdaptiveRefreshTriggers();
            }
            builder.topologyRefreshOptions(refreshBuilder.build());
            builder.socketOptions(SocketOptions.builder().keepAlive(true).build());
            clientConfigurationBuilder.clientOptions(builder.build());
        };
    }
```
