### ISSUE TITLE
OutOfDirectMemoryError: failed to allocate 524483910 byte(s) of direct memory (used: 3271557127, max: 3795845120)

### ISSUE THREAD

**Issue by wutingting1993** [reactor/reactor-netty#1310]
**when I use spring-boot 2.3.4 download with a big file (example 40M), OutOfDirectMemoryError occured.** 
but when I use vertx, that works well, vertx version is 3.5.3

If it does not reproduce, please try a few more times. All the configurations are default and have not been changed。

### Codes
```
@Bean
	public WebClient webClient() {
		return WebClient.builder()
			.exchangeStrategies(ExchangeStrategies.builder().codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(-1)).build())
			.build();
	}
```

```

String endpointUrl = "http://localhost:8080/bigfile";
		AtomicReference<ClientResponse> clientResponseAtomicReference = new AtomicReference<>();

		try {
			return webClient.method(HttpMethod.GET)
				.uri(endpointUrl)
				.body(serverRequest.bodyToMono(byte[].class), byte[].class)
				.exchange()
				.doOnDiscard(PooledDataBuffer.class, DataBufferUtils::release)
				.flatMap(clientResponse -> {
					clientResponseAtomicReference.set(clientResponse);
					return ServerResponse.status(clientResponse.statusCode())
						.headers(headers -> headers.addAll(clientResponse.headers().asHttpHeaders()))
						.body(clientResponse.bodyToMono(byte[].class), byte[].class);
				}).doOnCancel(() -> releaseClientResponse(clientResponseAtomicReference))
				.onErrorResume(throwable -> {
					releaseClientResponse(clientResponseAtomicReference);
					return ServerResponse.status(HttpStatus.INTERNAL_SERVER_ERROR).bodyValue(throwable.getMessage());
				});
		} catch (Throwable throwable) {
			releaseClientResponse(clientResponseAtomicReference);
			return ServerResponse.status(HttpStatus.INTERNAL_SERVER_ERROR).bodyValue(throwable.getMessage());
		}
```

### Exception
```
2020-09-18 17:17:06.635 DEBUG 14152 --- [ctor-http-nio-4] r.n.http.server.HttpServerOperations     : [id: 0xb6e98566, L:/0:0:0:0:0:0:0:1:9001 - R:/0:0:0:0:0:0:0:1:64680] New http connection, requesting read
2020-09-18 17:17:06.636 DEBUG 14152 --- [ctor-http-nio-4] reactor.netty.channel.BootstrapHandlers  : [id: 0xb6e98566, L:/0:0:0:0:0:0:0:1:9001 - R:/0:0:0:0:0:0:0:1:64680] Initialized pipeline DefaultChannelPipeline{(BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpServerCodec), (reactor.left.httpTrafficHandler = reactor.netty.http.server.HttpTrafficHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2020-09-18 17:17:06.637 DEBUG 14152 --- [ctor-http-nio-4] r.n.http.server.HttpServerOperations     : [id: 0xb6e98566, L:/0:0:0:0:0:0:0:1:9001 - R:/0:0:0:0:0:0:0:1:64680] Increasing pending responses, now 1
2020-09-18 17:17:06.637 DEBUG 14152 --- [ctor-http-nio-4] reactor.netty.http.server.HttpServer     : [id: 0xb6e98566, L:/0:0:0:0:0:0:0:1:9001 - R:/0:0:0:0:0:0:0:1:64680] Handler is being applied: org.springframework.http.server.reactive.ReactorHttpHandlerAdapter@6dc781bb
2020-09-18 17:17:06.639 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] Channel acquired, now 1 active connections and 0 inactive connections
2020-09-18 17:17:06.639 DEBUG 14152 --- [ctor-http-nio-3] r.netty.http.client.HttpClientConnect    : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] Handler is being applied: {uri=http://localhost:8082/apigw/v1/tenants/bigfile, method=GET}
2020-09-18 17:17:06.639 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] onStateChange(GET{uri=/apigw/v1/tenants/bigfile, connection=PooledConnection{channel=[id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082]}}, [request_prepared])
2020-09-18 17:17:06.639 DEBUG 14152 --- [ctor-http-nio-3] reactor.netty.channel.FluxReceive        : [id: 0xb6e98566, L:/0:0:0:0:0:0:0:1:9001 - R:/0:0:0:0:0:0:0:1:64680] FluxReceive{pending=0, cancelled=false, inboundDone=true, inboundError=null}: subscribing inbound receiver
2020-09-18 17:17:06.640 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] onStateChange(GET{uri=/apigw/v1/tenants/bigfile, connection=PooledConnection{channel=[id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082]}}, [request_sent])
2020-09-18 17:17:07.252 DEBUG 14152 --- [ctor-http-nio-3] r.n.http.client.HttpClientOperations     : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] Received response (auto-read:false) : [X-NCP-USER_REQ_ID=e38adcfd-af74-4bf0-bd04-bb259009e3a4, X-Application-Context=application:local:8082, Content-Disposition=attachment; filename=aaa.rar, Content-Type=application/octet-stream, Content-Length=524483910, Date=Fri, 18 Sep 2020 09:17:07 GMT]
2020-09-18 17:17:07.252 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] onStateChange(GET{uri=/apigw/v1/tenants/bigfile, connection=PooledConnection{channel=[id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082]}}, [response_received])
2020-09-18 17:17:07.254 DEBUG 14152 --- [ctor-http-nio-3] reactor.netty.channel.FluxReceive        : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] FluxReceive{pending=0, cancelled=false, inboundDone=false, inboundError=null}: subscribing inbound receiver
2020-09-18 17:17:13.638 DEBUG 14152 --- [ctor-http-nio-3] r.n.http.client.HttpClientOperations     : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] Received last HTTP packet
2020-09-18 17:17:14.079 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] onStateChange(GET{uri=/apigw/v1/tenants/bigfile, connection=PooledConnection{channel=[id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082]}}, [response_completed])
2020-09-18 17:17:14.079 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] onStateChange(GET{uri=/apigw/v1/tenants/bigfile, connection=PooledConnection{channel=[id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082]}}, [disconnecting])
2020-09-18 17:17:14.079 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] Releasing channel
2020-09-18 17:17:14.079 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 - R:localhost/127.0.0.1:8082] Channel cleaned, now 0 active connections and 1 inactive connections
2020-09-18 17:17:14.083 DEBUG 14152 --- [ctor-http-nio-4] r.n.http.server.HttpServerOperations     : [id: 0xb6e98566, L:/0:0:0:0:0:0:0:1:9001 - R:/0:0:0:0:0:0:0:1:64680] Decreasing pending responses, now 0
2020-09-18 17:17:14.093  WARN 14152 --- [ctor-http-nio-4] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by reactor.netty.FutureMono$FutureSubscription.operationComplete()

io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 524483910 byte(s) of direct memory (used: 3271557127, max: 3795845120)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.test.oom.GatewayHandler@24e7a1be [DispatcherHandler]
Stack trace:
		at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:645) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:635) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:215) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena.allocate(PoolArena.java:143) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena.allocate(PoolArena.java:128) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:378) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.AbstractNioChannel.newDirectBuffer(AbstractNioChannel.java:442) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:278) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:874) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.write(CombinedChannelDuplexHandler.java:521) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:137) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:117) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at reactor.netty.http.server.HttpTrafficHandler.write(HttpTrafficHandler.java:271) ~[reactor-netty-0.9.12.RELEASE.jar:0.9.12.RELEASE]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2020-09-18 17:17:14.094 DEBUG 14152 --- [ctor-http-nio-4] r.n.http.server.HttpServerOperations     : [id: 0xb6e98566, L:/0:0:0:0:0:0:0:1:9001 - R:/0:0:0:0:0:0:0:1:64680] Sending last HTTP packet was not successful, terminating the channel

io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 524483910 byte(s) of direct memory (used: 3271557127, max: 3795845120)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.test.oom.GatewayHandler@24e7a1be [DispatcherHandler]
Stack trace:
		at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:645) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:635) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:215) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena.allocate(PoolArena.java:143) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PoolArena.allocate(PoolArena.java:128) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:378) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) ~[netty-buffer-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.AbstractNioChannel.newDirectBuffer(AbstractNioChannel.java:442) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:278) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:874) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.write(CombinedChannelDuplexHandler.java:521) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:137) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:117) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at reactor.netty.http.server.HttpTrafficHandler.write(HttpTrafficHandler.java:271) ~[reactor-netty-0.9.12.RELEASE.jar:0.9.12.RELEASE]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.52.Final.jar:4.1.52.Final]
		at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2020-09-18 17:18:13.668 DEBUG 14152 --- [ctor-http-nio-3] r.n.resources.PooledConnectionProvider   : [id: 0x25f0bc33, L:/127.0.0.1:64675 ! R:localhost/127.0.0.1:8082] onStateChange(PooledConnection{channel=[id: 0x25f0bc33, L:/127.0.0.1:64675 ! R:localhost/127.0.0.1:8082]}, [disconnecting])

```

### Netty version ( spring-boot 2.3.4)
```
Maven: io.netty:netty-buffer:4.1.52.Final
Maven: io.netty:netty-codec:4.1.52.Final
Maven: io.netty:netty-codec-http2:4.1.52.Final
Maven: io.netty:netty-codec-http:4.1.52.Final
Maven: io.netty:netty-codec-socks:4.1.52.Final
Maven: io.netty:netty-common:4.1.52.Final
Maven: io.netty:netty-handler:4.1.52.Final
Maven: io.netty:netty-handler-proxy:4.1.52.Final
Maven: io.netty:netty-resolver:4.1.52.Final
Maven: io.netty:netty-transport:4.1.52.Final
Maven: io.netty:netty-transport-native-epoll:linux-x86_64:4.1.52.Final
Maven: io.netty:netty-transport-native-unix-common:4.1.52.Final
Maven: io.projectreactor.netty:reactor-netty:0.9.12.RELEASE
Maven: io.projectreactor:reactor-core:3.3.10.RELEASE
Maven: io.projectreactor:reactor-test:3.3.10.RELEASE
```

**Comment by violetagg** [comment]
@wutingting1993 Enable logging for Netty (io.netty=DEBUG) and tell us what's the configuration for `maxDirectMemory` when you run with Spring and when with Vert.x

**Comment by wutingting1993** [comment]
@violetagg 

please check error log again, I already Enable logging for Netty (io.netty=DEBUG) .

and when I change code as follows, it seems solved. Is there any difference between these two ways.
#### **as is** 
`body(clientResponse.bodyToMono(byte[].class), byte[].class)`

#### **to be** 
`body(BodyInserters.fromDataBuffers(clientResponse.body(BodyExtractors.toDataBuffers())))`

**Comment by wutingting1993** [comment]
maxDirectMemory is 16777216 when you run with Spring and when with Vert.x

**Comment by violetagg** [comment]
> maxDirectMemory is 16777216 when run with Spring and when with Vert.x

That's very interesting because in the exception above it is `(used: 3271557127, max: 3795845120)`

Also I was asking for Netty logs not Reactor Netty (I do not see above logs from Netty)

**Comment by violetagg** [comment]
> @violetagg
> 
> please check error log again, I already Enable logging for Netty (io.netty=DEBUG) .
> 
> and when I change code as follows, it seems solved. Is there any difference between these two ways.
> 
> #### **as is**
> `body(clientResponse.bodyToMono(byte[].class), byte[].class)`
> 
> #### **to be**
> `body(BodyInserters.fromDataBuffers(clientResponse.body(BodyExtractors.toDataBuffers())))`

This should be reported to Spring Framework as it is not an API provided by Reactor Netty

**Comment by wutingting1993** [comment]
> > maxDirectMemory is 16777216 when run with Spring and when with Vert.x
> 
> That's very interesting because in the exception above it is `(used: 3271557127, max: 3795845120)`
> 
> Also I was asking for Netty logs not Reactor Netty (I do not see above logs from Netty)

Sorry for give you error size.max size is 3795845120.  and there is no other logs

**Comment by rstoyanchev** [comment]
When you extract to `byte[]` you are making a copy of the buffers from the client, which are then copied yet again to the buffers of the response. That's 3 times the memory vs passing them as is as DataBuffer's.

**Comment by wutingting1993** [comment]
@rstoyanchev 

thanks for you explain.
