### ISSUE TITLE
NoClassDefFoundError for reactor.util.context.ContextView using an HttpClient with reactor-netty-core and reactor-netty-http

### ISSUE THREAD

**Issue by eriklumme** [reactor/reactor-netty#1388]
Consider the following piece of code

    HttpClient.create().get().uri("https://www.google.com").response().block();

And using the `1.0.1` versions of `reactor-netty-core` and `reactor-netty-http`, running the code produces the error below. 
If both dependencies are changed out for the `0.9.14.RELEASE` version of `reactor-netty`, the code works.

    java.lang.NoClassDefFoundError: reactor/util/context/ContextView

	at reactor.netty.internal.shaded.reactor.pool.PoolBuilder.buildPool(PoolBuilder.java:411)
	at reactor.netty.resources.PooledConnectionProvider$PoolFactory.newPool(PooledConnectionProvider.java:250)
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator.<init>(DefaultPooledConnectionProvider.java:517)
	at reactor.netty.resources.DefaultPooledConnectionProvider.createPool(DefaultPooledConnectionProvider.java:98)
	at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$0(PooledConnectionProvider.java:104)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:99)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:260)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:263)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
	at reactor.core.publisher.Mono.block(Mono.java:1679)

## Expected Behavior

There is no error.

## Actual Behavior

A `NoClassDefFoundError` is produced.

## Steps to Reproduce

1. Use the dependencies `io.projectreactor.netty:reactor-netty-core:1.0.1` and `io.projectreactor.netty:reactor-netty-http:1.0.1`.
2. Run the code below.

```java
@Test
void testCase() {
    HttpClient.create().get().uri("https://www.google.com").response().block();
}
```

## Your Environment

* JVM version (`javar -version`): OpenJDK Corretto 11.0.8
* OS and version (eg `uname -a`): Windows 10

**Comment by violetagg** [comment]
@eriklumme Reactor Netty 1.0x depends on Reactor Core 3.4.x so if you didn't update Reactor Core then you have to update it. Reactor Netty 1.0.x does not work with previous versions of Reactor Core.
It will be easier for you if you use Reactor BOM https://github.com/reactor/reactor/releases

**Comment by eriklumme** [comment]
@violetagg thanks, sorry, that was my bad. I have a parent POM which in turn uses Spring Boot's BOM, and I didn't notice that it defined the Reactor Core version as 3.3.11.RELEASE.

**Comment by violetagg** [comment]
@eriklumme Reactor Netty 1.0.0 has some incompatibilities that affect how the configuration is done. You may have issues with old versions of Spring Framework/Spring Boot. I would recommend to switch to Spring Boot 2.4.0.
