### ISSUE TITLE
Stuck Active Connections

### ISSUE THREAD

**Issue by pavelkuchin** [reactor/reactor-netty#1401]
We are having an issues with stuck active connections. At some arbitrary moments number of active connections starts growing till exhaustion of connection pool. Usually it happens few times a day and gets back to normal after service restart. We can't reproduce the issue with integration or load tests and can't correlate it with load. Once number of active connections is growing CPU consumption spikes to 100% and most active threads are reactor-http-epoll. It started at night from November 20 to 21 and since than happens at least few times a day. Last deployment was on Wednesday and we did't have any infrastructure changes on the night on our side. The service is on AWS ECS.   

## Expected Behavior
Number of active connection should not grow till pool exhaustion. 

## Actual Behavior
Connections pool gets exhausted by growing number of active connections.  

## Steps to Reproduce
Reproducible only on production environment at arbitrary moments.

## Possible Solution
The only solution we found is to restart the service on regular basis.

## Your Environment
* Reactor version(s) used: Dysprosium-SR14
* Reactor Netty: 0.9.14
* JVM version (`java -version`): 
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

* OS and version (eg. `uname -a`): Linux 1e0330d34cf6 4.14.200-155.322.amzn2.x86_64 #1 SMP Thu Oct 15 20:11:12 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
@pavelkuchin Please provide some code how the client is configured and used.
Tell us whether you use `exchange` or `retrieve`. With `exchange` if you do not consume the response body you can cause memory leak and connection leak.

**Comment by yangbongsoo** [comment]
@violetagg  Hello I have question about `exchange` use.
for example, response is success but response status code is 500  and has a response body,
in below code, `result.getBody();` method doesn't called. that cause memory leak?

or in onErrorResume, that cause memory leak?
thanks in advance :) 

```java
.exchange()
.flatMap(res -> res.toEntity(String.class))
.doOnNext(result -> {
	if (result.getStatusCode() != HttpStatus.OK) {
		throw new RequestFailException();
	}
})
.retryWhen(Retry.any().fixedBackoff(Duration.ofMillis(500)).retryMax(1)
		.doOnRetry((context) -> {
			logger.info("just for log : ", context.exception());
		}))
.doOnSuccess(
		result -> {
				if (result.getStatusCode() == HttpStatus.OK) {
					String body = result.getBody();
				} else {
					// 1. can cause memory leak???
				}
		})
.onErrorResume(error -> {
	// 2. if retry count is over and fail again, can cause memory leak???
	return just(new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR));
});
```

**Comment by rstoyanchev** [comment]
>  I have question about exchange use.
> for example, response is success but response status code is 500 and has a response body,
> in below code, result.getBody(); method doesn't called. that cause memory leak?

Yes it can. I suggest using `.retrieve().toEntity(String.class)`. This automatically turns 4xx-5xx status codes into a `WebClientResponseException` which includes the body content. You can add an additional `.onStatus` handler to reject any other 2xx-3xx status codes besides OK if necessary.

**Comment by pavelkuchin** [comment]
Hi Violeta, thanks for getting back so quickly. Here is one example but all our clients are using `retrieve` method:
```
        return webClient
                .post()
                .uri(String.format(BASIC_API_URI, apiKey))
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(request.getT1())
                .retrieve()
                .bodyToMono(ApiResponse.class)
                .transform(r -> ReactiveUtils.enableMetricsForMono(r, "metric_name"))
                .timeout(Duration.ofSeconds(30))
                .transform(this::handleErrorsAndRetryWithBackoff)
                .flatMapMany(response -> toTranslatedTextOrTranslationError(response, request.getT2()));
```
and here is initial client configuration:
```
        HttpClient httpClient = HttpClient.create(
                ConnectionProvider.builder("x")
                        .metrics(true)
                        .build()
        );

        return WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(httpClient))
                .baseUrl("https://x.com")
                .build();
```
After experiments we got this, but neither from the settings helped:
```
        HttpClient httpClient = HttpClient.create(
                ConnectionProvider.builder("x")
                        .pendingAcquireMaxCount(256)
                        .maxConnections(52)
                        .maxIdleTime(Duration.ofSeconds(30))
                        .maxLifeTime(Duration.ofSeconds(60))
                        .evictInBackground(Duration.ofMinutes(5))
                        .metrics(true)
                        .build()
        );

        return WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(httpClient))
                .baseUrl("https://x.com")
                .build();
```

**Comment by pavelkuchin** [comment]
Here are some logs which I think might be related to the problem:
```
11/29/20
7:38:19.513 PM    
2020-11-30 00:38:19,513 +0000 [reactor-http-epoll-1] [DEBUG] (r.n.r.PooledConnectionProvider:?) [8bbde608-86d7-40e2-90ee-6b84797e9243#jkto] - [id: 0xe31e9eb0, L:/masked:masked - R:masked/masked:masked] Channel connected, now 2 active connections and 0 inactive connections
host = masked/c03060e213b3 source = masked.log sourcetype = log4j
11/29/20
7:38:19.513 PM    
2020-11-30 00:38:19,513 +0000 [reactor-http-epoll-1] [DEBUG] (r.n.r.PooledConnectionProvider:?) [8bbde608-86d7-40e2-90ee-6b84797e9243#jkto] - [id: 0xe31e9eb0, L:/masked:masked - R:masked/masked:masked] Registering pool release on close event for channel
host = masked/c03060e213b3 source = masked.log sourcetype = log4j
11/29/20
7:38:19.511 PM    
2020-11-30 00:38:19,511 +0000 [reactor-http-epoll-1] [DEBUG] (reactor.netty.tcp.SslProvider:?) [44e53d93-1496-4b4c-bf3c-c528d6ac4a16#un4m] - [id: 0xe31e9eb0] SSL enabled using engine SSLEngineImpl and SNI masked:masked
host = masked/c03060e213b3 source = masked.log sourcetype = log4j
11/29/20
7:37:58.133 PM    
2020-11-30 00:37:58,133 +0000 [reactor-http-epoll-3] [DEBUG] (r.n.r.PooledConnectionProvider:?) [bd61425b-58c0-4482-beb8-6970913b46cb#hzsb] - [id: 0x675d970b, L:/masked:masked ! R:masked/masked:masked] onStateChange(PooledConnection{channel=[id: 0x675d970b, L:/masked:masked ! R:masked/masked:masked]}, [disconnecting])
host = masked/c03060e213b3 source = masked.log sourcetype = log4j
11/29/20
7:37:27.964 PM    
2020-11-30 00:37:27,964 +0000 [reactor-http-epoll-3] [DEBUG] (r.n.r.PooledConnectionProvider:?) [bd61425b-58c0-4482-beb8-6970913b46cb#hzsb] - [id: 0x675d970b, L:/masked:masked - R:masked/masked:masked] Channel cleaned, now 0 active connections and 1 inactive connections
host = masked/c03060e213b3 source = masked.log sourcetype = log4j
11/29/20
7:37:27.963 PM    
2020-11-30 00:37:27,963 +0000 [reactor-http-epoll-3] [DEBUG] (r.n.r.PooledConnectionProvider:?) [bd61425b-58c0-4482-beb8-6970913b46cb#hzsb] - [id: 0x675d970b, L:/masked:masked - R:masked/masked:masked] Releasing channel
```

**Comment by pavelkuchin** [comment]
It turned out that one of our clients (one out of 7) uses exchange, and in case of some errors response body might not be used. Can it be that leak in one client affects all others? I'll migrate the client to use `retrieve` and try with the change.

**Comment by violetagg** [comment]
> It turned out that one of our clients (one out of 7) uses exchange, and in case of some errors response body might not be used. Can it be that leak in one client affects all others? I'll migrate the client to use `retrieve` and try with the change.

If you use the default `HttpResources`, this means that all clients share the event loop and connection pool.

**Comment by pavelkuchin** [comment]
Hi Violeta, thank you so much for helping with this. It seems it was related to `exchange` call and responses without valid json so their processing was failing without releasing body. I knew that `exchange` may cause memory leak but our memory metric didn't show any signs of leak and instead we got the stuck active connections which I didn't anticipate. Closing the issue now.

**Comment by pavelkuchin** [comment]
Unfortunately I have to reopen this one, we got the issue back today even although we don't have `exchange` calls anymore.

**Comment by violetagg** [comment]
@pavelkuchin Will you be able to provide some logs?

**Comment by pavelkuchin** [comment]
Sorry @violetagg the only logs we found are above. Is there any way we can enable more logs for this part?
Currently we are using HttpClient.wiretap and logging on DEBUG level for reactor.netty package. I haven't see any connected warnings or errors in logs.

**Comment by pavelkuchin** [comment]
If it helps, the stuck connections seems to be in CLOSE-WAIT state.

**Comment by pavelkuchin** [comment]
@violetagg we were able to localize the issue to one client and when enabled full debug logging it revealed an exception logged on debug level. So far I haven't seen the exception for other clients.
```
2020-12-11 17:36:33,643 [custom-event-loop-epoll-6] [DEBUG] (o.s.h.codec.json.Jackson2JsonDecoder:147) [] - [2bcd04fe] Decoded [ApiClient.ApiResponse(data=[ApiClient.Response(field1=null, tex (truncated)...]
2020-12-11 17:36:33,643 [custom-event-loop-epoll-6] [DEBUG] (reactor.core.publisher.Operators:259) [] - Negative request
java.lang.IllegalArgumentException: Spec. Rule 3.9 - Cannot request a non strictly positive number: -8
	at reactor.core.Exceptions.nullOrNegativeRequestException(Exceptions.java:375)
	at reactor.core.publisher.Operators.reportBadRequest(Operators.java:1057)
	at reactor.core.publisher.Operators.validate(Operators.java:1255)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2095)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.request(FluxConcatMap.java:322)
	at reactor.core.publisher.FluxBufferTimeout$BufferTimeoutSubscriber.requestMore(FluxBufferTimeout.java:317)
	at reactor.core.publisher.FluxBufferTimeout$BufferTimeoutSubscriber.request(FluxBufferTimeout.java:308)
	at reactor.core.publisher.SerializedSubscriber.request(SerializedSubscriber.java:151)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:782)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:909)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:1013)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:252)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:838)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:457)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.checkTerminated(FluxGroupBy.java:419)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drainLoop(FluxGroupBy.java:372)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drain(FluxGroupBy.java:316)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onComplete(FluxGroupBy.java:230)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:701)
	at reactor.core.publisher.FluxZip$ZipInner.onSubscribe(FluxZip.java:884)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
	at reactor.core.publisher.FluxZip$ZipCoordinator.subscribe(FluxZip.java:592)
	at reactor.core.publisher.FluxZip.handleBoth(FluxZip.java:332)
	at reactor.core.publisher.FluxZip.handleArrayMode(FluxZip.java:273)
	at reactor.core.publisher.FluxZip.subscribe(FluxZip.java:137)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8325)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:162)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:173)
	at reactor.core.publisher.MonoMetricsFuseable$MetricsFuseableSubscriber.onNext(MonoMetricsFuseable.java:136)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:385)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:152)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:383)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:373)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:429)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:655)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Can it be cause of stuck connections and if yes than how to avoid it?

**Comment by violetagg** [comment]
@simonbasle @pavelkuchin 

Here
https://github.com/reactor/reactor-netty/blob/3fc0c956bb711af2d8abcf8174a84bba8a22a0fd/src/main/java/reactor/netty/channel/ChannelOperations.java#L429-L432

Reactor Netty first will invoke `onInboundComplete();` in order to notify the subscriber and then will emit `listener.onStateChange(this, ConnectionObserver.State.DISCONNECTING);` in order to return the connection to the pool.

Following the stack trace above, `onInboundComplete();` invokes the code below which notifies the subscriber
https://github.com/reactor/reactor-netty/blob/3fc0c956bb711af2d8abcf8174a84bba8a22a0fd/src/main/java/reactor/netty/channel/FluxReceive.java#L383

So if this call hangs forever than we will leak the connection.

@simonbasle Is it possible this `onComplete` invocation to hang forever when we have the logged exception above in the comment made by @pavelkuchin

**Comment by simonbasle** [comment]
> @simonbasle Is it possible this `onComplete` invocation to hang forever when we have the logged exception above in the comment made by @pavelkuchin

The `Operators.reportBadRequest()` method only _logs_ this exception. But at the same time, if there is no `request` there would be no progress of the `Publisher`, making it hang.

The report seems to be originating from the `onComplete` of a `flatMap`'s inner (+ `concatMap` is involved). If that inner is the one supposedly using the `Connection`, I'd say that bad request is definitely the cause of the stuck connection.

**Comment by pavelkuchin** [comment]
Thanks a lot @violetagg, @simonbasle I think we found what causing it. We are using some library to convert response to internal format, and the library has a bug, for some specific input it falls into infinite loop. Even although we are using retrieve method the infinite loop technically happens on reactor-netty-epoll thread and blocks reactor-netty from closing connection and further execution on the thread. I'll try to find a workaround and verify the theory on prod. If it holds I'll close the issue. Thank you a lot once again!

**Comment by OlegDokuka** [comment]
Hi, @pavelkuchin!


Can you try to build a custom build for reactor-core which should be based on the following repo -> https://github.com/reactor/reactor-core/pull/2219. In this repo, you may find an experimental debug-tool addition that collects `Stats` and provides more insights on what happened within the pipeline. That said if `.timeout` appears in your `WebClient` pipeline, the `StatsCollector` will report all the required info that you can send back to us and have that we can try to do more investigations

Cheers,
Oleh

**Comment by violetagg** [comment]
@pavelkuchin I would also want to ask if you add `HttpClient.responseTimeout` do you still see connections leak?
This will not solve the cause but at least there will be no connections leak.

**Comment by pavelkuchin** [comment]
Wow, thanks @OlegDokuka! I'm not sure it will help in this particular situation but I'll give it a try!

Thanks for the suggestion @violetagg, unfortunately `HttpClient.responseTimeout` doesn't help.

Just to give a little bit more context, It turned out to be an accidental ReDoS. The WebClient is requesting data from ML endpoint and some results are causing regexp parser inside the validation library which is used after `retrieve()` to hangup. This blocks the thread indefinitely without giving webclient/reactor opportunity to close connection. So I'm not sure the exception I've posted before is related to the issue, since once the thread is in the regexp parser it's never back.

**Comment by pavelkuchin** [comment]
Offloading helped to resolve the issue. Thank you @violetagg, @simonbasle, @OlegDokuka!

**Comment by shikharkrdixit** [comment]
Hi @pavelkuchin , We are also facing a similar issue, so can you please expand on what you mean by Offloading in this case and how you resolved this issue?
