### ISSUE TITLE
TransportConnector.connect(…) fails if netty-transport-native-unix-common is not on the class path

### ISSUE THREAD

**Issue by mp911de** [reactor/reactor-netty#1420]
## Expected Behavior

`TransportConnector.connect(…)`  should not fail with `NoClassDefFoundError`

## Actual Behavior

```
		... 76 more
		Suppressed: java.lang.NoClassDefFoundError: io/netty/channel/unix/DomainSocketAddress
			at reactor.netty.transport.TransportConnector.connect(TransportConnector.java:102)
			at reactor.netty.resources.NewConnectionProvider.lambda$acquire$0(NewConnectionProvider.java:74)
			at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
			at reactor.core.publisher.Mono.subscribe(Mono.java:4046)
			at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
			at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
			at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
			at reactor.core.publisher.Operators.error(Operators.java:196)
			at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
			at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
			at reactor.core.publisher.Mono.subscribe(Mono.java:4046)
			at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:103)
			at reactor.core.publisher.Mono.subscribe(Mono.java:4046)
			at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:173)
			at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
			at reactor.core.publisher.Mono.subscribe(Mono.java:4046)
			at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:199)
			at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
			at reactor.core.publisher.Mono.subscribe(Mono.java:4031)
			at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:448)
			at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:218)
			at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
			at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
			at reactor.core.publisher.Flux.subscribe(Flux.java:8147)
			at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:93)
			... 72 more
		Caused by: java.lang.ClassNotFoundException: io.netty.channel.unix.DomainSocketAddress
			at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
			at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
			... 97 more
```

## Steps to Reproduce

Try to establish a connection and exclude `netty-transport-native-unix-common` or `netty-transport-native-epoll` in the project

## Possible Solution

Guard the `instanceof DomainSocketAddress` check against absence of `DomainSocketAddress`.

**Comment by mp911de** [comment]
Yes, I removed it intentionally to actually reduce the dependencies to the least possible amount. To some extent, we also want to guard R2DBC drivers against the absence of native transports and that's where the issue originated.

It would be good to use native transports when these dependencies are on the classpath, but Reactor Netty should not break if these aren't available.

**Comment by violetagg** [comment]
> To some extent, we also want to guard R2DBC drivers against the absence of native transports and that's where the issue originated.

This shouldn't be a problem because we do that for you:
https://github.com/reactor/reactor-netty/blob/29d07fd6dd16be573dcbb3b87c0b993156fb4507/reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNativeDetector.java#L29-L41

https://github.com/reactor/reactor-netty/blob/29d07fd6dd16be573dcbb3b87c0b993156fb4507/reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java#L107

So the only reason for this requirement is to reduce the dependencies.

**Comment by violetagg** [comment]
We cannot work properly without `netty-transport-native-unix-common`

Let say you want to use UDS and `netty-transport-native-unix-common` is missing from the class path, if we do the recommended solution above how we have to react on `instanceof DomainSocketAddress` throwing an exception?
We cannot ignore it because thus UDS will not work. We need somehow to understand the whether the provided `SocketAddress` is `InetSocketAddress` or `DomainSocketAddress`.

Wdyt?

**Comment by mp911de** [comment]
What I'm proposing is making the `instanceof` check conditional based on the presence of `netty-transport-native-unix-common`. If `netty-transport-native-unix-common` is not on the classpath, then the outcome of this check will be always `false`. It would be something like:

```
Class<?> DOMAIN_SOCKET_CLASS = ClassUtils.findClass(DomainSocketAddress).

…

		return doInitAndRegister(config, channelInitializer, DOMAIN_SOCKET_CLASS != null ? DOMAIN_SOCKET_CLASS.isInstance(remoteAddress) : false
				.flatMap(channel -> doResolveAndConnect(channel, config, remoteAddress, resolverGroup));


```

**Comment by violetagg** [comment]
@mp911de In the latest Netty versions, the TLS functionality depends on `netty-transport-native-unix-common` and we cannot make this dependency optional.
https://github.com/netty/netty/blob/b063c211277fcfb4453f24aad3bda8529cf21b8a/handler/pom.xml#L58-L62
