### ISSUE TITLE
Connection prematurely closed BEFORE response - server sent RST

### ISSUE THREAD

**Issue by edgarSang** [reactor/reactor-netty#1498]
Sometimes an "Connection prematurely closed BEFORE response " error occurs.

My reator-netty version is 0.8.16 ~ (I tested it with various versions. In the 0.8.xx version,Since 0.8.16)

And Spring version is 5.1.14
(call API with webclient)

## Expected Behavior
Api call From my server(TOMCAT) to Remote Api Tomcat server. status 200 ok 

## Actual Behavior
When my tomcat server request to API server, Sometimes "Connection prematurely closed BEFORE response " error occurs.

## TCP Dump

```
823081	2021-02-05 12:17:39.262264	[MYIP x.xx.x]	[API IP x.xx]	TCP	bb	aaa → 80 [ACK] Seq=8506 Ack=167062 Win=130752 Len=0 TSval=603031992 TSecr=1349303645
825991	2021-02-05 12:17:44.253855	[MYIP x.xx.x]	[API IP x.xx]	TCP	dd	ccc → 80 [SYN] Seq=0 Win=65535 Len=0 MSS=1460 WS=64 TSval=603036821 TSecr=0 SACK_PERM=1
825992	2021-02-05 12:17:44.253878	[MYIP x.xx.x]	[API IP x.xx]	TCP	hh	zzzzz → 80 [ACK] Seq=2227 Ack=11857 Win=131072 Len=1368 TSval=603036821 TSecr=1349298846 [TCP segment of a reassembled PDU]
825993	2021-02-05 12:17:44.253878	[MYIP x.xx.x]	[API IP x.xx]	TCP	hh	zzzzz → 80 [ACK] Seq=3595 Ack=11857 Win=131072 Len=1368 TSval=603036821 TSecr=1349298846 [TCP segment of a reassembled PDU]
825994	2021-02-05 12:17:44.253879	[MYIP x.xx.x]	[API IP x.xx]	TCP	hh	zzzzz → 80 [ACK] Seq=4963 Ack=11857 Win=131072 Len=1368 TSval=603036821 TSecr=1349298846 [TCP segment of a reassembled PDU]
825995	2021-02-05 12:17:44.253879	[MYIP x.xx.x]	[API IP x.xx]	HTTP/JSON	241	GET /api/v1/mark/marking/markkk/get HTTP/1.1 , JavaScript Object Notation (application/json)
825996	2021-02-05 12:17:44.272226	[API IP x.xx]	[MYIP x.xx.x]	TCP	ff	80 → zzzzz [FIN, ACK] Seq=11857 Ack=2227 Win=32896 Len=0 TSval=1349308846 TSecr=603027119
825997	2021-02-05 12:17:44.272279	[MYIP x.xx.x]	[API IP x.xx]	TCP	ff	zzzzz → 80 [ACK] Seq=6506 Ack=11858 Win=131072 Len=0 TSval=603036839 TSecr=1349308846
825998	2021-02-05 12:17:44.272404	[MYIP x.xx.x]	[API IP x.xx]	TCP	ff	zzzzz → 80 [FIN, ACK] Seq=6506 Ack=11858 Win=131072 Len=0 TSval=603036839 TSecr=1349308846
826000	2021-02-05 12:17:44.289479	[API IP x.xx]	[MYIP x.xx.x]	TCP	ww	80 → a4422 [SYN, ACK] Seq=0 Ack=1 Win=27360 Len=0 MSS=1380 SACK_PERM=1 TSval=1349308674 TSecr=603036821 WS=128
826001	2021-02-05 12:17:44.289524	[MYIP x.xx.x]	[API IP x.xx]	TCP	uu	a4422 → 80 [ACK] Seq=1 Ack=1 Win=131328 Len=0 TSval=603036856 TSecr=1349308674
826002	2021-02-05 12:17:44.289996	[MYIP x.xx.x]	[API IP x.xx]	HTTP/JSON	934	GET /api/v1/mark/marking/markkk/get HTTP/1.1 , JavaScript Object Notation (application/json)
826003	2021-02-05 12:17:44.290454	[API IP x.xx]	[MYIP x.xx.x]	TCP	oo	80 → zzzzz [RST] Seq=11857 Win=0 Len=0
826004	2021-02-05 12:17:44.290547	[API IP x.xx]	[MYIP x.xx.x]	TCP	oo    80 → zzzzz [RST] Seq=11857 Win=0 Len=0
826005	2021-02-05 12:17:44.290776	[API IP x.xx]	[MYIP x.xx.x]	TCP	oo	80 → zzzzz [RST] Seq=11857 Win=0 Len=0
826009	2021-02-05 12:17:44.308049	[API IP x.xx]	[MYIP x.xx.x]	TCP	oo	80 → zzzzz [RST] Seq=11858 Win=0 Len=0
826010	2021-02-05 12:17:44.308328	[API IP x.xx]	[MYIP x.xx.x]	TCP	oo	80 → zzzzz [RST] Seq=11858 Win=0 Len=0
```

**Comment by violetagg** [comment]
@edgarSang Reactor Netty `0.8.23.RELEASE` is the latest release for 0.8.x. Also 0.8x is not supported anymore. Please Upgrade either to the latest 0.9.x release or 1.0.x release.
https://github.com/reactor/reactor-netty/releases

**Comment by vipul-mykaarma** [comment]
we are still facing the same issue in 1.0.3

**Comment by violetagg** [comment]
@vipul-mykaarma Do you have the use case above?

**Comment by edgarSang** [comment]
@violetagg Why did this happen? Just version? Even with a TCP dump I can't understand. Any explanation would be appreciated.

**Comment by vipul-mykaarma** [comment]
@violetagg In our use case the error comes at high load out of 15,000 requests fired in 5 requests we see the error

**Comment by vipul-mykaarma** [comment]
Stack Trace : nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:137)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to POST https://3pa.dmotorworks.com/pip-extract/servicesalespartsopenext/extract [DefaultWebClient]
Stack trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:137)

**Comment by violetagg** [comment]
@vipul-mykaarma Please open a new issue and we will track your use case there

**Comment by violetagg** [comment]
@edgarSang In your tcp dump do you see RST? I asked you to upgrade because we have several fixes related to this exception.

**Comment by edgarSang** [comment]
```
2021-02-05 12:17:43 [reactor-http-nio-3] [INFO ] [com.mycorp.front.log.HttpRequestLog:logRequest:41] - httpRequestLoggingType=REST_TEMPLATE, serviceUrl=http://[apiserver]v1/bbb/www?cd=&id=, host=[apiserver], port=8080, path=/v1/bbb/www, header=[Content-Type:"application/json"], httpMethod=GET, methodName=null, duration=227, remoteIp=127.0.0.1, responseStatusCode=200, , cookieString=null, requestUrl=/www/, screenName=
2021-02-05 12:17:44 [elastic-5] [INFO ] [com.mycorp.front.log.HttpRequestLog:logRequest:41] - httpRequestLoggingType=HTTP_INVOKER, serviceUrl=http://otherohst:19202/remoting/ac/v1, host=otherapi.xxxx.com, port=19102, path=/ooooo/oooooooo/v1, header=null, httpMethod=NONE, methodName=getOther, duration=15, remoteIp=null, responseStatusCode=200, userAgent=null, cookieString=null, requestUrl=null, screenName=null
2021-02-05 12:17:44 [reactor-http-nio-3] [WARN ] [reactor.netty.http.client.HttpClientConnect:warn:299] - [id: 0x1f81d3ea, L:0.0.0.0/0.0.0.0:51648 ! R:[apiserver]v1/bbb/www:80] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
2021-02-05 12:17:44 [reactor-http-nio-3] [ERROR] [com.mycorp.front.apps.rest.AbstractLspWebClient:lambda$getBack$4:44] - Message: Connection prematurely closed BEFORE response, URL: [apiserver]v1/bbb/www/getother
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
2021-02-05 12:17:44 [elastic-4] [INFO ] [com.mycorp.front.log.HttpRequestLog:logRequest:41] - httpRequestLoggingType=HTTP_INVOKER, serviceUrl=other, host=otther.server, port=19102, path=/remoting/AccumulationPolicy/v1, header=null, httpMethod=NONE, methodName=getUnitPolicies, duration=9, remoteIp=null, responseStatusCode=200, userAgent=null, cookieString=null, requestUrl=null, screenName=null
2021-02-05 12:17:44 [reactor-http-nio-6] [INFO ] [com.mycorp.front.log.HttpRequestLog:logRequest:41] - httpRequestLoggingType=REST_TEMPLATE, serviceUrl=[apiserver]v1/bbb/www/getother, host=[apiserver], port=-1, path=v1/bbb/www/getother, header=[X-:"Sys", X:"front", X-LSP-AREA:"front", Content-Type:"application/json"], httpMethod=GET, methodName=null, duration=83, remoteIp=null, responseStatusCode=200, 
```


```
	@Bean
	public TcpClient tcpClient() {
		TcpClient tcpClient = TcpClient
			.create()
			.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 2000)
			.doOnConnected(connection -> {
				connection.addHandlerLast(new ReadTimeoutHandler(2000, TimeUnit.MILLISECONDS));
				connection.addHandlerLast(new WriteTimeoutHandler(2000, TimeUnit.MILLISECONDS));
			});
		return tcpClient;
	}
```

This is My error log and TCP client setting in my front tomcat server.

**Comment by violetagg** [comment]
@edgarSang I meant whether you have some logs on the target server -> `[id: 0x1f81d3ea, L:0.0.0.0/0.0.0.0:51648 ! R:[apiserver]v1/bbb/www:80]`. So that we can understand why the target server closes the connection (as it is in the tcp dump, the RST is sent by the target server)

**Comment by violetagg** [comment]
@edgarSang Were you able to check the target server?

**Comment by edgarSang** [comment]
@violetagg I have to talk to someone from another company. mmm

**Comment by violetagg** [comment]
@edgarSang I'm closing this. When you have more information we can reopen it.
