### ISSUE TITLE
connection closed after request is handled

### ISSUE THREAD

**Issue by zhchen-zhchen** [reactor/reactor-netty#1499]
## Actual Behavior

I am adding the connection provider to configure `maxIdleTime` and `maxLifeTime`. I expected to see some trace logs about the connections that would be terminated after the threshold I set. But during the debugging, it seems the connection is disconnected after getting the response from the remote peer.

## Steps to Reproduce

```kotlin
@Bean
    fun connectionProvider(property: ConnectionProperty): ConnectionProvider =
        ConnectionProvider.elastic(
            "myConnectionProvider",
            property.maxIdleTime, // Duration.ofMillis(5000)
            property.maxLifeTime, // Duration.ofMillis(10000)
        )

private fun getConfiguredHttpClientConnector(
        property: ConnectionProperty,
        connectionProvider: ConnectionProvider
    ): ReactorClientHttpConnector {
        val httpClient = HttpClient
            .create(connectionProvider)
            .tcpConfiguration { tcpClient: TcpClient ->
                tcpClient
                    .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, property.connectTimeoutMillis)
                    .doOnConnected { conn: Connection ->
                        conn.addHandlerLast(ReadTimeoutHandler(property.readTimeout, TimeUnit.MILLISECONDS))
                        conn.addHandlerLast(WriteTimeoutHandler(property.writeTimeout, TimeUnit.MILLISECONDS))
                    }
            }
        return ReactorClientHttpConnector(httpClient)
    }

@Bean
    fun myWebClient(connectionProvider: ConnectionProvider) = WebClient.builder()
        .baseUrl("myApi.com/graphql")
        .clientConnector(getConfiguredHttpClientConnector(property, connectionProvider))
        .build()
```

## Trace Log
```
time:2021-02-08T12:01:51.688+09:00	level:DEBUG	thread:reactor-http-nio-3	logger:reactor.netty.resources.PooledConnectionProvider	message:Creating a new elastic client pool with name [myConnectionProvider] and max connections [-1] for [myApi.com:80]
time:2021-02-08T12:01:51.7+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487] Created a new pooled channel, now 1 active connections and 0 inactive connections
time:2021-02-08T12:01:51.702+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.channel.BootstrapHandlers	message:[id: 0x81972487] Initialized pipeline DefaultChannelPipeline{(BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
time:2021-02-08T12:01:51.731+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Registering pool release on close event for channel
time:2021-02-08T12:01:51.731+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Channel connected, now 1 active connections and 0 inactive connections
time:2021-02-08T12:01:51.731+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] onStateChange(PooledConnection{channel=[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80]}, [connected])
time:2021-02-08T12:01:51.733+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80]}}, [configured])
time:2021-02-08T12:01:51.738+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.ReactorNetty	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Added decoder [ReadTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.httpCodec, ReadTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
time:2021-02-08T12:01:51.738+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.ReactorNetty	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Added decoder [WriteTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.httpCodec, ReadTimeoutHandler, WriteTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
time:2021-02-08T12:01:51.739+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.http.client.HttpClientConnect	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Handler is being applied: {uri=http://myApi.com/graphql, method=POST}
time:2021-02-08T12:01:51.744+09:00	level:TRACE	thread:reactor-http-nio-4	logger:org.springframework.core.codec.CharSequenceEncoder	message:[74a46ab] Writing "***"
time:2021-02-08T12:01:51.76+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] onStateChange(POST{uri=/graphql, connection=PooledConnection{channel=[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80]}}, [request_sent])
time:2021-02-08T12:01:51.829+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.http.client.HttpClientOperations	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Received response (auto-read:false) : [Content-Length=591, Content-Type=application/json;charset=UTF-8, Date=Mon, 08 Feb 2021 03:01:51 GMT, Vary=Origin, Vary=Access-Control-Request-Method, Vary=Access-Control-Request-Headers, X-Vcap-Request-Id=6764d256-88f6-4376-4a84-2c660f089f4e]
time:2021-02-08T12:01:51.829+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] onStateChange(POST{uri=/graphql, connection=PooledConnection{channel=[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80]}}, [response_received])
time:2021-02-08T12:01:51.831+09:00	level:TRACE	thread:reactor-http-nio-4	logger:org.springframework.web.reactive.function.client.ExchangeFunctions	message:[74a46ab] Response 200 OK, headers={masked}
time:2021-02-08T12:01:51.91+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.channel.FluxReceive	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
time:2021-02-08T12:01:51.91+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.http.client.HttpClientOperations	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Received last HTTP packet
time:2021-02-08T12:01:51.91+09:00	level:TRACE	thread:reactor-http-nio-4	logger:reactor.netty.channel.ChannelOperations	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Disposing ChannelOperation from a channel	throwable:java.lang.Exception: ChannelOperation terminal stack\n  at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:404)\n  at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:572)\n  at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)\n  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)\n  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)\n  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)\n  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)\n  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)\n  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)\n  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n  at java.lang.Thread.run(Thread.java:748)
time:2021-02-08T12:01:51.912+09:00	level:TRACE	thread:reactor-http-nio-4	logger:org.springframework.http.codec.json.Jackson2JsonDecoder	message:[74a46ab] Decoded [GraphQLResponse(***), errors=null)]
time:2021-02-08T12:01:51.913+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:org.springframework.web.reactive.function.client.ExchangeFunctions	message:[74a46ab] Cancel signal (to close connection)
time:2021-02-08T12:01:51.956+09:00	level:TRACE	thread:reactor-http-nio-4	logger:org.springframework.http.codec.json.Jackson2JsonEncoder	message:[c089c436] Encoding [AlertSuccessResponse(success=SuccessModel(***))]
time:2021-02-08T12:01:51.967+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.ReactorNetty	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Removed handler: ReadTimeoutHandler, pipeline: DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
time:2021-02-08T12:01:51.968+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.ReactorNetty	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Removed handler: WriteTimeoutHandler, pipeline: DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
time:2021-02-08T12:01:51.968+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] onStateChange(POST{uri=/graphql, connection=PooledConnection{channel=[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80]}}, [disconnecting])
time:2021-02-08T12:01:51.968+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Releasing channel
time:2021-02-08T12:01:51.969+09:00	level:DEBUG	thread:reactor-http-nio-3	logger:reactor.netty.http.server.HttpServerOperations	message:[id: 0xc089c436, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:59710] Decreasing pending responses, now 0
time:2021-02-08T12:01:51.97+09:00	level:DEBUG	thread:reactor-http-nio-4	logger:reactor.netty.resources.PooledConnectionProvider	message:[id: 0x81972487, L:/10.10.149.169:59711 - R:myApi.com/100.69.241.11:80] Channel cleaned, now 0 active connections and 1 inactive connections
time:2021-02-08T12:01:51.999+09:00	level:TRACE	thread:reactor-http-nio-3	logger:org.springframework.web.server.adapter.HttpWebHandlerAdapter	message:[c089c436] Completed 202 ACCEPTED, headers={masked}
time:2021-02-08T12:01:51.999+09:00	level:TRACE	thread:reactor-http-nio-3	logger:org.springframework.http.server.reactive.ReactorHttpHandlerAdapter	message:[c089c436] Handling completed
time:2021-02-08T12:01:52+09:00	level:DEBUG	thread:reactor-http-nio-3	logger:reactor.netty.http.server.HttpServerOperations	message:[id: 0xc089c436, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:59710] Last HTTP response frame
time:2021-02-08T12:01:52+09:00	level:DEBUG	thread:reactor-http-nio-3	logger:reactor.netty.http.server.HttpServerOperations	message:[id: 0xc089c436, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:59710] Last HTTP packet was sent, terminating the channel
time:2021-02-08T12:01:52+09:00	level:TRACE	thread:reactor-http-nio-3	logger:reactor.netty.channel.ChannelOperations	message:[id: 0xc089c436, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:59710] Disposing ChannelOperation from a channel	throwable:java.lang.Exception: ChannelOperation terminal stack\n  at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:404)\n  at reactor.netty.http.server.HttpServerOperations.cleanHandlerTerminate(HttpServerOperations.java:556)\n  at reactor.netty.http.server.HttpTrafficHandler.operationComplete(HttpTrafficHandler.java:380)\n  at reactor.netty.http.server.HttpTrafficHandler.operationComplete(HttpTrafficHandler.java:60)\n  at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)\n  at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)\n  at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)\n  at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)\n  at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)\n  at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)\n  at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)\n  at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)\n  at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:717)\n  at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:272)\n  at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352)\n  at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:414)\n  at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)\n  at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)\n  at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)\n  at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)\n  at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726)\n  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531)\n  at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)\n  at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)\n  at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726)\n  at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)\n  at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)\n  at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1089)\n  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)\n  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)\n  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n  at java.lang.Thread.run(Thread.java:748)

```

## TCP Dump

```
first request:
13:33:12.365852 IP 10.10.149.169.60993 > myApi.vip.http: Flags [S], seq 3777156401, win 65535, options [mss 1240,nop,wscale 6,nop,nop,TS val 1392690282 ecr 0,sackOK,eol], length 0
13:33:12.376058 IP myApi.vip.http > 10.10.149.169.60993: Flags [S.], seq 3298491094, ack 3777156402, win 8190, options [mss 1220], length 0
13:33:12.376128 IP 10.10.149.169.60993 > myApi.vip.http: Flags [.], ack 3298491095, win 65535, length 0
13:33:12.378745 IP 10.10.149.169.60993 > myApi.vip.http: Flags [.], seq 3777156402:3777157622, ack 3298491095, win 65535, length 1220: HTTP: POST /graphql HTTP/1.1
13:33:12.378753 IP 10.10.149.169.60993 > myApi.vip.http: Flags [P.], seq 3777157622:3777157987, ack 3298491095, win 65535, length 365: HTTP
13:33:12.391833 IP myApi.vip.http > 10.10.149.169.60993: Flags [.], ack 3777157987, win 8190, length 0
13:33:12.405582 IP myApi.vip.http > 10.10.149.169.60993: Flags [P.], seq 3298491095:3298492166, ack 3777157987, win 8190, length 1071: HTTP: HTTP/1.1 200 OK
13:33:12.405632 IP 10.10.149.169.60993 > myApi.vip.http: Flags [.], ack 3298492166, win 65535, length 0



second request:
13:34:03.694053 IP 10.10.149.169.60993 > myApi.vip.http: Flags [F.], seq 3777157987, ack 3298492166, win 65535, length 0
13:34:03.700023 IP 10.10.149.169.61005 > myApi.vip.http: Flags [S], seq 2311650907, win 65535, options [mss 1240,nop,wscale 6,nop,nop,TS val 1392741190 ecr 0,sackOK,eol], length 0
13:34:03.708914 IP myApi.vip.http > 10.10.149.169.60993: Flags [F.], seq 3298492166, ack 3777157988, win 8190, length 0
13:34:03.708973 IP 10.10.149.169.60993 > myApi.vip.http: Flags [.], ack 3298492167, win 65535, length 0
13:34:03.711904 IP myApi.vip.http > 10.10.149.169.61005: Flags [S.], seq 1507816887, ack 2311650908, win 8190, options [mss 1220], length 0
13:34:03.711983 IP 10.10.149.169.61005 > myApi.vip.http: Flags [.], ack 1507816888, win 65535, length 0
13:34:03.713952 IP 10.10.149.169.61005 > myApi.vip.http: Flags [.], seq 2311650908:2311652128, ack 1507816888, win 65535, length 1220: HTTP: POST /graphql HTTP/1.1
13:34:03.713957 IP 10.10.149.169.61005 > myApi.vip.http: Flags [P.], seq 2311652128:2311652493, ack 1507816888, win 65535, length 365: HTTP
13:34:03.725143 IP myApi.vip.http > 10.10.149.169.61005: Flags [.], ack 2311652128, win 8190, length 0
13:34:03.725174 IP myApi.vip.http > 10.10.149.169.61005: Flags [.], ack 2311652493, win 8190, length 0
13:34:03.736561 IP myApi.vip.http > 10.10.149.169.61005: Flags [P.], seq 1507816888:1507817959, ack 2311652493, win 8190, length 1071: HTTP: HTTP/1.1 200 OK
13:34:03.736601 IP 10.10.149.169.61005 > myApi.vip.http: Flags [.], ack 1507817959, win 65535, length 0
```

From the above trace log, it seems that the connection is being disconnected after  state `response_received`. 
Does that mean that the connection wont be back to the connection pool for resue? May I ask if there is anything wrong with my configuration?

## Your Environment

* Reactor version(s) used: `reactor-netty-0.9.4.RELEASE`, `io.netty:netty-codec:4.1.46.Final`
* Other relevant libraries versions (eg. `netty`, ...):  `spring-webflux-5.2.3.RELEASE` `Spring-boot 2.2.4.RELEASE`
* JVM version (`java -version`): `1.8.0_222`
* OS and version (eg. `uname -a`): `Darwin myMac 19.6.0 Darwin Kernel Version 19.6.0`

**Comment by violetagg** [comment]
@zhchen-zhchen I do not see anything wrong with the logs. I see the connection is returned to the pool and is in inactive state.
`Channel cleaned, now 0 active connections and 1 inactive connections`

`maxIdleTime` property will be checked when Reactor Netty acquires a connection from the pool. If this timeout is reached we will close the connection.
`maxLifeTime` property will be checked on release to pool/acquire. If this timeout is reached we will close the connection.

With Reactor Netty version `0.9.13.RELEASE` and above, we exposed and API for enabling the connection pool background eviction. so that these properties will be check by a background process, if you configure it.

**Comment by zhchen-zhchen** [comment]
@violetagg Thanks for the prompt reply.

Does the connection seem to be closed when I request again (with flag `F`)? 
```
13:34:03.694053 IP 10.10.149.169.60993 > myApi.vip.http: Flags [F.], seq 3777157987, ack 3298492166, win 65535, length 0
13:34:03.700023 IP 10.10.149.169.61005 > myApi.vip.http: Flags [S], seq 2311650907, win 65535, options [mss 1240,nop,wscale 6,nop,nop,TS val 1392741190 ecr 0,sackOK,eol], length 0
13:34:03.708914 IP myApi.vip.http > 10.10.149.169.60993: Flags [F.], seq 3298492166, ack 3777157988, win 8190, length 0
...
```

When I change Provider from `elastic` to `fixed` with `1` connection, those `Flags [F.],` disappeared and seems the connection is reused.

**Comment by violetagg** [comment]
@zhchen-zhchen Yes that's correct.
When you use `elastic` the pool does not wait for a free connection, if there aren't free connections in the pool, but creates immediately a connection. This means that it may happen that we will have a lot of idle connections if at some point the demand for connections drops.
With `fixed` with `1` the pool will always wait for a free connection so the connection will no reach `maxIdleTime` except you really stopped requesting, this is not the case for `maxLifeTime` though.

**Comment by zhchen-zhchen** [comment]
@violetagg 
Thanks very much for the explanations. Please allow me to ask few questions

I tried under the `elastic` configuration.

When I continuously sent multiple requests (3-5), I found they use the same connection (I didn't see the `F`flag from TCP dump)

If I made the request and tried to make the request again after a few seconds.

The TCP dump of the second request shows `F` flag.

> If there aren't free connections in the pool, but creates immediately a connection. 

If that is the case, the second request should use the first connection? since the first request is handled and the connection is back to pool

and the idleTime I set is `Duration.ofMillis(5000)` it should be still valid.

**Comment by violetagg** [comment]
@zhchen-zhchen Let's discuss your questions on [Gitter](https://gitter.im/reactor/reactor-netty). Wdyt?

**Comment by zhchen-zhchen** [comment]
@violetagg Thanks

**Comment by zhchen-zhchen** [comment]
@violetagg sorry for the mistake. let me close this issus.
