### ISSUE TITLE
AbortedException: Connection has been closed BEFORE send operation

### ISSUE THREAD

**Issue by manzhizhen** [reactor/reactor-netty#1540]
The current situation is that I use spring cloud gateway (2.1.2. Release) as the gateway, and then replace the version of reactor netty (changed to 0.8.23. Release) and reactor core (changed to 3.2.22. Release). I find that when the gateway is called upstream, there are some exceptions as follows:

```
reactor.netty.channel.AbortedException: Connection has been closed BEFORE send operation
        at reactor.netty.channel.AbortedException.beforeSend(AbortedException.java:60) ~[reactor-netty-0.8.23.RELEASE.jar!/:0.8.23.RELEASE]
        at reactor.netty.http.HttpOperations.then(HttpOperations.java:165) ~[reactor-netty-0.8.23.RELEASE.jar!/:0.8.23.RELEASE]
        at reactor.netty.ReactorNetty$OutboundThen.<init>(ReactorNetty.java:516) ~[reactor-netty-0.8.23.RELEASE.jar!/:0.8.23.RELEASE]
        at reactor.netty.ReactorNetty$OutboundThen.<init>(ReactorNetty.java:509) ~[reactor-netty-0.8.23.RELEASE.jar!/:0.8.23.RELEASE]
        at reactor.netty.NettyOutbound.then(NettyOutbound.java:336) ~[reactor-netty-0.8.23.RELEASE.jar!/:0.8.23.RELEASE]
        at reactor.netty.http.HttpOperations.send(HttpOperations.java:103) ~[reactor-netty-0.8.23.RELEASE.jar!/:0.8.23.RELEASE]
        at org.springframework.http.server.reactive.ReactorServerHttpResponse.writeWithInternal(ReactorServerHttpResponse.java:86) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.http.server.reactive.AbstractServerHttpResponse.lambda$null$2(AbstractServerHttpResponse.java:187) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_232]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_232]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_232]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_232]
        at org.springframework.http.server.reactive.AbstractServerHttpResponse.doCommit(AbstractServerHttpResponse.java:240) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.http.server.reactive.AbstractServerHttpResponse.lambda$writeWith$3(AbstractServerHttpResponse.java:187) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.http.server.reactive.ChannelSendOperator$WriteBarrier.onNext(ChannelSendOperator.java:184) [spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96) [spring-cloud-sleuth-core-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2205) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.request(FluxContextStart.java:132) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:79) [spring-cloud-sleuth-core-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.http.server.reactive.ChannelSendOperator$WriteBarrier.onSubscribe(ChannelSendOperator.java:166) [spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71) [spring-cloud-sleuth-core-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onSubscribe(FluxContextStart.java:97) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:63) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoSubscriberContext.subscribe(MonoSubscriberContext.java:47) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.FluxSourceMonoFuseable.subscribe(FluxSourceMonoFuseable.java:39) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.FluxLiftFuseable.subscribe(FluxLiftFuseable.java:78) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at org.springframework.http.server.reactive.ChannelSendOperator.subscribe(ChannelSendOperator.java:77) [spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:71) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.ignoreDone(MonoIgnoreThen.java:190) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onComplete(MonoIgnoreThen.java:240) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112) [spring-cloud-sleuth-core-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:141) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96) [spring-cloud-sleuth-core-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96) [spring-cloud-sleuth-core-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1643) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112) [spring-cloud-sleuth-core-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144) [reactor-core-3.2.22.RELEASE.jar!/:3.2.22.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112) [spring-cloud-sleuth-core-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
```

## Expected Behavior
Gateway normal response upstream

## Actual Behavior
The upstream call gateway timed out

**Comment by violetagg** [comment]
@manzhizhen If I understand the issue correctly, we have

```
client -> SCG -> target server
       ^
       Here when SCG tries to return a response, it appears that the client already closed the connection. Is that the correct scenario?
```

If the answer is yes then do you have SCG `spring.cloud.gateway.httpclient.response-timeout` configuration? https://cloud.spring.io/spring-cloud-gateway/reference/html/appendix.html

**Comment by manzhizhen** [comment]
> @manzhizhen If I understand the issue correctly, we have
> 
> ```
> client -> SCG -> target server
>        ^
>        Here when SCG tries to return a response, it appears that the client already closed the connection. Is that the correct scenario?
> ```
> 
> If the answer is yes then do you have SCG `spring.cloud.gateway.httpclient.response-timeout` configuration? https://cloud.spring.io/spring-cloud-gateway/reference/html/appendix.html

yes, you got it!!

**Comment by violetagg** [comment]
I'm not familiar with the differences between SCG versions, but in the latest documentation it is `response-timeout` while your configuration contains `responseTimeout`

**Comment by manzhizhen** [comment]
> I'm not familiar with the differences between SCG versions, but in the latest documentation it is `response-timeout` while your configuration contains `responseTimeout`

I've really tried this one. It can take effect. Ha ha

**Comment by manzhizhen** [comment]
I have tried to upgrade reactor-netty and reactor-core to a higher version, but it seems to be incompatible with the existing SCG or Spring Webflux (Spring Web, which Spring Webflux relies on, also relies on reactor-core)

**Comment by violetagg** [comment]
You need to check which Spring Boot version is supported by a concrete SCG version.
Spring Boot 2.4.x uses Reactor 2020.0.x (Reactor Netty 1.0.x)
Spring Boot 2.3.x and 2.2.x use Reactor Dysprosium (Reactor Netty 0.9.x)
Spring Boot 2.1.x uses Reactor Californium (Reactor Netty 0.8.x)

**Comment by violetagg** [comment]
@manzhizhen I'm closing this one. For issues with SCG upgrade please consider contacting SCG maintainers.
