### ISSUE TITLE
 io.netty.channel.ConnectTimeoutException: connection timed out: AbstractEpollChannel.java:576

### ISSUE THREAD

**Issue by paramthind** [reactor/reactor-netty#1574]
My proxy service is throwing this error intermitently: 

500 Server Error for HTTP POST "/jupyter/228fff57-1489-42ae-9c84-38e3c0fdcad9/git/branch?1616124558197" io.netty.channel.ConnectTimeoutException: connection timed out: <SOME_HOST>:443
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:576)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ com.jpmchase.omniai.ui.filter.OmniaiUiFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ com.jpmchase.omniai.ui.filter.DefaultHomePageFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/jupyter/228fff57-1489-42ae-9c84-38e3c0fdcad9/git/branch?1616124558197" [ExceptionHandlingWebHandler]
Stack trace:
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:576)
		at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
		at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)

Description :
Server is using Springboot:  '2.3.7.RELEASE' and springCloud: 'Hoxton.SR9'
     
We have this server doing WebSocket proxy to EC2 instance which is running JupyterNotebook. By nature, app consumers stay active on the same browser tab for a long period of time(more than 4 hours). 

I checked the source code and looks like there is a default 30 sec connection timeout which is not configurable. Can somebody help me with any solution to this problem?

**Comment by violetagg** [comment]
@paramthind Can you try with SCG property `spring.cloud.gateway.httpclient.connect-timeout`?
https://cloud.spring.io/spring-cloud-gateway/reference/html/appendix.html

`spring.cloud.gateway.httpclient.connect-timeout - The connect timeout in millis, the default is 45s.`

**Comment by violetagg** [comment]
@paramthind Were you able to try SCG property for connect timeout?

**Comment by paramthind** [comment]
that worked. Thank you!
