### ISSUE TITLE
NettyState dispose deadlock

### ISSUE THREAD

**Issue by jvalkeal** [reactor/reactor-netty#16]
`dispose()` call never return as shown with simple test:
```
	@Test
	public void testHang() throws Exception {
		NettyState httpServer = HttpServer
				.create(ServerOptions.on("0.0.0.0", 0)
						.eventLoopGroup(new NioEventLoopGroup(10)))
				.newRouter(r -> r.get("/data", (request, response) -> {
					return response.send(Mono.empty());
				})).block();
		httpServer.dispose();
	}
```
From stack dump:
```
"nioEventLoopGroup-2-1" #23 prio=10 os_prio=0 tid=0x00007fb8f0a36800 nid=0x7441 in Object.wait() [0x00007fb8cf2e1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000672ef4af8> (a io.netty.util.concurrent.DefaultPromise)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:239)
	- locked <0x0000000672ef4af8> (a io.netty.util.concurrent.DefaultPromise)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:340)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:34)
	at reactor.ipc.netty.tcp.TcpServer.lambda$channel$1(TcpServer.java:313)
	at reactor.ipc.netty.tcp.TcpServer$$Lambda$11/84739718.dispose(Unknown Source)
	at reactor.ipc.netty.channel.ChannelConnectHandler.lambda$operationComplete$0(ChannelConnectHandler.java:54)
	at reactor.ipc.netty.channel.ChannelConnectHandler$$Lambda$14/870848850.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1062)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:686)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:664)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:634)
	at io.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:623)
	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)


"main" #1 prio=5 os_prio=0 tid=0x00007fb8f000e800 nid=0x741f in Object.wait() [0x00007fb8f8d22000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000677aae4e0> (a io.netty.channel.DefaultChannelPromise)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:239)
	- locked <0x0000000677aae4e0> (a io.netty.channel.DefaultChannelPromise)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:340)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:117)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:28)
	at reactor.ipc.netty.channel.ChannelConnectHandler.dispose(ChannelConnectHandler.java:77)
	at reactor.ipc.netty.channel.ChannelState.dispose(ChannelState.java:69)
	at org.springframework.cloud.stream.app.gpfdist.sink.FooTests.testHang(FooTests.java:40)

```

**Comment by smaldini** [comment]
Test now runs fine:

```
	@Test
	public void testHang() throws Exception {
		NettyContext httpServer = HttpServer
				.create(opts -> opts.listen("0.0.0.0", 0)
				                     .eventLoopGroup(new NioEventLoopGroup(10)))
				.newRouter(r -> r.get("/data", (request, response) -> {
					return response.send(Mono.empty());
				})).block();
		httpServer.dispose();
	}
```
