### ISSUE TITLE
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms

### ISSUE THREAD

**Issue by uvarajk** [reactor/reactor-netty#1617]
Versions : 
Reactor Netty : reactor-netty-http-1.0.5.jar, Java : 11.0.8 (N/A) , Linux : 4.15.0-133-generic

We're receiving the SSL Handshake Timout Exception in our production environment.

Captured few details for the reference those are mentioned below :

In the Debug Log below are the default connection pool configurations
r.n.resources.PooledConnectionProvider : Creating a new [http] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=1000, pendingAcquireTimeout=45000}] for [/172.25.0.12:443]

We are able to see that the application is working fine for some time(4 to 5 hours) and slowly the responses are received late
Taken <<24442>> milliseconds to retrieve data from endpoint
Taken <<32875>> milliseconds to retrieve data from endpoint
Taken <<2532046>> milliseconds to retrieve data from endpoint

During the delayed responses following are the errors/exceptions
io.netty.handler.timeout.ReadTimeoutException: null
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms

We have configured the following timeout's for the HTTPClient
web-client.connect-timeout=5
web-client.read-timeout=5
web-client.use-connection-pooling=true
reactor.netty.ioWorkerCount=128
web-client.response-timeout=5

It would be a great help if we could know what's going wrong.

**Comment by uvarajk** [comment]
@violetagg for your question https://github.com/reactor/reactor-netty/issues/907#issuecomment-829042391

The below code provide the preperties 
HttpClient.create()
                    .wiretap("reactor.netty.http.client.HttpClient", logLevel, AdvancedByteBufFormat.TEXTUAL)
                    .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectionTimeout)
                    .responseTimeout(responseTimeout)
                    .doOnConnected(connection -> connection.addHandlerLast(new ReadTimeoutHandler(readTimeout, TimeUnit.MILLISECONDS)))
                    .followRedirect(true);

**Comment by violetagg** [comment]
@uvarajk What's the idea of having `ReadTimeoutHandler`?
You have SSL handshake timeout and also response timeout.
Having `ReadTimeoutHandler` may interfere with SSL handshake reading.

**Comment by uvarajk** [comment]
We initially included ReadTimeoutHandler to check if it the time taken to read the response. As it did not work we have added ResponseTimeout. 
Yes got Response Timeout and default SSL handshake timeout. Still why the request is waiting too long as I have mentioned the timetaken is milliseconds.

**Comment by violetagg** [comment]
@uvarajk Without knowing the scenario and how the client is used is very hard to say what causes this.

**Comment by uvarajk** [comment]
@violetagg If I can understand you question right, below is my explanation.
the flow is 
Client Request --> Out Microservice Application --> Network Layer(NAT) --> Downstream System (we are using the netty client to establish connection to the downstream system through the NATed IP).
It's purely a Rest Service call using Spring Boot web client.

**Comment by violetagg** [comment]
@uvarajk OK so you are using WebClient. Can you give some coding, how you use it?

**Comment by uvarajk** [comment]
@violetagg please find the attached code for reference and starts with the below get method

public Mono<Object> get(String endpoint, Map<String, String> headers, Class responseClass) 

[WebClientConnector.txt](https://github.com/reactor/reactor-netty/files/6398507/WebClientConnector.txt)

**Comment by violetagg** [comment]
@uvarajk You are creating WebClient always, why don't you share it? Is it possible that you overload the downstream system. Do you use blocking or non-blocking on the downstream system? Did you check the load on the downstream system?

**Comment by uvarajk** [comment]
@violetagg I think spring internally uses singleton for the webclient.

However, the concern is why the timeout's are not considered.

**Comment by violetagg** [comment]
@uvarajk can you add `logging.level.reactor.netty=debug` to application.properties and then provide here logs for some request where the `responseTimeout` is not considered. You can correlated using connection id i.e. `id:68812135-1, L:/0:0:0:0:0:0:0:1:52348 - R:/0:0:0:0:0:0:0:1:52346`

```
18:33:26.906 [reactor-http-nio-3] DEBUG reactor.netty.http.client.HttpClient - [id:68812135-1, L:/0:0:0:0:0:0:0:1:52348 - R:/0:0:0:0:0:0:0:1:52346] WRITE: 145B
```

**Comment by uvarajk** [comment]
@violetagg Please find the attached logs that I have captured enabling the debug mode for netty. 
I could see that one transaction Taken <<83275>> milliseconds to retrieve the data. Provided the Start and End below for reference.
[nettyDebugLogs.txt](https://github.com/reactor/reactor-netty/files/6405808/nettyDebugLogs.txt)

2021-04-30 09:32:18.840 : [id:18009796, L:/10.200.61.65:42856 - R:172.25.0.12/172.25.0.12:443] Registering pool release on close event for channel 
2021-04-30 09:33:40.189 : [id:18009796, L:/10.200.61.65:42856 - R:172.25.0.12/172.25.0.12:443] READ COMPLETE
2021-04-30 09:33:42.737 : [id:18009796, L:/10.200.61.65:42856 ! R:172.25.0.12/172.25.0.12:443] UNREGISTERED

**Comment by uvarajk** [comment]
@violetagg

**Comment by violetagg** [comment]
@uvarajk If you do not increase the I/O workers count `reactor.netty.ioWorkerCount=128`, do you observe issue with the timeout?

**Comment by uvarajk** [comment]
@violetagg Yes we see the issue, the timeout's are not considered even without the ioWorkerCount configuration.

**Comment by violetagg** [comment]
@uvarajk Is it possible that you run blocking/log running operations in the event loop? For blocking operations you can use `BlockHound` in order to detect them.

**Comment by uvarajk** [comment]
@violetagg Thanks, will check on that and implement and will give you the feedback.

**Comment by violetagg** [comment]
> Is it that will work just by adding BlockHound.install(); in the SpringBoot main method.

Yes this should be enough

**Comment by violetagg** [comment]
@uvarajk Were you able to install BlockHound?

**Comment by violetagg** [comment]
@uvarajk Let me close this, if you are able to provide the requested information we can reopen the issue.

**Comment by uvarajk** [comment]
@violetagg please keep it open. I've just got the approval to include the BlockHound

**Comment by violetagg** [comment]
@uvarajk Were you able to install BlockHound?

**Comment by violetagg** [comment]
@uvarajk Let me close this, if you are able to provide the requested information we can reopen the issue.

**Comment by klopfdreh** [comment]
Hey @violetagg,

we are facing the same issue. It seems that sometimes the 10000ms timeout is not taken into account, but sometimes it is. For us this happens when using Spring Boot Native images, but I guess it is a race condition more often occuring at native images:

The reason why I think the timeout is not taken into account is because we have a log message right before using the WebClient to send the request and the timestamps are: 

`{"@timestamp":"2025-07-28T05:48:08.960503Z","log":{"level":"INFO","logger": .....` (before sending the request)
and
`{"@timestamp":"2025-07-28T05:48:08.978950Z","log":{"level":"WARN","logger": .....`(when the issue occurs)

definitely no 10000ms.

Stacktrace
```java
org.springframework.web.reactive.function.client.WebClientRequestException: handshake timed out after 10000ms
at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:137)
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \nError has been observed at the following site(s):
*__checkpoint ⇢ Request to POST https://<endpoint> [DefaultWebClient]\nOriginal Stack Trace:
 at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:137)
 at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
 at reactor.core.publisher.Mono.subscribe(Mono.java:4576)
 at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:205)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
 at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:229)
 at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:279)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.maybeOnError(FluxConcatMapNoPrefetch.java:327)
 at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:212)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:68)
 at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
 at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:476)
 at reactor.core.publisher.SinkManyEmitterProcessor$EmitterInner.drainParent(SinkManyEmitterProcessor.java:620)
 at reactor.core.publisher.FluxPublish$PubSubInner.request(FluxPublish.java:874)
 at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
 at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:337)
 at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
 at reactor.core.publisher.Operators$DeferredSubscription.request(Operators.java:1742)
 at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:196)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:205)
 at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:325)
 at io.opentelemetry.instrumentation.reactor.v3_1.TracingSubscriber.onError(TracingSubscriber.java:85)
 at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:205)
 at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onUncaughtException(DefaultPooledConnectionProvider.java:224)
 at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onUncaughtException(DefaultPooledConnectionProvider.java:478)
 at reactor.netty.channel.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:156)
 at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
 at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
 at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
 at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:424)
 at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
 at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:145)
 at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
 at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:231)
 at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
 at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
 at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
 at reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:726)
 at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:398)
 at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:376)
 at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:368)
 at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:506)
 at io.netty.handler.ssl.SslHandler$8.run(SslHandler.java:2285)
 at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
 at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
 at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
 at java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
 at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:837)
 at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:813)
Suppressed: java.lang.Exception: #block terminated with an error
 at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104)
 at reactor.core.publisher.Mono.block(Mono.java:1779)
 at  batch.basic.tasks.rest.caller.steps.callrest.StepCallRestEndpointTasklet.sendRestCall(StepCallRestEndpointTasklet.java:120)
 at java.base@23.0.1/java.util.ArrayList.forEach(ArrayList.java:1597)
 at  batch.basic.tasks.rest.caller.steps.callrest.StepCallRestEndpointTasklet.execute(StepCallRestEndpointTasklet.java:74)
 at java.base@23.0.1/java.lang.reflect.Method.invoke(Method.java:580)
 at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
 at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
 at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)
 at  batch.basic.tasks.rest.caller.steps.callrest.StepCallRestEndpointTasklet$$SpringCGLIB$$0.execute(<generated>)
 at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:383)
 at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:307)
 at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
 at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:250)
 at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
 at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:369)
 at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:206)
 at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:140)
 at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:235)
 at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:230)
 at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:153)
 at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
 at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
 at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:165)
 at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:140)
 at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:132)
 at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:307)
 at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher$1.run(TaskExecutorJobLauncher.java:155)
 at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
 at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.run(TaskExecutorJobLauncher.java:146)
 at  batch.starter.job.RestartDetectionJobLauncher.run(RestartDetectionJobLauncher.java:73)
 at org.springframework.cloud.task.batch.handler.TaskJobLauncherApplicationRunner.execute(TaskJobLauncherApplicationRunner.java:148)
 at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.executeLocalJobs(JobLauncherApplicationRunner.java:194)
 at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.launchJobFromProperties(JobLauncherApplicationRunner.java:174)
 at org.springframework.cloud.task.batch.handler.TaskJobLauncherApplicationRunner.run(TaskJobLauncherApplicationRunner.java:112)
 at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.run(JobLauncherApplicationRunner.java:164)
 at org.springframework.cloud.task.configuration.observation.ObservationApplicationRunner.run(ObservationApplicationRunner.java:59)
 at org.springframework.boot.SpringApplication.lambda$callRunner$4(SpringApplication.java:784)
 at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:82)
 at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
 at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:86)
 at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:796)
 at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
 at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:772)
 at java.base@23.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
 at java.base@23.0.1/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
 at java.base@23.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:571)
 at java.base@23.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
 at java.base@23.0.1/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
 at java.base@23.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
 at java.base@23.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
 at java.base@23.0.1/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
 at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
 at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:149)
 at  batch.basic.tasks.rest.caller.RestCallerApplication.main(RestCallerApplication.java:24)
 at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)\nCaused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
at io.netty.handler.ssl.SslHandler$8.run(SslHandler.java:2281)
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
at java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:837)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:813)\n
```

Hint: I replaced the endpoint with `<endpoint>`

Versions: Netty 4.1.123 / Spring Boot 3.5.4 / Java: 23.0.1+13 / Liberica-NIK-24.1.1-1 / Netty-Reactor 1.2.8

Would you be so kind and reopen the issue as it still exists?

A problem mitigation for this in our case is to use `@Retryable` and wrap the call in a service method as for the most time it works after some attempts.
```java
    @Retryable(retryFor = {WebClientRequestException.class},
        maxAttemptsExpression = "#{${restCaller.retry.maxAttempts:3}}",
        backoff = @Backoff(
            delayExpression = "#{${restCaller.retry.delay:5000}}"
        )
    )
```

**Comment by violetagg** [comment]
Please open a new issue and if possible attach a reproducible example.
I'm currently on vacation. When I return I'll take a look at it.

На пн, 28.07.2025 г. в 9:08 Tobias Soloschenko ***@***.***>
написа:
