### ISSUE TITLE
Connection prematurely closed BEFORE opening handshake is complete.

### ISSUE THREAD

**Issue by ankit320422** [reactor/reactor-netty#1678]
I have created the client to call another service via websocketClient. the issue i'm facing not able find out root cause.

```
	@Autowired
	RSocketClientBuilder rSocketClientBuilder;

	private RSocketRequester rSocketRequester;

	private RSocketRequester.Builder builder;

	private String serviceName = InternalSdkConfig.Data_Base;

	public AwsWrapperClient(RSocketRequester.Builder builder) {
		this.builder = builder;
	}

	public AmazonEC2ServiceController getController() {
		this.rSocketRequester = builder
				.transport(WebsocketClientTransport.create(URI.create(InternalSdkConfig.HOSTS.get(serviceName))));
		
		return rSocketClientBuilder.buildClientFor(Controller.class, rSocketRequester);
	}
```	
	
---------------------------------------------------------------------------------------------------------------------------------------------

```
io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Invalid handshake response getStatus: 201 Created
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:272) ~[netty-codec-http-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:302) ~[netty-codec-http-4.1.60.Final.jar:4.1.60.Final]
	at reactor.netty.http.client.WebsocketClientOperations.onInboundNext(WebsocketClientOperations.java:119) ~[reactor-netty-http-1.0.5.jar:1.0.5]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) ~[reactor-netty-core-1.0.5.jar:1.0.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1534) ~[netty-handler-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1283) ~[netty-handler-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1330) ~[netty-handler-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar:4.1.60.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar:4.1.60.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.60.Final-linux-x86_64.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-06-17 09:59:49.201  WARN 1 --- [tor-tcp-epoll-2] reactor.netty.channel.FluxReceive        : [id:89189753-1, L:/10.3.114.5:45994 ! R:apistaging.demo.com/13.224.249.2:443] An exception has been observed post termination, use DEBUG level to see the full stack: io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Connection prematurely closed BEFORE opening handshake is complete.
2021-06-17 09:59:49.201  INFO 1 --- [d8e9214ad30-240] reactor.Parallel.Map.3                   : onNext(com.demo.rsocket.core.model.BaseResponse@7532bf5)
2021-06-17 09:59:49.201  INFO 1 --- [d8e9214ad30-240] reactor.Parallel.Map.3                   : onComplete()
2021-06-17 09:59:49.336 DEBUG 1 --- [fbfd77d70d3-141] c.c.r.c.c.config.RSocketClientBuilder    : invoking ec2ReservedInstances accepting 1 argument(s) for route amazonEC2Service/ec2ReservedInstances with destination variables (). The payload is com.demo.rsocket.core.model.awswrapper.ec2.DescribeReservedInstancesCustomRequest@6d3336af
2021-06-17 09:59:49.336 DEBUG 1 --- [fbfd77d70d3-141] c.c.r.c.c.config.RSocketClientBuilder    : request-response
2021-06-17 09:59:49.672  WARN 1 --- [tor-tcp-epoll-2] r.netty.http.client.HttpClientConnect    : [id:d3d410e0-1, L:/10.3.114.5:36520 - R:apistaging.demo.com/13.224.249.23:443] The connection observed an error
```

**Comment by OlegDokuka** [comment]
Hey @ankit320422. 201 status says that your http endpoint just answered with normal http response instead of downgrading request to websocket connection. Can it be that you are connecting to an incorrect http path?

Can you also check that you are capable on opening websocket connection to that endpoint using other utils just to make reduce problem surface.

Thanks

**Comment by violetagg** [comment]
@ankit320422 The remote peer sends status code 201 while we are waiting for 101

```
io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Invalid handshake response getStatus: 201 
```

**Comment by violetagg** [comment]
@ankit320422 I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by OlegDokuka** [comment]
Also. Can you please check that your `URI.create(InternalSdkConfig.HOSTS.get(serviceName)` return string in the following format : `ws` or `wss` `://<host>:<port>/<path>`

**Comment by ankit320422** [comment]
> Also. Can you please check that your `InternalSdkConfig.HOSTS.get(serviceName` returns a string in the following format : `ws` or `wss` `://<host>:<port>/<path>`

it's `wss` `://<host>:<port>/<path>`
also we are trying to attain multiple connection i.e  request per connection.
i have seen your blog for this and resolve it by expanding the size of connection pool.
[RSocket Request Stream hangs when connection per request is used on load test](https://www.gitmemory.com/issue/rsocket/rsocket-java/911/671042382)

**Comment by ankit320422** [comment]
`	@PostConstruct
	private void init() {

		Field[] fields = ApplicationProperties.class.getDeclaredFields();

		for (int i = 0; i < fields.length; i++) {
			if (fields[i].getType().isAssignableFrom(Service.class)) {
				String serviceName = CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_HYPHEN, fields[i].getName());
				if (applicationProperties.isKubernetes()) {
					HOSTS.put(serviceName, "wss://" + applicationProperties.APP_DOMAIN + "/" + serviceName);
				} else if (applicationProperties.isDev()) {
					HOSTS.put(serviceName, "ws://" + "localhost:" + getPostFromService(serviceName) + "/");
				}
			}
		}
	}`

**Comment by OlegDokuka** [comment]
@ankit320422 

Can you please check that you are capable of opening a WebSocket connection to that endpoint using other utils? That is needed just to make reduce the problem surface.

Thanks

**Comment by violetagg** [comment]
@ankit320422 Can you provide the requested information so that we can continue with the investigation?

**Comment by violetagg** [comment]
@ankit320422 Let me close this, if you are able to provide the requested information we can reopen the issue.
