### ISSUE TITLE
Intermittent SslHandshakeTimeoutException and UnresolvedAddressException

### ISSUE THREAD

**Issue by amardeepkhera** [reactor/reactor-netty#1742]
Hello, I am using reactor netty 0.9.15 with Spring Boot 2.2.12.RELEASE. I have configured Webclient as follows to work with a company proxy when connecting to internet
```
HttpClient.create()
            .tcpConfiguration {
                it.proxy { proxy ->
                proxy.type(ProxyProvider.Proxy.HTTP)
                    .address(InetSocketAddress(host, port))
            }.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, webclientTimeout)
                .doOnConnected {
                    it.addHandlerLast(
                        ReadTimeoutHandler(5000,TimeUnit.MILLISECONDS)
                        
                    )
                    it.addHandlerLast(
                       WriteTimeoutHandler(5000,TimeUnit.MILLISECONDS)
                    )
                }
            }
            .metrics(true, Function { it })
```
Also, ```-Dreactor.netty.tcp.sslHandshakeTimeout=2500``` is passed as JVM arg.

Now, there are two intermittent issues I am seeing when Webclient makes a call to a external service via proxy. Both the issues are not happening at the same time and are totally random.
Is there any pointers to say that this is Webclient configuration issue, or is happening due to company proxy misbehaving. Any ideas will be much appreciated.

1) I get following UnresolvedAddressException error(intermittent)
``` 
j.n.c.UnresolvedAddressException: null
 at i.n.c.e.AbstractEpollChannel.checkResolvable(AbstractEpollChannel.java:337)Suppressed: r.c.p.FluxOnAssembly$OnAssemblyException:
 Assembly trace from producer [reactor.core.publisher.MonoLift] :reactor.core.publisher.Mono.create(Mono.java:197)reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator.connectChannel(PooledConnectionProvider.java:239)
 Error has been observed at the following site(s):| Mono.create ⇢
 at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator.connectChannel(PooledConnectionProvider.java:239)| Mono.create ⇢ at reactor.netty.resources.PooledConnectionProvider.acquire(PooledConnectionProvider.java:143)| Mono.create ⇢ at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:292)
```
2) I get following error(intermittent)
```
i.n.h.s.SslHandshakeTimeoutException: handshake timed out after 2500ms
	at i.n.h.s.SslHandler$5.run(SslHandler.java:2069)
	Suppressed: r.c.p.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to POST https://remote.host.com/get/ [DefaultWebClient]
	|_ checkpoint ⇢ Handler xx.com.xx.xx.authorization.web.XX#xX(HttpHeaders, Map) [DispatcherHandler]
Stack trace:
		at i.n.h.s.SslHandler$5.run(SslHandler.java:2069)
		at i.n.u.c.PromiseTask.runTask(PromiseTask.java:98)
		at i.n.u.c.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
		at i.n.u.c.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at i.n.u.c.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
		at i.n.c.e.EpollEventLoop.run(EpollEventLoop.java:384)
		at i.n.u.c.SingleThreadEventExecutor$4.run(...
```
```
i.n.h.p.ProxyConnectException: http, none, proxy.xx.corp/xx.xxx.yyy.zzz:8080 => remote.host.com:443, disconnected
	at i.n.h.p.ProxyHandler.channelInactive(ProxyHandler.java:234)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at i.n.c.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at i.n.c.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
	at i.n.h.c.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at i.n.h.c.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at i.n.h.c.h.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:311)
	at i.n.c.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
	at i.n.h.p.HttpProxyHandler$HttpClientCodecWrapper.cha...
```

**Comment by violetagg** [comment]
@amardeepkhera

If those exceptions happens from time to time for one and the same coding then try to obtain a tcp dump (you may use Wireshark or something else) in order to check how your network is behaving ...

Let's continue this on [Gitter](https://gitter.im/reactor/reactor-netty) and if we find that the issue is in Reactor Netty we can reopen this one.
