### ISSUE TITLE
Client channel Initialised twice when Server does not exists

### ISSUE THREAD

**Issue by AmandeepSingh97** [reactor/reactor-netty#1759]
We have a test case which intialises a reactor netty client and tries to hit a server which does not exists
It's default expected behaviour is to have exception connection refused and not retry initialising the channel
Reactor netty client sometimes tries to re-initialise the channel.

## Expected Behavior
If server is not reachable (does not exists) client should not retry the channel initialisation

## Actual Behavior
Channel gets initialised twice (Flaky behaviour)

## Steps to Reproduce

```java
  @Test
  public void testNumberOfChannelsInitialised() {
      AtomicInteger counter = new AtomicInteger();
      HttpClient.create()
              .doOnChannelInit((observer, channel, address) -> {
                  counter.getAndIncrement();
              })
              .get()
              .uri("http://localhost:" + 12345)
              .responseSingle((resp, bytes) -> bytes.asString())
              .as(StepVerifier::create)
              .verifyErrorSatisfies(throwable -> {
                  assertThat(throwable, instanceOf(ConnectException.class));
                  assertThat(
                          throwable.getMessage(),
                          containsStringIgnoringCase("Connection refused")
                  );
              });

      Assert.assertEquals(counter.get(), 1);
  }
```

## Your Environment

Running tests on CI instance:
"cpu": 0.15,
"ram": 4096,
"disk": 2048,

* Reactor netty version(s) used: 1.0.8. (This is not observed in 1.0.7)
* Other relevant libraries versions (eg. `netty`, ...): netty 4.1.65.FINAL
* JVM version (`java -version`): zulu_8_212
* OS and version (eg. `uname -a`): OS name: "linux", version: "4.15.0-1091-gcp", arch: "amd64", family: "unix"

**Comment by violetagg** [comment]
@AmandeepSingh97 Is it possible that in your `/etc/hosts` file you have more than one entry for the `localhost`?
How many logs like the one below do you see? Is the `localhost` always resolved to `127.0.0.1`?

```
20:28:47.902 [reactor-http-nio-2] DEBUG r.netty.transport.TransportConnector - [id:f2dba4b7] Connecting to [localhost/127.0.0.1:12345].
20:28:48.911 [reactor-http-nio-2] DEBUG r.netty.transport.TransportConnector - [id:f2dba4b7] Connect attempt to [localhost/127.0.0.1:12345] failed.
```

Reactor Netty 1.0.7 runs with Netty 4.1.63.Final while Reactor Netty 1.0.8 runs with Netty 4.1.65.Final. In Netty 4.1.65.Final we have a fix for this issue #1405

**Comment by AmandeepSingh97** [comment]
Thanks for sharing @violetagg
I still have a small clarification 
If we have multiple entries for the localhost in /etc/hosts file, all of which resolve to the same host (127.0.0.1) is the retry still an expected behaviour ?

**Comment by violetagg** [comment]
@AmandeepSingh97 It is not related to the entries in `/etc/hosts` that will be resolved to `127.0.0.1`. It is the opposite whether you have many entries for `localhost`. In the mentioned issue there are two entries for `localhost` - the first `127.0.1.1` and the second `127.0.0.1`. If you are in the latter use case we will try with both `127.0.1.1` and `127.0.0.1`.

**Comment by AmandeepSingh97** [comment]
@violetagg 
We have a situation in which our /etc/hosts file contains 2 entries with localhost 127.0.0.1.
The doOnChannelInit is being called exact same number of times as the repeated entry for localhost (with the same IP).

Is this the expected behaviour? If not let us file a bug.

**Comment by violetagg** [comment]
@AmandeepSingh97 Is it possible to paste here the entries from the `/etc/hosts`
and the logs like the following:

```
20:28:47.902 [reactor-http-nio-2] DEBUG r.netty.transport.TransportConnector - [id:f2dba4b7] Connecting to [localhost/127.0.0.1:12345].
20:28:48.911 [reactor-http-nio-2] DEBUG r.netty.transport.TransportConnector - [id:f2dba4b7] Connect attempt to [localhost/127.0.0.1:12345] failed.
```

**Comment by AmandeepSingh97** [comment]
Working case 

- logs:
`2021-08-10 16:02:34,959 [main] DEBUG TcpResources - [http] resources will use the default LoopResources: DefaultLoopResources {prefix=reactor-http, daemon=true, selectCount=16, workerCount=16}
2021-08-10 16:02:34,961 [main] DEBUG TcpResources - [http] resources will use the default ConnectionProvider: reactor.netty.resources.DefaultPooledConnectionProvider@188598ad
2021-08-10 16:02:34,962 [main] DEBUG DefaultLoopIOUring - Default io_uring support : false
2021-08-10 16:02:34,982 [main] DEBUG DefaultLoopEpoll - Default Epoll support : false
2021-08-10 16:02:34,983 [main] DEBUG DefaultLoopKQueue - Default KQueue support : false
2021-08-10 16:02:35,234 [reactor-http-nio-1] DEBUG ServerTransport - [id:23a90ecd, L:/127.0.0.1:56370] Bound new server
2021-08-10 16:02:37,485 [main] DEBUG PooledConnectionProvider - Creating a new [http] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=1000, pendingAcquireTimeout=45000}] for [localhost:12345]
2021-08-10 16:02:37,525 [reactor-http-nio-3] DEBUG PooledConnectionProvider - [id:b0a51e05] Created a new pooled channel, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
2021-08-10 16:02:37,557 [reactor-http-nio-3] DEBUG TransportConfig - [id:b0a51e05] Initialized pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2021-08-10 16:02:37,558 [reactor-http-nio-3] DEBUG HttpClient - [id:b0a51e05] REGISTERED
2021-08-10 16:02:37,596 [reactor-http-nio-3] DEBUG TransportConnector - [id:b0a51e05] Connecting to [localhost/127.0.0.1:12345].
2021-08-10 16:02:37,596 [reactor-http-nio-3] DEBUG HttpClient - [id:b0a51e05] CONNECT: localhost/127.0.0.1:12345
2021-08-10 16:02:37,604 [reactor-http-nio-3] DEBUG HttpClient - [id:b0a51e05] CLOSE
2021-08-10 16:02:37,605 [reactor-http-nio-3] DEBUG TransportConnector - [id:b0a51e05] Connect attempt to [localhost/127.0.0.1:12345] failed.
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:12345`

- /etc/hosts file:
\#\#
\# Host Database
\#
\# localhost is used to configure the loopback interface
\# when the system is booting.  Do not change this entry.
\#\#
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
\# Added by Docker Desktop
\# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
\# End of section

Not Working case 

- logs:
`2021-08-10 17:05:23,117 [main] DEBUG TcpResources - [http] resources will use the default LoopResources: DefaultLoopResources {prefix=reactor-http, daemon=true, selectCount=16, workerCount=16}
2021-08-10 17:05:23,119 [main] DEBUG TcpResources - [http] resources will use the default ConnectionProvider: reactor.netty.resources.DefaultPooledConnectionProvider@7cf78c85
2021-08-10 17:05:23,120 [main] DEBUG DefaultLoopIOUring - Default io_uring support : false
2021-08-10 17:05:23,132 [main] DEBUG DefaultLoopEpoll - Default Epoll support : false
2021-08-10 17:05:23,132 [main] DEBUG DefaultLoopKQueue - Default KQueue support : false
2021-08-10 17:05:23,276 [reactor-http-nio-1] DEBUG ServerTransport - [id:70336a98, L:/127.0.0.1:57039] Bound new server
2021-08-10 17:05:24,820 [main] DEBUG PooledConnectionProvider - Creating a new [http] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=1000, pendingAcquireTimeout=45000}] for [localhost:12345]
2021-08-10 17:05:24,846 [reactor-http-nio-3] DEBUG PooledConnectionProvider - [id:b2e1dd43] Created a new pooled channel, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
2021-08-10 17:05:24,864 [reactor-http-nio-3] DEBUG TransportConfig - [id:b2e1dd43] Initialized pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2021-08-10 17:05:24,864 [reactor-http-nio-3] DEBUG HttpClient - [id:b2e1dd43] REGISTERED
2021-08-10 17:05:24,887 [reactor-http-nio-3] DEBUG TransportConnector - [id:b2e1dd43] Connecting to [localhost/127.0.0.1:12345].
2021-08-10 17:05:24,887 [reactor-http-nio-3] DEBUG HttpClient - [id:b2e1dd43] CONNECT: localhost/127.0.0.1:12345
2021-08-10 17:05:24,892 [reactor-http-nio-3] DEBUG HttpClient - [id:b2e1dd43] CLOSE
2021-08-10 17:05:24,892 [reactor-http-nio-3] DEBUG TransportConnector - [id:b2e1dd43] Connect attempt to [localhost/127.0.0.1:12345] failed.
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:12345
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-08-10 17:05:24,899 [reactor-http-nio-3] DEBUG PooledConnectionProvider - [id:0de53cb2] Created a new pooled channel, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
2021-08-10 17:05:24,899 [reactor-http-nio-3] DEBUG TransportConfig - [id:0de53cb2] Initialized pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2021-08-10 17:05:24,899 [reactor-http-nio-3] DEBUG HttpClient - [id:0de53cb2] REGISTERED
2021-08-10 17:05:24,899 [reactor-http-nio-3] DEBUG HttpClient - [id:b2e1dd43] UNREGISTERED
2021-08-10 17:05:24,900 [reactor-http-nio-3] DEBUG TransportConnector - [id:0de53cb2] Connecting to [localhost/127.0.0.1:12345].
2021-08-10 17:05:24,900 [reactor-http-nio-3] DEBUG HttpClient - [id:0de53cb2] CONNECT: localhost/127.0.0.1:12345
2021-08-10 17:05:24,900 [reactor-http-nio-3] DEBUG HttpClient - [id:0de53cb2] CLOSE
2021-08-10 17:05:24,900 [reactor-http-nio-3] DEBUG TransportConnector - [id:0de53cb2] Connect attempt to [localhost/127.0.0.1:12345] failed.
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:12345
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-08-10 17:05:24,904 [reactor-http-nio-3] DEBUG HttpClient - [id:0de53cb2] CLOSE
2021-08-10 17:05:24,905 [reactor-http-nio-3] DEBUG HttpClient - [id:0de53cb2] CLOSE
2021-08-10 17:05:24,909 [reactor-http-nio-3] DEBUG HttpClient - [id:0de53cb2] UNREGISTERED
`

- /etc/hosts file:
\# Host Database
\#
\# localhost is used to configure the loopback interface
\# when the system is booting.  Do not change this entry.
\#\#
127.0.0.1       localhost
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
\# Added by Docker Desktop
\# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
\# End of section

@violetagg We have two entries for localhost in logs (both have the same IP)

**Comment by violetagg** [comment]
@AmandeepSingh97 Ok. Netty does not remove the duplicated entries.

**Comment by AmandeepSingh97** [comment]
Is this a fit for a bug? Or is there a major reason we do not remove duplicates?

**Comment by violetagg** [comment]
@AmandeepSingh97 We do not remove the duplicating entires because we don't know what was the intention of the system administrator that configured the `/etc/hosts` file. Whether this is a mistake or it is added intentionally.

**Comment by AmandeepSingh97** [comment]
Thanks for confirming and your help on this issue @violetagg
We have changed our test assertions accordingly
