### ISSUE TITLE
NPE happens when http client metrics enabled

### ISSUE THREAD

**Issue by tbartlomiejczyk** [reactor/reactor-netty#1766]
NPE warning is logged:

An exception was thrown by reactor.netty.http.client.HttpClientMetricsHandler$$Lambda$990/0x0000000800924840.operationComplete()

java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
	at io.micrometer.core.instrument.ImmutableTag.<init>(ImmutableTag.java:35) ~[micrometer-core-1.7.0.jar:1.7.0]
	at io.micrometer.core.instrument.Tag.of(Tag.java:29) ~[micrometer-core-1.7.0.jar:1.7.0]
	at io.micrometer.core.instrument.Tags.of(Tags.java:254) ~[micrometer-core-1.7.0.jar:1.7.0]
	at io.micrometer.core.instrument.AbstractTimerBuilder.tags(AbstractTimerBuilder.java:57) ~[micrometer-core-1.7.0.jar:1.7.0]
	at io.micrometer.core.instrument.Timer$Builder.tags(Timer.java:316) ~[micrometer-core-1.7.0.jar:1.7.0]
	at reactor.netty.http.client.MicrometerHttpClientMetricsRecorder.lambda$recordDataSentTime$1(MicrometerHttpClientMetricsRecorder.java:60) ~[reactor-netty-http-1.0.7.jar:1.0.7]
...

## Expected Behavior
NPE doesn't happen. Micrometer is not called or is called with valid parameters.

## Actual Behavior
Micrometer is called with invalid parameters.

## Steps to Reproduce
https://github.com/tbartlomiejczyk/netty-http-client-metrics-npe

## Your Environment
* Reactor version: 3.4.6
* Reactor netty version: 1.0.7
* Netty version: 4.1.65.Final
* Spring Boot version: 2.5.1
* Spring Cloud Gateway version: 3.0.3
* JVM version (`java -version`): 11
* OS and version (eg. `uname -a`): windows 10

**Comment by ctlove0523** [comment]
@tbartlomiejczyk 
I download your project “netty-http-client-metrics-npe” and run test org.example.npeexample.NPETest#test,but i can't reproduce this issue,i got an “Connection prematurely closed BEFORE response” exception

**Comment by tbartlomiejczyk** [comment]
@ctlove0523 
Look for warning in the logs. Should be before “Connection prematurely closed BEFORE response”.

**Comment by violetagg** [comment]
@tbartlomiejczyk  @ctlove0523 I can reproduce it on Windows 10 OS (the OS specified by @tbartlomiejczyk).

**Comment by ctlove0523** [comment]
@violetagg 

My OS is Microsoft Windows [Version 10.0.19041.985],Java version is Java8，but i can not reproduce this issue,Java version affect this?

**Comment by violetagg** [comment]
@ctlove0523 I'm testing with `11.0.12`

**Comment by violetagg** [comment]
@tbartlomiejczyk @ctlove0523 this PR should fix the NPE #1769
