### ISSUE TITLE
Content is fully buffered in memory when serving over TLS

### ISSUE THREAD

**Issue by oleg-alexeyev** [reactor/reactor-netty#178]
### Expected behavior
Flushing content whenever write buffer high watermark is reached.

### Actual behavior
All content is buffered in memory until response body (`Flux<DataBuffer>`) is complete.

### Steps to reproduce
Serve big content over TLS, e.g. several GB file, GET it using `curl`: curl shows no progress, java process memory grows enormously.

### Version
spring-webflux 5.0.0.RELEASE
reactor-core 3.1.0.RELEASE
reactor-netty 0.7.0.RELEASE

### JVM version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version
Windows 7 64-bit, Debian 8 64-bit.

### Investigation
While debugging, the following things were noticed:
- `ChannelOperationsHandler` calls `ctx.write(msg, promise)` (line 304), but doesn't call `ctx.flush` (line 307) as `ctx.channel().isWritable()` always returns `false`.
- `ctx.channel().isWritable()` calls `ChannelOutboundBuffer.isWritable()`, which returns `unwritable`, but it's always `false`.
- It looks like data doesn't reach `ChannelOutboundBuffer` at all as its `addMessage()` method (line 110) doesn't get called with HTTPS, while it does with plain HTTP.
- All data is collected inside `SslHandler.write()` (line 697) in `pendingUnencryptedWrites`.

### Workaround
- Intercept `BiFunction<HttpServerRequest, HttpServerResponse, Mono<Void>>` (hanlder function passed to `HttpServer.start()` or `HttpServer.newHandler()`).
- Configure flush on each buffer: `response.options(SendOptions::flushOnEach)`.

With such workaround, data tranfer seems to be a bit slower, e.g. up to 60 MB/s with workaround over plain HTTP against max 90 MB/s without (`localhost` on Windows).

Tried also returning `Flux<Flux<DataBuffer>>` from controller, but got `org.springframework.web.server.NotAcceptableStatusException: Response status 406 with reason "Could not find acceptable representation"` :(.

**Comment by violetagg** [comment]
Can you provide small reproducible example?

**Comment by alexmaddriver** [comment]
@smaldini Do you have any idea when 0.7.1.RELEASE is supposed to happen? Cause, in my opinion, this issue that we discovered is a stopper for any service or webapp serving relatively large content, especially simultaneously. E.g. in our case the app grows easily above 4-5GB RAM.

**Comment by alexmaddriver** [comment]
@violetagg we can certainly provide an example on Monday. But i believe you can reproduce on your side just trying to download several gigs file (e.g. ISO image) over HTTPS.

**Comment by oleg-alexeyev** [comment]
Here you are:
https://gist.github.com/oleg-alexeyev/a44dac6150e350ce0d06e5af3a7b159b

For testing I'm using a virtual disk of 26G size like this:
```
java ... Test "C:\Users\alexol\VirtualBox VMs\Debian 9.1 64-bit\Debian 9.1 64-bit.vdi"
```
and then
```
curl -o content https://localhost:51767
```
Curl shows no progress and java process consumes more and more memory. After interrupting curl with Ctrl+C, java process shrinks.

Here is some output from the server:
```
[DEBUG] (main) Using Console logging
[DEBUG] (main) Default epoll support : false
[DEBUG] (main) Connecting new channel: DefaultChannelPromise@1372ed45(success)
[ INFO] (main) Started HttpServer on /0:0:0:0:0:0:0:0:51767
...
[DEBUG] (reactor-http-nio-3) SSL enabled using engine OpenSslEngine
[DEBUG] (reactor-http-nio-3) New http connection, requesting read
[DEBUG] (reactor-http-nio-3) After pipeline DefaultChannelPipeline{(reactor.left.sslLoggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.sslReader = reactor.ipc.netty.channel.SslReadHandler), (ServerContextHandler#0 = reactor.ipc.netty.channel.ServerContextHandler), (reactor.left.httpDecoder = io.netty.handler.codec.http.HttpRequestDecoder), (reactor.left.httpEncoder = io.netty.handler.codec.http.HttpResponseEncoder), (reactor.left.httpServerHandler = reactor.ipc.netty.http.server.HttpServerHandler), (reactor.right.reactiveBridge = reactor.ipc.netty.channel.ChannelOperationsHandler)}
[TRACE] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] End of the pipeline, User event SslHandshakeCompletionEvent(SUCCESS)
[DEBUG] (reactor-http-nio-3) [HttpServer] [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] handler is being applied: Test$$Lambda$9/503195940@53150187
[DEBUG] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] Writing object DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
transfer-encoding: chunked
[DEBUG] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] Writing object ByteBufFlux
[TRACE] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] Pending write size = 524288
...
[TRACE] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] Pending write size = 1844969472
[DEBUG] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] Write state change false
[DEBUG] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] Write state change true
окт 09, 2017 1:49:47 PM io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught
WARNING: An exception 'io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1879048199, max: 1888485376)' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1879048199, max: 1888485376)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
	at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1779)
	at io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:1790)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:759)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:731)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:712)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.handler.logging.LoggingHandler.flush(LoggingHandler.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at reactor.ipc.netty.channel.ChannelOperationsHandler$PublisherSender.onError(ChannelOperationsHandler.java:540)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:261)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:199)
	at reactor.ipc.netty.channel.ChannelOperationsHandler$PublisherSender.onSubscribe(ChannelOperationsHandler.java:596)
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:83)
	at reactor.ipc.netty.ByteBufFlux.subscribe(ByteBufFlux.java:241)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6447)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.drain(ChannelOperationsHandler.java:433)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.flush(ChannelOperationsHandler.java:179)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1041)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at reactor.ipc.netty.NettyOutbound.lambda$sendObject$6(NettyOutbound.java:298)
	at reactor.ipc.netty.FutureMono$DeferredFutureMono.subscribe(FutureMono.java:106)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:148)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:380)
	at reactor.ipc.netty.http.server.HttpServerOperations.onHandlerStart(HttpServerOperations.java:354)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
...
[DEBUG] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 - R:/127.0.0.1:51770] Writing object EmptyLastHttpContent
[TRACE] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 ! R:/127.0.0.1:51770] End of the pipeline, User event SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
[TRACE] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 ! R:/127.0.0.1:51770] Disposing ChannelOperation from a channel
[TRACE] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 ! R:/127.0.0.1:51770] End of the pipeline, User event [Handler Terminated]
[DEBUG] (reactor-http-nio-3) [id: 0x0ae135c9, L:/127.0.0.1:51767 ! R:/127.0.0.1:51770] Disposing context reactor.ipc.netty.channel.ServerContextHandler@1da2c2b5
```

**Comment by smaldini** [comment]
I am currently investigating a similar issue with @nebhale bear with me I'll keep you updated. Thanks for the detailed report as it confirms some of our observations (in a case of file upload).

**Comment by violetagg** [comment]
Hi,

Can you try to downgrade Netty's version to 4.1.13. Then try your scenario and tell us the result.

Thanks,
Violeta

**Comment by smaldini** [comment]
It does that seem that Netty has changed from using PendingWriteQueue to SslHandlerCoalescingBufferQueue which does not track size and therefore never update isWriteable as before. Keeping investigating.

**Comment by smaldini** [comment]
Pinging on netty for some feedback with https://github.com/netty/netty/issues/2752

**Comment by rstoyanchev** [comment]
> Tried also returning Flux<Flux<DataBuffer>> from controller

Probably something we could fix on the WebFlux side. Note that you can declare `ServerHttpResponse` as a controller method argument and then call the `writeAndFlushWith`.

**Comment by alexmaddriver** [comment]
HttpClient is also affected by this issue. It also buffers the whole content into memory when sending files via HTTPS.

**Comment by alexmaddriver** [comment]
Downgrading Netty to 4.1.13 solves the HttpServer buffering problems. 
However, HttpClient keeps to accumulate data and eventually fails with out of direct memory exception even with Netty 4.1.13.

**Comment by violetagg** [comment]
Hi,

We have several fixes in the snapshot version related to ByteBuff leaks, also prepared PR in Netty addressing the SslHandler issue https://github.com/netty/netty/pull/7309.

If you can test them it will be great.

Regards,
Violeta

**Comment by alexmaddriver** [comment]
Hi Violeta,

We looked deeper into the client leak and indeed this is caused by a different thingy, not SslHandler buffering. Guess you are referring to SHA-1: f1d8576993abe5ce0174301617dd49f61ba84193 commit which is supposed to fix HttpClient leak, right?

--
Alex

**Comment by violetagg** [comment]
yes

**Comment by alexmaddriver** [comment]
Just tried with reactor-netty-0.7.1.BUILD-20171017.105550-16.jar - the leak is still there, HttpClient fails with out of memory.

**Comment by violetagg** [comment]
ok can you create another issue for the HttpClient issue so that we track independent the server and the client issue? Please refer this and if you can provide an example or it is the same?

**Comment by alexmaddriver** [comment]
Maybe it might help you to pinpoint what is going wrong - memory consumption grows only when using HTTPS. With HTTP data transfer it works well.

**Comment by alexmaddriver** [comment]
Okey, will create a new issue and test case tomorrow.

**Comment by alexmaddriver** [comment]
HttpClient related case: https://github.com/reactor/reactor-netty/issues/188

**Comment by violetagg** [comment]
Netty version is updated to `v4.1.17.Final` which includes a fix for the issue with SslHandler.

**Comment by oleg-alexeyev** [comment]
Tested with netty 4.1.17.Final and reactor-netty 0.7.2 - content is not buffered into memory anymore. Thanks a lot!
