### ISSUE TITLE
https proxy error

### ISSUE THREAD

**Issue by xiguayizu** [reactor/reactor-netty#1801]
## Expected Behavior

It can use https proxy

## Actual Behavior

error:
io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, basic, /52.28.250.157:40100 => whatismyip.akamai.com:80, status: 407 Proxy Authentication Required

## Steps to Reproduce

```java
public class HTTPS_PROXY_TEST {
    public static void main(String[] args) {
        HttpClient client = HttpClient.create()
//                .headers(h -> h.add("Authorization", "asd"))
                .proxy(spec -> spec.type(ProxyProvider.Proxy.HTTP)
                        .host("52.28.250.157")
                        .port(40100)
                        .username("a547922")
                        .password(s-> "17e11114")
                        .connectTimeoutMillis(20_000));

        String block = client.get()
                .uri("http://whatismyip.akamai.com")
                .responseContent()
                .aggregate()
                .asString()
                .block();
        System.out.println("block = " + block);
    }
}
```

## Possible Solution

```shell
curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 52.28.250.157:40100 --proxy-user a547922:17e11114
is shell ok but...
```

## Your Environment

```shell
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.60.Final</version>
        </dependency>
```

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
* OS and version (eg. `uname -a`):

**Comment by xiguayizu** [comment]
io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, basic, /52.28.250.157:40100 => whatismyip.akamai.com:80, status: 407 Proxy Authentication Required
	at io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200)
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by violetagg** [comment]
@xiguayizu  Can you tell us the result from the command below (I added `--proxytunnel` to the curl command)

`curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 52.28.250.157:40100 --proxy-user a547922:17e11114 --proxytunnel`

**Comment by xiguayizu** [comment]
> @xiguayizu 你能告诉我们下面命令的结果吗（我添加`--proxytunnel`到 curl 命令中）
> 
> `curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 52.28.250.157:40100 --proxy-user a547922:17e11114 --proxytunnel`

so sorry， the ip and password was changed.

address: 65.2.65.42
port: 40100
user: a547922
pass: c86856f8

shell return ip: 
```
curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 65.2.65.42:40100 --proxy-user a547922:c86856f8 --proxytunnel
117.230.178.66
```

**Comment by violetagg** [comment]
@xiguayizu I didn't get it did you receive a response with `--proxytunnel`

**Comment by xiguayizu** [comment]
> @xiguayizu I didn't get it, did you receive a response with `--proxytunnel`
After I ran, he returned to this
```
$ curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 65.2.65.42:40100 --proxy-user a547922:c86856f8 --proxytunnel
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0     18      0 --:--:-- --:--:-- --:--:--    184
3.226.29.123
```

**Comment by xiguayizu** [comment]
> @xiguayizu但是你的 URL 在 java 程序中是不同的...请`curl`使用你在 java 程序中使用的相同 URL执行命令

ok... sorry
shell
```shell
$ curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 65.2.65.42:40100 --proxy-user a547922:c86856f8 --proxytunnel
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0     10      0  0:00:01  0:00:01 --:--:--    10

47.11.126.151
```

java
```java
package com.example.demo.login.httpUtil;

import reactor.netty.http.client.HttpClient;
import reactor.netty.transport.ProxyProvider;

import javax.net.ssl.SSLException;

/*
    $ curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 65.2.65.42:40100 --proxy-user a547922:c86856f8 --proxytunnel
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100    13  100    13    0     0     10      0  0:00:01  0:00:01 --:--:--    10

    47.11.126.151

    is ok but...
* */
public class HTTPS_PROXY_TEST {
    public static void main(String[] args) throws SSLException {
//        String auth = "Basic " + Base64.getEncoder().encodeToString("a547922:c86856f8".getBytes());

        HttpClient client = HttpClient.create()
                .noSSL()
//                .headers(h -> h.add("Authentication", auth))
                .proxy(spec -> spec.type(ProxyProvider.Proxy.HTTP)
                        .host("65.2.65.42")
                        .port(40100)
                        .username("a547922")
                        .password(pwd-> "c86856f8")
                        .connectTimeoutMillis(20_000));

        String block = client.get()
                .uri("whatismyip.akamai.com")
                .responseContent()
                .aggregate()
                .asString()
                .block();
        System.out.println("block = " + block);
    }
}
```

error
```
io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, basic, /65.2.65.42:40100 => whatismyip.akamai.com:80, status: 407 Proxy Authentication Required
	at io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200) ~[netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:258) ~[netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272) [netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]

2021-09-15 22:07:51.862 ERROR 461209 --- [io-25003-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is reactor.core.Exceptions$ReactiveException: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, basic, /65.2.65.42:40100 => whatismyip.akamai.com:80, status: 407 Proxy Authentication Required] with root cause

io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, basic, /65.2.65.42:40100 => whatismyip.akamai.com:80, status: 407 Proxy Authentication Required
	at io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200) ~[netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:258) ~[netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272) ~[netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]

```

**Comment by xiguayizu** [comment]
> @xiguayizu但是你的 URL 在 java 程序中是不同的...请`curl`使用你在 java 程序中使用的相同 URL执行命令




```shell
# java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

# uname -a
Linux iZt4n5m85tdj36ckmrqnorZ 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Mon Mar 1 17:16:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

//  socks5:
# curl http://whatismyip.akamai.com --socks5 18.138.238.133:40000 -U a547922:38622b99
183.78.112.118

//  https:
# curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 65.2.65.42:40100 --proxy-user a547922:c86856f8 --proxytunnel
157.43.255.69
```
`shell is ok. `


`code socks5 proxy is ok `
`code https proxy is faild`
```java
package com.example.demo.login.httpUtil;

import reactor.netty.http.client.HttpClient;
import reactor.netty.transport.ProxyProvider;

import javax.net.ssl.SSLException;

/*
    $ curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 65.2.65.42:40100 --proxy-user a547922:c86856f8 --proxytunnel
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100    13  100    13    0     0     10      0  0:00:01  0:00:01 --:--:--    10

    47.11.126.151

    is ok but...
* */
public class HTTPS_PROXY_TEST {
    /**
     * err:
     *
     * */
    public static void testHTTPS(){
        /**
         * curl http://whatismyip.akamai.com -m 10 --connect-timeout 10 --speed-limit 1 -x 65.2.65.42:40100 --proxy-user a547922:c86856f8 --proxytunnel
         * 157.43.220.11
         * */
        HttpClient client = HttpClient.create()
                .noSSL()
                .proxy(spec -> spec.type(ProxyProvider.Proxy.HTTP)
                        .host("65.2.65.42")
                        .port(40100)
                        .username("a547922")
                        .password(pwd-> "c86856f8")
                        .connectTimeoutMillis(20_000));

        String block = client.get()
                .uri("http://whatismyip.akamai.com")
                .responseContent()
                .aggregate()
                .asString()
                .block();
        System.out.println("https proxy => " + block);
    }
    /**
     * ok
     * */
    public static void testSocks5(){
        /**
         * curl http://whatismyip.akamai.com --socks5 18.138.238.133:40000 -U a547922:38622b99
         * 175.137.149.59
         * */
        HttpClient client = HttpClient.create()
                .noSSL()
                .proxy(spec -> spec.type(ProxyProvider.Proxy.SOCKS5)
                        .host("18.138.238.133")
                        .port(40000)
                        .username("a547922")
                        .password(pwd-> "38622b99")
                        .connectTimeoutMillis(20_000));

        String block = client.get()
                .uri("http://whatismyip.akamai.com")
                .responseContent()
                .aggregate()
                .asString()
                .block();
        System.out.println("socks5 proxy => " + block);
    }
    public static void main(String[] args) {
        try{
            testSocks5();
        }catch (Exception e){
            System.err.println(e);
        }
        try{
            testHTTPS();
        }catch (Exception e){
            System.err.println(e);
        }
    }
}

```

err:
```shell
socks5 proxy => 183.78.113.52
2021-09-15 22:54:37.706  WARN 462708 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect    : [id: 0x51530d66, L:/172.22.213.199:42456 - R:65.2.65.42/65.2.65.42:40100] The connection observed an error

io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, basic, /65.2.65.42:40100 => whatismyip.akamai.com:80, status: 407 Proxy Authentication Required
	at io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200) ~[netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:258) ~[netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272) [netty-handler-proxy-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]

reactor.core.Exceptions$ReactiveException: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, basic, /65.2.65.42:40100 => whatismyip.akamai.com:80, status: 407 Proxy Authentication Required

```

**Comment by violetagg** [comment]
@xiguayizu Do you still experience this issue?

**Comment by violetagg** [comment]
@xiguayizu I'm closing this one. We can reopen it, if it is needed.
