### ISSUE TITLE
Reactor Netty TCP server Exception if client shut down Interruptedly

### ISSUE THREAD

**Issue by v-saurabhsingh** [reactor/reactor-netty#1814]
## Expected Behavior
 How can I handle this exception

## Actual Behavior
This exception occurs when client shut down

```
2021-09-20 21:44:17.512  INFO 6368 --- [actor-tcp-nio-2] org.reactor.tcp.Server                   : in doOnError: An existing connection was forcibly closed by the remote host
2021-09-20 21:44:17.521 ERROR 6368 --- [actor-tcp-nio-2] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: java.io.IOException: An existing connection was forcibly closed by the remote host
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-09-20 21:44:17.521  INFO 6368 --- [actor-tcp-nio-2] org.reactor.tcp.Server                   : out doOnCancel

```

## Server Implementation

```
		TcpServer tcpServer = TcpServer.create()
				.doOnBind(tcpServerConfig-> log.info("doOnBind {}",tcpServerConfig))
				.doOnBound(disposableServer-> log.info("doOnBound {}",disposableServer))
				.doOnUnbound(disposableServer-> log.info("doOnUnbound {}",disposableServer))
				.doOnConnection(connection-> log.info("doOnConnection {}",connection))
				.doOnChannelInit((connectionObserver,channel,remoteAddress)-> log.info("doOnConnection {}, {}, {}",connectionObserver,channel,remoteAddress))
				.host("127.0.0.1")
				.port(8089)
				.wiretap(true)
				//.metrics(true)
				.noSSL();
		DisposableServer server = tcpServer.handle((in,out)-> {
			//return inbound.receive().asString().log().then();
			in.receive().asString()
					.doOnError(ex->log.info("in doOnError: {}",ex.getMessage()))
					.doOnCancel(()->log.info("in doOnCancel"))
					.subscribe(i->log.info("in RECEIVED: {}",i));
			return out.neverComplete()
					.doOnTerminate(()->log.info("out doOnTerminate"))
					.doOnError(ex->log.info("out doOnError: {}",ex.getMessage()))
					.doOnCancel(()->log.info("out doOnCancel"));
		}).bindNow();
		server.onDispose()
				.block();
```

## TCP Client Implementation

```
TcpClient client = TcpClient.create()
				.doOnConnect(connection-> log.info("doOnConnect {}",connection))
				.doOnConnected(connection-> log.info("doOnConnected {}",connection))
				.doOnDisconnected(connection-> log.info("doOnDisconnected {}",connection))
				.doOnChannelInit((connectionObserver,channel,remoteAddress)-> log.info("doOnConnection {}, {}, {}",connectionObserver,channel,remoteAddress))
				.host("127.0.0.1")
				.port(8089)
				.wiretap(true)
				//.metrics(true)
				.noSSL();
		Connection connection = client.handle((in, out) -> {
			//return out.send(Flux.concat(ByteBufFlux.fromString(Mono.just("echo")), in.receive().retain()))
			in.receive().asString().subscribe(i->{
				log.info("RECEIVED: {}",i);
			});
			return out.sendString(Flux.interval(Duration.ofMillis(100)).map(l -> {
				final String msg= Long.toString(l);
				log.info("SEND: {}",msg);
				return msg;
			}));
		}).connectNow();
		connection.onDispose()
				.block();
```

* Reactor version(s) used: bom 2020.0.11
* JVM version (`java -version`): 11
@rmorgan @violetagg

**Comment by violetagg** [comment]
@v-saurabhsingh When the client closes the connection, the server can just clean up the resources utilised for that connection. What do you mean with `How can I handle this exception`. From the provided logs it seems that the event connection closed is sent and you can cleanup all resources that needs to be cleanup `org.reactor.tcp.Server                   : in doOnError: An existing connection was forcibly closed by the ...`

**Comment by v-saurabhsingh** [comment]
```org.reactor.tcp.Server : in doOnError: An existing connection was forcibly closed by the ...```
```
in.receive().asString()
                    .doOnTerminate(() -> log.info("in doOnTerminate"))
                    .doOnError(ex -> log.info("in doOnError: {}", ex.getMessage()))
                    .doOnCancel(() -> log.info("in doOnCancel"))
                    .subscribe(i -> log.info("in RECEIVED: {}", i));
```
 I already provided doOnError callback then why I am getting this exception  
 I have handled all callbacks so I am not able to get in which event I am getting this exception. How can I avoid this exception.
I can not rely on client. Client is not in my hand that is remote TCP client. It can be network issue or any other issue. But at server side I must be able to handle all events. But is this case I am just terminating client application in Intellij by clicking terminate button

**Comment by violetagg** [comment]
@v-saurabhsingh Is your concerns that this log appears in the logs? `2021-09-20 21:44:17.521 ERROR 6368 --- [actor-tcp-nio-2] reactor.core.publisher.Operators reactor.core.Exceptions$ErrorCallbackNotImplemented: java.io.IOException: An existing connection`

**Comment by v-saurabhsingh** [comment]
yes That is concern and Also want to know event on that it  occurs

**Comment by v-saurabhsingh** [comment]
1:44:17.521 ERROR 6368 --- [actor-tcp-nio-2] reactor.core.publisher.Operators         : Operator called default onErrorDropped

**Comment by simonbasle** [comment]
`doOnError` have their use (ie. they can observe errors in intermediate steps, that are later recovered from with an `onErrorResume`) but the `ErrorCallbackNotImplemented` "warning" isn't concerned with upstream doOnError. It points to a bad practice in the final `subscribe`.

In 3.3.x, it used to throw the exception and now it is just passed to the `onErrorDropped` hook, which logs by default. So there's even less chance for it to observe that there's a `doOnError` upstream, even less to understand that it correctly caught and processed the error.

In a simple case like that, where the side effects are right before the final `subscribe`, I would recommend you don't use `doOnNext`/`doOnError`[/`doOnComplete`] but the fuller form of `subscribe(onNextHandler, onErrorHandler[, onCompleteHandler])`.
