### ISSUE TITLE
reactor-netty http server out of directMemoryError

### ISSUE THREAD

**Issue by sweetcczhang** [reactor/reactor-netty#1869]
hello, I use reactor-netty as a http  server ,but there may be some problems ,it is frequently  out of direct memory,
the code :

```
public void start() {
        LoopResources loop = LoopResources.create("event-loop-" + config.getName(), config.getIoSelectCount(), config.getIoWorkerCount(), true);
        
        server = HttpServer.create()
            .runOn(loop)
            .port(config.getPort())
            .childOption(ChannelOption.SO_KEEPALIVE,true)
            .childOption(ChannelOption.SO_RCVBUF,1024*1024)
            .childOption(ChannelOption.SO_SNDBUF,1024*1024)
            .childOption(ChannelOption.CONNECT_TIMEOUT_MILLIS, config.getConnectTimeout())
            .handle(this::handler)
                .bindNow();
    }

    
    public ResponsePublisher handler(HttpServerRequest request, HttpServerResponse response){
        ResponsePublisher publisher = new DefaultResponsePublisher(response);
        request
            .receive()
            .aggregate()
            .subscribe(byteBuf -> httpHandler.handle(request, byteBuf, publisher));

        return publisher;
    }
```

error:

```
 [event-loop-HTTPNetGapServer-epoll-3] WARN  i.n.c.AbstractChannelHandlerContext - An exception 'reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.netty.ReactorNetty$InternalNettyException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 6425673735, max: 6442450944)' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 6425673735, max: 6442450944)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:726)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:681)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:342)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

reactor-netty version:1.0.5
openJdk:1.8
runtime environment : docker

Is it my mistake?

**Comment by violetagg** [comment]
@sweetcczhang Are you able to provide some reproducible example. From the code above I can see only some HttpServer configurations but it is not obvious what happens with the request data.

**Comment by violetagg** [comment]
@sweetcczhang Were you able to test with the extended logging from my previous comment.

I've edited your comment to improve the formatting.

**Comment by violetagg** [comment]
@sweetcczhang I'm closing this one. If you are able to provide the requested information, we can reopen it.

**Comment by sweetcczhang** [comment]
Are there some way to aggregate data not in memory?
