### ISSUE TITLE
Connection is getting Closed while forwarding request from Spring Cloud APIGateway to backend services. 

### ISSUE THREAD

**Issue by rajatbehl** [reactor/reactor-netty#1870]
Getting issue with Spring Cloud APIGateway while forwarding request to backend services. 

Spring Gateway version: 3.0.3 Spring Boot version: 2.5.3 Reactor core versoin: 3.4.8 Reactor netty core: 1.0.9
The connection observed an error reactor.netty.channel.AbortedException: Connection has been closed. Here we are forwarding request for url "/v1/kyc/upload" from Spring Cloud API Gateway micro service to other micro service running on 172.20.0.13:3141

Exception at Spring Cloud API gateway

```
2021-10-30 12:33:09,687 WARN reactor.util.Loggers$Slf4JLogger [reactor-http-epoll-4] [id:a0483b16-1, L:/10.0.25.39:44310 - R:172.20.0.13/172.20.0.13:3141] The connection observed an error
reactor.netty.channel.AbortedException: Connection has been closed
        at reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:559)
        at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:73)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
        at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-30 12:33:09,687 ERROR org.springframework.web.server.adapter.HttpWebHandlerAdapter [reactor-http-epoll-4] [cc4ebd14-1999] 500 Server Error for HTTP POST "/v1/kyc/upload"
reactor.netty.channel.AbortedException: Connection has been closed
        at reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:559)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP POST "/v1/kyc/upload" [ExceptionHandlingWebHandler] 
```

**Exception at second micro service** 

```
reactor.netty.channel.AbortedException: Connection has been closed
        at reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:559)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ HTTP POST "/v1/kyc/upload" [ExceptionHandlingWebHandler]
Stack trace:
                at reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:559)
                at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:73)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
                at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
                at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
                at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
                at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
                at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by violetagg** [comment]
@rajatbehl `AbortedException: Connection has been closed` Typically is cause by a client closing a connection. If that's not the case please provide reproducible example and/or tcp dump so that we can track which peer closes the connection.

**Comment by rajatbehl** [comment]
@violetagg 
Please follow the link to have tcpdump taken at both api-gateway and second microservice on 30th oct for the issue mentioned above at "2021-10-30 12:33:09"

I am not able to upload zip file directly, please use this link https://we.tl/t-BFiodxJPs3 to download tcpdump

**Comment by violetagg** [comment]
@rajatbehl Try to extract only the relevant part from the tcp dump i.e. for the concrete destination/source address and where you have RST/FIN

**Comment by rajatbehl** [comment]
@violetagg I have updated the tcp dump with relevant part. API Gateway is running on host "10.0.25.39" and kyc service is running on host 172.20.0.13, you can use below filters to debug this issue
Use "ip.dst == 172.20.0.13" as filter in api-gateway.pcap and "ip.src == 10.0.25.39" as filter in kyc.pcap
[tcpdump.zip](https://github.com/reactor/reactor-netty/files/7494046/tcpdump.zip)

**Comment by violetagg** [comment]
@rajatbehl there are many requests can you be more specific which one is the problematic one?

**Comment by rajatbehl** [comment]
@violetagg Can you please check for request for which SYN is sent to host "172.20.0.13" at "12:31:10", we got reactor.netty.channel.AbortedException: Connection has been closed exception for this request at "12:33:09" at both api gateway and kyc service.

**Comment by rajatbehl** [comment]
@violetagg Did you got a chance to look into this issue. Please let me know if you need anything from my side.

**Comment by violetagg** [comment]
@rajatbehl I cannot find anything with time "12:31:10". Is this time UTC or some other time zone?

**Comment by rajatbehl** [comment]
@violetagg Please check in IST time zone and we will check if original client closes the connection.
We are still facing this issue on production, please let me know if you need any help on this.

**Comment by violetagg** [comment]
@rajatbehl Please take a look whether this is the correct record. If yes, isn't the original client that is closing the connection? (this is the tcp dump from the gateway)
![Screenshot 2021-11-25 at 10 58 49](https://user-images.githubusercontent.com/696661/143411030-84de218d-77f2-4916-b78f-d36f97ad8899.png)

**Comment by rajatbehl** [comment]
@violetagg Yes, this is the correct record which means client is closing the connection before complete payload could be sent to API Gateway and then to KYC and which is why we are getting "reactor.netty.channel.AbortedException: Connection has been closed" exception at both API Gateway and KYC service.

Thanks @violetagg for helping to identify the issue. I will check what we can do here to avoid this.
