### ISSUE TITLE
HttpClient leaks when sending content over HTTPS

### ISSUE THREAD

**Issue by alexmaddriver** [reactor/reactor-netty#188]
### Expected behavior
HttpClient is able to send large files over HTTPS.

### Actual behavior
HttpClient fails with io.netty.util.internal.OutOfDirectMemoryError exception.

### Steps to reproduce
Reproducing test case: 
https://gist.github.com/alexmaddriver/917985dbb5bde4846b5d54510a29269d

First launch startContentStorageServer() and then trigger sending large file content using clientSendingHugeContentFile(). The files has to be created in advance at "c:\\temp\\issue\\very-large-file" path. In our case we use 6GB file. HttpClient keeps growing in memory and fails with exception at around 4GB boundary.

With HTTP protocol it doesn't leak and uploads content as expected.

The same leak is observed when using WebClient to upload data over HTTPS.

When connection is closed, the allocated memory is released back.

Thrown exception:
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1879048199, max: 1881145344)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:109) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.stream.ChunkedNioFile.readChunk(ChunkedNioFile.java:159) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.stream.ChunkedNioFile.readChunk(ChunkedNioFile.java:36) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.codec.http.HttpChunkedInput.readChunk(HttpChunkedInput.java:102) ~[netty-codec-http-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.codec.http.HttpChunkedInput.readChunk(HttpChunkedInput.java:43) ~[netty-codec-http-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:221) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:137) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
	at 
...

### Version
reactor-netty-0.7.1.BUILD-20171017.105550-16.
spring-webflux 5.0.0.RELEASE
reactor-core 3.1.0.RELEASE

**Comment by smaldini** [comment]
You tried to force netty to 4.1.13.Final ?

**Comment by oleg-alexeyev** [comment]
Yep, tried with 4.1.13 and it didn't help.

**Comment by smaldini** [comment]
Can you paste the stack under 4.1.13 just to see which path it uses here.

**Comment by violetagg** [comment]
Ok here is what I can see with the provided example:

In all cases I used 0.7.1.BUILD-SNAPSHOT

With Netty 4.1.16
<img width="993" alt="netty 4 1 16" src="https://user-images.githubusercontent.com/696661/31784552-c70276ee-b50a-11e7-9ec8-07b3ab6cc54c.png">

With Netty 4.1.17 snapshot
<img width="994" alt="netty 4 1 17 snapshot without fix" src="https://user-images.githubusercontent.com/696661/31784562-d532ed5c-b50a-11e7-9029-91aff2337334.png">

With Netty 4.1.17 snapshot with my PR for the SslHandler
<img width="994" alt="netty 4 1 17 snapshot with fix" src="https://user-images.githubusercontent.com/696661/31784585-e9bb3a9a-b50a-11e7-8234-83ad3c3e34e1.png">

So can you try again on you side, just grab my PR, then `mvn clean install -DskipTests=true` and then use 4.1.17.Final-SNAPSHOT

**Comment by alexmaddriver** [comment]
Hi Violet,

If you would provide us the Netty JAR with your PR it would be much easier for us to test against it. Of course we can try building it on our own, but it just takes a bit more time.

--
Alex

**Comment by alexmaddriver** [comment]
Hi,

Just tested and able to confirm that with your PR 4.1.17.Final-SNAPSHOT the HttpClient works good and seamlessly managed to send 10GB file over HTTPS. Great stuff!

--
Alex

**Comment by violetagg** [comment]
Duplicates #178
