### ISSUE TITLE
reactor.netty: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-netty#2022]
Hello Reactor Netty Team,

I would like to report an issue if you allow me.
First, I would like to present the setup.

The server is a server using Spring Webflux 2.6.x
The clients, multiple of them, will send requests to this server, **at a fix rate**, **for long time**.
Meaning, there is no burst, no high and low, it is as simple as clients sending requests to the server using a Spring Webclient, at a very stable and fixed rate.

**Reproducible 100% of the time**, the clients, after a while, are observing:
```
Exception in thread "main" org.springframework.web.reactive.function.client.WebClientRequestException: handshake timed out after 10000ms; nested exception is io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
   at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
   Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
   |_ checkpoint ⇢ Request to POST https://the-server:port/someAPI [DefaultWebClient]
Stack trace:
      at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
      at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
      at reactor.core.publisher.Mono.subscribe(Mono.java:4361)
      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
[...]
   Suppressed: java.lang.Exception: #block terminated with an error
      at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
      at reactor.core.publisher.Mono.block(Mono.java:1706)
[...]
Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
   at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2062)
   at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
   at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
   at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)
   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   at java.base/java.lang.Thread.run(Thread.java:834)
```
it is always reproducible fand this pattern can be observed:

Matching client, the server timestamps shows this at first.
```
WARN [myservice,,] 10 --- [or-http-epoll-2] .s.ApplicationProtocolNegotiationHandler : [id: 0x5f49bdce, L:/someIP:somePort - R:/someIP:somePort] Failed to select the application-level protocol:

io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2112) ~[netty-handler-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-classes-epoll-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```
```
WARN [myservice,,] 10 --- [or-http-epoll-3] .s.ApplicationProtocolNegotiationHandler : [id: 0xbb923c46, L:/someIP:somePort - R:/someIP:somePort] Failed to select the application-level protocol:

java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1063) ~[netty-handler-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[netty-transport-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-classes-epoll-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.73.Final.jar!/:4.1.73.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

Then, after a while, it will always get into this "state" seeing all requests with this on server side:
```
java.lang.OutOfMemoryError: Java heap space

WARN [myservice,,] 10 --- [or-http-epoll-4] .s.ApplicationProtocolNegotiationHandler : [id: 0xa09e351e, L:/someIP:somePort - R:/someIP:somePort] Failed to select the application-level protocol:

java.lang.OutOfMemoryError: Java heap space

ERROR [myservice,,] 10 --- [or-http-epoll-4] reactor.netty.transport.ServerTransport  : [a09e351e, L:/someIP:somePort - R:/someIP:somePort] onUncaughtException(SimpleConnection{channel=[id: 0xa09e351e, L:/someIP:somePort - R:/someIP:somePort]})

java.lang.OutOfMemoryError: Java heap space

WARN [myservice,,] 10 --- [        s0-io-1] i.n.c.AbstractChannelHandlerContext      : An exception 'java.lang.OutOfMemoryError: Java heap space' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:

java.lang.OutOfMemoryError: Java heap space

```

At this point, nothing, we need to restart the server entirely, as it seems there is no recovery.
I am having a very hard time understanding this issue.
Is it possible to kindly have a look at this issue please?

Thank you

**Comment by violetagg** [comment]
@patpatpat123 Most probably you use HTTP/2, is that correct?
If that's the case, can you try 1.0.16-SNAPSHOT because it might be this issue #1978.

**Comment by patpatpat123** [comment]
Hello @violetagg,

Absolutely! I am indeed using HTTP/2.
Having a hard time understanding issue https://github.com/reactor/reactor-netty/issues/1978 but will follow your advise and give it a go with 1.0.16-SNAPSHOT and update here with the result.

Thank you again

**Comment by violetagg** [comment]
@patpatpat123 That's good news! Thanks for testing it!
