### ISSUE TITLE
UnixDomainSocket not work on OS X

### ISSUE THREAD

**Issue by takaaki7** [reactor/reactor-netty#2024]
Using UnixDomainSocket on OS X causes IllegalArgumentException `Unsupported channel type: DomainSocketChannel`

## Actual Behavior
stack trace
```
Caused by: java.lang.IllegalArgumentException: Unsupported channel type: DomainSocketChannel
	at reactor.netty.resources.DefaultLoopNIO.getChannel(DefaultLoopNIO.java:50)
	at reactor.netty.resources.LoopResources.onChannel(LoopResources.java:214)
	at reactor.netty.tcp.TcpResources.onChannel(TcpResources.java:251)
	at reactor.netty.transport.TransportConfig.lambda$connectionFactory$1(TransportConfig.java:266)
	at reactor.netty.transport.TransportConnector.doInitAndRegister(TransportConnector.java:224)
	at reactor.netty.transport.TransportConnector.connect(TransportConnector.java:109)
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator.lambda$connectChannel$0(DefaultPooledConnectionProvider.java:497)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4371)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4307)
	at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:407)
	at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.pendingOffer(SimpleDequePool.java:558)
	at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:268)
	at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:432)
	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onSubscribe(DefaultPooledConnectionProvider.java:194)
	at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:676)
	at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:144)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4371)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4307)
	at reactor.netty.http.client.Http2Pool.drainLoop(Http2Pool.java:374)
	at reactor.netty.http.client.Http2Pool.pendingOffer(Http2Pool.java:487)
	at reactor.netty.http.client.Http2Pool.doAcquire(Http2Pool.java:273)
	at reactor.netty.http.client.Http2Pool$Borrower.request(Http2Pool.java:557)
	at reactor.netty.http.client.Http2ConnectionProvider$DisposableAcquire.onSubscribe(Http2ConnectionProvider.java:305)
	at reactor.netty.http.client.Http2Pool$BorrowerMono.subscribe(Http2Pool.java:629)
	at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:144)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:268)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:271)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
	at reactor.core.publisher.Mono.toFuture(Mono.java:4920)
	at jp.co.plaid.karte.domain.action.variable.LegacyActionClient.requestToLegacyActionServer(LegacyActionClient.java:255)
	... 60 more
```

Running with dependency `io.netty:netty-transport-native-kqueue:4.1.70.Final:osx-x86_64` also causes same exception.
`KQueue.isAvailable()` returns false because of the following UNAVAILABILITY_CAUSE.(I've debugged with debugger)
```
Method 'void io.netty.channel.unix.Socket.initialize(boolean)' name or signature does not match
  at io.netty.channel.kqueue.Native.registerUnix(Native Method)
  at io.netty.channel.kqueue.Native.access$000(Native.java:56)
  at io.netty.channel.kqueue.Native$1.run(Native.java:81)
  at io.netty.channel.unix.Unix.registerInternal(Unix.java:57)
  at io.netty.channel.kqueue.Native.<clinit>(Native.java:78)
  at io.netty.channel.kqueue.KQueue.<clinit>(KQueue.java:38)
  at java.base/java.lang.Class.forName0(Native Method)
  at java.base/java.lang.Class.forName(Class.java:375)
  at reactor.netty.resources.DefaultLoopEpoll.<clinit>(DefaultLoopEpoll.java:109)
  at reactor.netty.resources.DefaultLoopNativeDetector.<clinit>(DefaultLoopNativeDetector.java:35)
  at reactor.netty.resources.LoopResources.hasNativeSupport(LoopResources.java:270)
  at reactor.netty.resources.DefaultLoopResources.onClient(DefaultLoopResources.java:138)
  at reactor.netty.transport.NameResolverProvider.newNameResolverGroup(NameResolverProvider.java:473)
  at reactor.netty.tcp.TcpResources.getOrCreateDefaultResolver(TcpResources.java:315)
  at reactor.netty.http.HttpResources.getOrCreateDefaultResolver(HttpResources.java:139)
  at reactor.netty.http.client.HttpClientConfig.defaultAddressResolverGroup(HttpClientConfig.java:382)
  at reactor.netty.transport.ClientTransportConfig.resolverInternal(ClientTransportConfig.java:224)
  at reactor.netty.http.client.HttpClientConfig.resolverInternal(HttpClientConfig.java:436)
  at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:264)
  at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
  at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
  at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
  at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
  at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:271)
  at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
  at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
  at reactor.core.publisher.Mono.toFuture(Mono.java:4920)
  at jp.co.plaid.karte.domain.action.variable.LegacyActionClient.requestToLegacyActionServer(LegacyActionClient.java:263)
  at jp.co.plaid.karte.DebugT.test(DebugT.java:25)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
  at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
  at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
  at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
  at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
  at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
  at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
  at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
  at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
  at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
  at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
  at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
  at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
  at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
  at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

## Steps to Reproduce

```java
@Test
public void repoCase() {
    HttpClient.create().protocol(HttpProtocol.H2C).remoteAddress(() -> new DomainSocketAddress("/tmp/my.sock"));
}
```

## Your Environment

* Reactor version(s) used:

io.projectreactor.netty:reactor-netty-core:1.0.15
io.projectreactor.netty:reactor-netty-http:1.0.15

* Other relevant libraries versions (eg. `netty`, ...):

io.netty:netty-transport-native-kqueue:4.1.70.Final:osx-x86_64

* JVM version (`java -version`):
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
```

* OS and version (eg. `uname -a`):

Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**Comment by violetagg** [comment]
@takaaki7 Unix domain sockets are supported only with the **native** transports: **Epoll** and **KQueue** so this exception is expected as you run with **NIO** transport.

```
 Caused by: java.lang.IllegalArgumentException: Unsupported channel type: DomainSocketChannel
	at reactor.netty.resources.DefaultLoopNIO.getChannel(DefaultLoopNIO.java:50)
```

For the exception below with KQueue, is it possible that you have some mismatch of the Netty binaries?
Reactor Netty 1.0.15 depends on Netty 4.1.72.Final while you add dependency to 4.1.70.Final (io.netty:netty-transport-native-kqueue:4.1.70.Final:osx-x86_64)

```
Method 'void io.netty.channel.unix.Socket.initialize(boolean)' name or signature does not match
  at io.netty.channel.kqueue.Native.registerUnix(Native Method)
  at io.netty.channel.kqueue.Native.access$000(Native.java:56)
  at io.netty.channel.kqueue.Native$1.run(Native.java:81)
  at io.netty.channel.unix.Unix.registerInternal(Unix.java:57)
```

**Comment by violetagg** [comment]
I think that your **netty-transport-native-unix-common** is a newer version as the stack trace above has a change made in 4.1.71.Final

https://github.com/netty/netty/commit/559c08555eea54582b24c7c52152f75b6dbb4301#diff-30da94238a2601ebdf45abc16f437ed9f8568d3d351aaba08dc79b814694e286

**Comment by takaaki7** [comment]
Using 4.1.72.Final solves the problem!

With current settings(4.1.70.Final:osx-x86_64) `./gradle dependencies` shows only 4.1.70 and 4.1.72. I don't know why the stacktrace was different...

But anyway uds is now working. Thanks!

**Comment by violetagg** [comment]
Nice you found the issue!
