### ISSUE TITLE
java.util.NoSuchElementException: Context does not contain key: callereventloop

### ISSUE THREAD

**Issue by mhmdsalem1993** [reactor/reactor-netty#2113]
I’ve got this error when using netty HttpClient with Spring WebClient
java.util.NoSuchElementException: Context does not contain key: callereventloop

## Expected Behavior
Not to have this error
## Actual Behavior
we got it multiple times

## Steps to Reproduce

httpClient creation part and this exception is logged with the method below

```java
HttpClient.create(reactorResourceFactory.connectionProvider)
                                    .runOn(reactorResourceFactory.loopResources)
                                    .wiretap(
                                        "reactor.netty.http.client.HttpClient",
                                        LogLevel.DEBUG,
                                        AdvancedByteBufFormat.TEXTUAL
                                    ).apply {
                                        if (client.followRedirect != null) {
                                            followRedirect(client.followRedirect!!)
                                        }
                                    }.doOnRequestError { t, u ->
                                        log.error(
                                            "Request Error Occurred when calling ${entry.key} Service with Url:${t.uri()}",
                                            u
                                        )
                                    }
```

Propgated to be wrapped by this exception too

```java
org.springframework.web.reactive.function.client.WebClientRequestException
```

This is how i use the webClient
```java
webClient
            .get()
            .uri {
                it.path("/v2/objects/")
                    .queryParam("id", id)
                    .queryParam("country", countryCode.code)
                    .queryParam("type", type)
                    .apply {
                        if (filterIds.isNotEmpty()) {
                            queryParam("filterIds", filterIds.joinToString(separator = ","))
                        }
                    }.build()
            }
            .setAcceptLanguageHeader(locale)
            .setRequestTimeout(requestTimeout)
            .retrieve()
            .handleErrors(GROUP_NAME, locale)
            .bodyToFlux(Response::class.java)
            .mapParsingErrors("Error parsing response")
            .awaitFirstOrElse {
                throw ResourceNotFoundException("Empty response")
            }
```

Stacktrace:
```
java.util.NoSuchElementException: Context does not contain key: callereventloop
    at reactor.util.context.Context2.get(Context2.java:87)
    at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator.lambda$connectChannel$0(DefaultPooledConnectionProvider.java:498)
    at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
    at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
    at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
    at reactor.core.publisher.Mono.subscribe(Mono.java:4371)
    at reactor.core.publisher.Mono.subscribe(Mono.java:4307)
    at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:407)
    at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.pendingOffer(SimpleDequePool.java:558)
    at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:268)
    at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:432)
    at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onSubscribe(DefaultPooledConnectionProvider.java:195)
    at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:676)
    at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.run(DefaultPooledConnectionProvider.java:223)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

* Reactor version(s) used: 1.0.16
* Spring Boot version: 2.5.10
* JVM version: 11

**Comment by houlang** [comment]
Netty core version: v1.0.17
I encountered this problem in the production environment. 
My solution is to add the configuration to the gateway.
```yml
spring:
  cloud:
    gateway:
      httpclient:
        pool:
          maxIdleTime: 10000  #If needed, it can be changed.
```
I hope it can help others.

**Comment by houlang** [comment]
Netty core version: v1.0.17  
I encountered this problem in the production environment.  
My solution is to add the configuration to the gateway.

```yaml
spring:
  cloud:
    gateway:
      httpclient:
        pool:
          maxLifeTime: 8  #If needed, it can be changed.
```

I hope it can help others.

**Comment by violetagg** [comment]
@houlang This issue is fixed and you and other users would better update Reactor Netty version.
