### ISSUE TITLE
proxy configs failing to send request 

### ISSUE THREAD

**Issue by hammafataka** [reactor/reactor-netty#2166]
## Expected Behavior

should configure proxy with ssl and send request via proxy,
should not use UDP since i am setting proxy type to HTTP and should send via TCP

## Actual Behavior

Throws exception for not being able to validate Dns hostname after trying send via UDP

```
Caused by: java.net.UnknownHostException: Failed to resolve 'ToSendUrl' after 2 queries
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
        at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:240)
        at io.netty.resolver.dns.DnsQueryContext.onQueryWriteCompletion(DnsQueryContext.java:177)
        at io.netty.resolver.dns.DnsQueryContext.access$200(DnsQueryContext.java:42)
        at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:169)
        at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:166)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
        at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:723)
        at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:308)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:288)
        at io.netty.channel.epoll.EpollDatagramChannel.doWrite(EpollDatagramChannel.java:355)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
        at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
        at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
        at io.netty.resolver.dns.DnsNameResolver.flushQueries(DnsNameResolver.java:1257)
        at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:361)
        at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:215)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1158)
        at io.netty.resolver.dns.DnsNameResolver.access$500(DnsNameResolver.java:91)
        at io.netty.resolver.dns.DnsNameResolver$7.run(DnsNameResolver.java:1137)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java

caused by: io.netty.resolver.dns.DnsNameResolverException: [/2001:4860:4860:0:0:0:0:8844:53] failed to send a query via UDP (no stack trace available)
Caused by: io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Network is unreachable
```

## Steps to Reproduce

```java
public WebClient buildWebClient() {
  final var httpClientBuilder = HttpClient
                    .create();

  final var store = KeyStore.getInstance("JKS");
                stream = new FileInputStream("trustStorePath");
                store.load(stream,"trustStorePass".toCharArray());
                final var trustManagerFactory = TrustManagerFactory
                        .getInstance(TrustManagerFactory.getDefaultAlgorithm());

  trustManagerFactory.init(store);
  final var sslContext = SslContextBuilder
                        .forClient()
                        .protocols("TLS")
                        .trustManager(trustManagerFactory)
                        .build();

  httpClientBuilder
                        .secure(ssl -> ssl.sslContext(sslContext)
                                .handshakeTimeout(Duration.ofSeconds(10))
                                .build()
                        );
   httpClientBuilder.resolver(DefaultAddressResolverGroup.INSTANCE);
                httpClientBuilder.proxy(
                        proxy -> proxy.type(ProxyProvider.Proxy.HTTP)
                                .host("proxy.com")
                                .port(3232)
                                .connectTimeoutMillis(TimeUnit.SECONDS.toMillis(10))
                                .build()
                );
   ReactorClientHttpConnector clientHttpConnector = new ReactorClientHttpConnector(httpClientBuilder);
   return WebClient.builder()
                    .clientConnector(clientHttpConnector)
                    .build();
}

public void test(){
              buildWebClient()
                    .post()
                    .uri("url")
                    .body(Body)
                    .headers(httpHeaders -> httpHeaders.setBasicAuth(username,password))
                    .retrieve()
                    .toEntity(Response.class);
}
```

## Possible Solution

Disabling UDP checker, or changing proxy type to SOCKET4

## Your Environment

* Reactor version(s) used (io.projectreactor.netty:reactor-netty-core:1.0.16,   io.projectreactor.netty:reactor-netty-http: 1.0.16):
* JVM version (`java -version 8`):
* OS and version (MacOS Monteray 12.3.1):

**Comment by violetagg** [comment]
@hammafataka Can you tell us what do you expect from this setting?

`httpClientBuilder.resolver(DefaultAddressResolverGroup.INSTANCE);`

**Comment by hammafataka** [comment]
@violetagg  it was for dnsName Resolver, but it was behaving the same even without setting AddressResolver

**Comment by violetagg** [comment]
@hammafataka `HttpClient` is immutable so you need to change the example to this:

```
final var httpClientBuilder =
	HttpClient.create()
		.secure(ssl -> ssl.sslContext(Http11SslContextSpec.forClient()
						.configure(builder -> builder.trustManager(InsecureTrustManagerFactory.INSTANCE)))
				.handshakeTimeout(Duration.ofSeconds(10))
				.build())
		.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP)
				.host("proxy.com")
				.port(3232)
				.connectTimeoutMillis(TimeUnit.SECONDS.toMillis(10))
				.build());
```

**Comment by hammafataka** [comment]
hello @violetagg, there is one thing that is not clear for me, i am still getting ` java.nio.channels.UnresolvedAddressException: null` it causes when sslhandler tries to connect because address is unresolved, i digged up and i can see from InetSocketAddress.java the address is unresolved in another word addr=null;
 
any reason why it causes it. i am attaching log with it as well 



`org.springframework.web.reactive.function.client.WebClientRequestException: nested exception is java.nio.channels.UnresolvedAddressException
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to POST  URL_OF_SERVER  [DefaultWebClient]
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:307)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:158)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:477)
		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:431)
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:542)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
		at reactor.core.publisher.Operators.error(Operators.java:198)
		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:534)
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:488)
		at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:223)
		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
		at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
		at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
		at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
		at reactor.netty.transport.TransportConnector.lambda$doConnect$8(TransportConnector.java:205)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
		at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:750)
Caused by: java.nio.channels.UnresolvedAddressException: null
	at io.netty.channel.kqueue.AbstractKQueueChannel.checkResolvable(AbstractKQueueChannel.java:254)
	at io.netty.channel.kqueue.AbstractKQueueChannel.doConnect(AbstractKQueueChannel.java:690)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.connect(AbstractKQueueChannel.java:550)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.handler.ssl.SslHandler.connect(SslHandler.java:713)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:495)
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:51)
	at io.netty.channel.CombinedChannelDuplexHandler.connect(CombinedChannelDuplexHandler.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:457)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:942)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:229)
	at reactor.netty.transport.TransportConnector.lambda$doConnect$8(TransportConnector.java:198)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)`

**Comment by violetagg** [comment]
@hammafataka can you provide some reproducible example?

**Comment by hammafataka** [comment]
@violetagg reproducible example is below 

 `public WebClient buildWebClient() {
  final var httpClientBuilder = HttpClient
                    .create();

  final var store = KeyStore.getInstance("JKS");
                stream = new FileInputStream("trustStorePath");
                store.load(stream,"trustStorePass".toCharArray());
                final var trustManagerFactory = TrustManagerFactory
                        .getInstance(TrustManagerFactory.getDefaultAlgorithm());

  trustManagerFactory.init(store);
  final var sslContext = SslContextBuilder
                        .forClient()
                        .protocols("TLSv1.2", "TLSv1.3")
                        .trustManager(trustManagerFactory)
                        .build();

  httpClientBuilder
                        .secure(ssl -> ssl.sslContext(sslContext)
                                .handshakeTimeout(Duration.ofSeconds(10))
                                .build()
                        );
   httpClientBuilder.resolver(NoopAddressResolverGroup.INSTANCE);
   ReactorClientHttpConnector clientHttpConnector = new ReactorClientHttpConnector(httpClientBuilder);
   return WebClient.builder()
                    .clientConnector(clientHttpConnector)
                    .build();
}

public void test(){
              buildWebClient()
                    .post()
                    .uri("url")
                    .body(Body)
                    .headers(httpHeaders -> httpHeaders.setBasicAuth(username,password))
                    .retrieve()
                    .toEntity(Response.class);
}`

i am getting it when it is sending with ssl, when it is not using ssl then it goes thro, i suspect i am missing some config with setting ssl

**Comment by violetagg** [comment]
@hammafataka One thing that I'm noticing in the example above is that you configure the http client but you never actually use the configurations. `HttpClient` is immutable so when you have for example

```
httpClientBuilder
                        .secure(ssl -> ssl.sslContext(sslContext)
                                .handshakeTimeout(Duration.ofSeconds(10))
                                .build()
                        );
```

it should be like this

```
httpClientBuilder = httpClientBuilder
                        .secure(ssl -> ssl.sslContext(sslContext)
                                .handshakeTimeout(Duration.ofSeconds(10))
                                .build()
                        );
```


so the whole example should be like this

```
public WebClient buildWebClient() {
  final var store = KeyStore.getInstance("JKS");
                stream = new FileInputStream("trustStorePath");
                store.load(stream,"trustStorePass".toCharArray());
                final var trustManagerFactory = TrustManagerFactory
                        .getInstance(TrustManagerFactory.getDefaultAlgorithm());

  trustManagerFactory.init(store);
  final var sslContext = SslContextBuilder
                        .forClient()
                        .protocols("TLSv1.2", "TLSv1.3")
                        .trustManager(trustManagerFactory)
                        .build();

  final var httpClientBuilder = HttpClient
                    .create()
                    .secure(ssl -> ssl.sslContext(sslContext)
                                .handshakeTimeout(Duration.ofSeconds(10))
                                .build()
                    )
                   .resolver(NoopAddressResolverGroup.INSTANCE);

   ReactorClientHttpConnector clientHttpConnector = new ReactorClientHttpConnector(httpClientBuilder);
   return WebClient.builder()
                    .clientConnector(clientHttpConnector)
                    .build();
}

public void test(){
              buildWebClient()
                    .post()
                    .uri("url")
                    .body(Body)
                    .headers(httpHeaders -> httpHeaders.setBasicAuth(username,password))
                    .retrieve()
                    .toEntity(Response.class);
}
```

**Comment by hammafataka** [comment]
Hello @violetagg , sorry for not keeping code updated, yes i am using it as immutable, and still getting the same
