### ISSUE TITLE
Https proxy timeout

### ISSUE THREAD

**Issue by Jean-Baptiste-Avril** [reactor/reactor-netty#2173]
### Expected Behavior
Support https proxy

## Expected Behavior
Getting response from http://ip.quotaguard.com/ with https proxy

Exemple : 

```
{
ip: "85.76.98.251"
}
```
## Actual Behavior
I have 2 proxies:
  - https proxy : https://eedsi90hfd7k0f:xs2v7pkzo9malgzvp476i6by0sqgnq@eu-west-shield-01.quotaguard.com:9294
  - http proxy : http://jt8bbqzxyct6b1:ve8da3lcwsfyy85mcjskvzr6so9cm@eu-west-static-05.quotaguard.com:9293

With curl, both proxies work:
  - Https : curl -x https://eedsi90hfd7k0f:xs2v7pkzo9malgzvp476i6by0sqgnq@eu-west-shield-01.quotaguard.com:9294 -L ip.quotaguard.com
  - Http : curl -x http://jt8bbqzxyct6b1:ve8da3lcwsfyy85mcjskvzr6so9cm@eu-west-static-05.quotaguard.com:9293 -L ip.quotaguard.com

**Curl :**

![image](https://user-images.githubusercontent.com/71263792/166152092-dd99b149-ba36-41fb-a6c7-1d3333bd0be6.png)

In Java only http proxy works :

![image](https://user-images.githubusercontent.com/71263792/166152347-9de8e48f-3dc7-4872-b5b4-6203a9c36fb6.png)

The https proxy results in a timeout :

```
2022-05-01 16:43:09.159  WARN 72564 --- [ctor-http-nio-2] r.netty.http.client.HttpClientConnect    : [3e579072, L:/192.168.50.127:53435 ! R:eu-west-shield-01.quotaguard.com/18.200.38.238:9294] The connection observed an error

io.netty.handler.proxy.ProxyConnectException: http, basic, eu-west-shield-01.quotaguard.com/18.200.38.238:9294 => ip.quotaguard.com/<unresolved>:80, timeout
	at io.netty.handler.proxy.ProxyHandler$2.run(ProxyHandler.java:198) ~[netty-handler-proxy-4.1.76.Final.jar:4.1.76.Final]
ProxyHandler.java:198
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.76.Final.jar:4.1.76.Final]
PromiseTask.java:98
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.76.Final.jar:4.1.76.Final]
ScheduledFutureTask.java:170
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.76.Final.jar:4.1.76.Final]
AbstractEventExecutor.java:164
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.76.Final.jar:4.1.76.Final]
SingleThreadEventExecutor.java:469
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
NioEventLoop.java:503
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.76.Final.jar:4.1.76.Final]
SingleThreadEventExecutor.java:986
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.76.Final.jar:4.1.76.Final]
ThreadExecutorMap.java:74
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.76.Final.jar:4.1.76.Final]
FastThreadLocalRunnable.java:30
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

## Steps to Reproduce

https://github.com/Jean-Baptiste-Avril/simple-webclient
```java
String apiUrl = "http://ip.quotaguard.com/";

String quotaGuardUrlHttps = "https://eedsi90hfd7k0f:xs2v7pkzo9malgzvp476i6by0sqgnq@eu-west-shield-01.quotaguard.com:9294";
String quotaGuardUrlHttp = "http://jt8bbqzxyct6b1:ve8da3lcwsfyy85mcjskvzr6so9cm@eu-west-static-05.quotaguard.com:9293";

URL proxyUrl = new URL(quotaGuardUrlHttps); // Change to quotaGuardUrlHttps (fail) or quotaGuardUrlHttp
											// (success)

String userInfo = proxyUrl.getUserInfo();
String proxyUser = userInfo.substring(0, userInfo.indexOf(':'));
String proxyPassword = userInfo.substring(userInfo.indexOf(':') + 1);

HttpClient httpClient = HttpClient.create()
		.secure()
		.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).host(proxyUrl.getHost()).port(proxyUrl.getPort())
				.username(proxyUser).password(passwd -> proxyPassword));

WebClient webClient = WebClient.builder()
		.baseUrl(apiUrl)
		.clientConnector(new ReactorClientHttpConnector(httpClient))
		.build();

LOG.info("GET http://ip.quotaguard.com/");
RequestHeadersSpec<?> request = webClient.get().uri("");
String response = request.retrieve().bodyToMono(String.class).retry(2).block();
LOG.info(response);
```
With this line, the code works : `URL proxyUrl = new URL(quotaGuardUrlHttps);`

But it crashes with this : `URL proxyUrl = new URL(quotaGuardUrlHttp);`

## Your Environment

 - Windows 10
 - Java 17
 - Spring boot 2.6.7

Dependencies (https://github.com/Jean-Baptiste-Avril/simple-webclient/blob/main/pom.xml) : 
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>io.projectreactor</groupId>
	<artifactId>reactor-test</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-devtools</artifactId>
	<scope>runtime</scope>
</dependency>
```

**Comment by violetagg** [comment]
@Jean-Baptiste-Avril Can you try this:

```
curl --proxytunnel https://eedsi90hfd7k0f:xs2v7pkzo9malgzvp476i6by0sqgnq@eu-west-shield-01.quotaguard.com:9294/ -L ip.quotaguard.com
```

```
curl --proxytunnel http://jt8bbqzxyct6b1:ve8da3lcwsfyy85mcjskvzr6so9cm@eu-west-static-05.quotaguard.com:9293/ -L ip.quotaguard.com
```

Please check this FAQ
https://projectreactor.io/docs/netty/release/reference/index.html#faq.proxy-connect-method

**Comment by Jean-Baptiste-Avril** [comment]
@violetagg 
Thank you for your reply,

Here is the return:

![image](https://user-images.githubusercontent.com/71263792/166193276-c495c90d-a389-44c9-a4d8-56a42a2a305a.png)

I'll take a closer look at your link.

**Comment by Jean-Baptiste-Avril** [comment]
@violetagg 

If I understand correctly, Netty's HTTP proxy uses the CONNECT method in order to establish a tunnel to the specified proxy, regardless of the http or https scheme used.

But my proxy does not support this method and therefore does not allow the connection to be established.

Would that be a possible explanation ?

**Comment by violetagg** [comment]
@Jean-Baptiste-Avril yes I think so, as you can see when you use `curl --proxytunnel` the requests also fail

**Comment by Jean-Baptiste-Avril** [comment]
@violetagg 

Thank you for your answer, I close the ticket.
