### ISSUE TITLE
Memory Leaks in web application

### ISSUE THREAD

**Issue by jvidal-dev** [reactor/reactor-netty#2196]
Hi all,

I am getting memory leaks when using Reactor Netty HttpClient. We detected that if the application is deployed as a war file to Tomcat, and when we need to upgrade it we just stop it from the Manager app, and then Start it. Classes are not garbage collected properly and memory usage continues to grow every time the process is repeated.

For now I am seeing 2 errors:

```java
6-May-2022 17:22:24.886 WARNING [http-nio-8080-exec-9] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [demo] appears to have started a thread named [test-loop-resources-nio-6] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
```

That line appears many times, it seems like one per thread.

Other error I saw is 

```bash
ClassLoaderLeakPreventorListener: com.jamfsoftware.jss.server.JssClassLoaderLeakPreventorListener shutting down context by removing known leaks (CL: 0x29b902b2)
16-May-2022 13:02:13.568 WARNING [http-nio-8080-exec-8] se.jiderhamn.classloader.leak.prevention.JULLogger.warn reactor.netty.http.HttpResources.shutdown()
        java.lang.NoSuchMethodException: reactor.netty.http.HttpResources.shutdown()
                at java.base/java.lang.Class.getDeclaredMethod(Class.java:2480)
                at se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventor.findMethod(ClassLoaderLeakPreventor.java:528)
                at se.jiderhamn.classloader.leak.prevention.cleanup.ReactorNettyHttpResourcesCleanUp.cleanUp(ReactorNettyHttpResourcesCleanUp.java:30)
                at se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventor.runCleanUps(ClassLoaderLeakPreventor.java:246)
                at se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener.contextDestroyed(ClassLoaderLeakPreventorListener.java:242)
                at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4811)
                at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5467)
                at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
                at org.apache.catalina.manager.ManagerServlet.stop(ManagerServlet.java:1458)
```

### Implementation
I have a builder patter to create the http client:

```java
public WebClient build() {
		webClientBuilder.clientConnector(new ReactorClientHttpConnector(resourceFactory(), client -> httpClient));
		return webClientBuilder.build();
	}

	public ReactorResourceFactory resourceFactory() {
		ReactorResourceFactory factory = new ReactorResourceFactory();
		factory.setConnectionProvider(ConnectionProvider.builder("test-connection-provider").build());
		factory.setLoopResources(LoopResources.create("test-loop-resources"));
		factory.setUseGlobalResources(false);
		return factory;
	}
```

If I don't set the Connection Provider I get an error saying none has been initialized. The same happens with the Loop Resources.

### Steps to reproduce

Just create a simple web application that creates the http client with a code similar to the above. Generate the war file and deploy to tomcat. Use the app, stop it manually from the Manager and you will see error logs in the `catalina.out` log file.

* Reactor version(s) used: io.projectreactor.netty:reactor-netty:1.0.2
* JVM version (`java -version`): Java 12.0.2
* OS and version (eg. `uname -a`): macOS Monterrey 12.3.1
* Followed these documentation: https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-client-builder-reactor-resources

---

All in all, anything can help. I didn't find much code to handle Netty resources correctly so maybe I messed something up there. Maybe I am missing something.

**Comment by violetagg** [comment]
@jvidal-dev There is no method `reactor.netty.http.HttpResources.shutdown()` - check javadoc https://projectreactor.io/docs/netty/release/api/reactor/netty/http/HttpResources.html
One should invoke `reactor.netty.http.HttpResources.disposeLoopsAndConnections()`

Please contact the project providing the functionality below and discuss this with the project

```
java.lang.NoSuchMethodException: reactor.netty.http.HttpResources.shutdown()
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2480)
        at se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventor.findMethod(ClassLoaderLeakPreventor.java:528)
        at se.jiderhamn.classloader.leak.prevention.cleanup.ReactorNettyHttpResourcesCleanUp.cleanUp(ReactorNettyHttpResourcesCleanUp.java:30)
        at se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventor.runCleanUps(ClassLoaderLeakPreventor.java:246)
        at se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventorListener.contextDestroyed(ClassLoaderLeakPreventorListener.java:242)
```

**Comment by jvidal-dev** [comment]
Hi Violeta, thanks for getting back to me so soon.

I know the method is not present and that `reactor.netty.http.HttpResources.disposeLoopsAndConnections` should be used instead.

The problem is that this is done automatically by Spring. We were following this documentation https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-client-builder-reactor-resources where I understood that if we implemented the `ReactorResourceFactory` Spring should release all resources when the context is destroyed. This is not happening and instead it looks like it's calling the `shutdown` method automatically even though it's not there.

Do you have any suggestion on implementing this with Spring? Do you have any suggestion on preventing memory leaks with the HttpClient not being released from memory?

Thanks!

**Comment by violetagg** [comment]
@jvidal-dev I cannot comment anything about Spring, however I just checked their implementation and they call the correct method
https://github.com/spring-projects/spring-framework/blob/874077d16ec126ca19d4b9fbb4157cfdc4eac382/spring-web/src/main/java/org/springframework/http/client/reactive/ReactorResourceFactory.java#L222
