### ISSUE TITLE
Let the `NettyInbound.onReadIdle` and `NettyOutbound.onWriteIdle` replace existing idle handlers

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#22]
````
java.lang.IllegalArgumentException: Duplicate handler name: onChannelReadIdle
        at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1062)
        at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:293)
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:250)
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240)
        at reactor.ipc.netty.channel.ChannelOperations.addHandler(ChannelOperations.java:141)
        at reactor.ipc.netty.channel.ChannelOperations.addHandler(ChannelOperations.java:64)
        at reactor.ipc.netty.NettyInbound.onReadIdle(NettyInbound.java:66)
        at org.springframework.messaging.tcp.reactor.ReactorNettyTcpConnection.onReadInactivity(ReactorNettyTcpConnection.java:67)
        at org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler$StompConnectionHandler.initHeartbeats(StompBrokerRelayMessageHandler.java:706)
...
````

For context, on a TCP connection to a STOMP broker we use heartbeats to keep the connection from hanging. However heartbeats have to be negotiated first through an exchange of CONNECT and CONNECTED frames and so there is a possibility to hang before the heartbeats have started leading to a [resource leak](https://jira.spring.io/browse/SPR-14266). This is why we first register one task first check if we haven't received CONNECTED and then a heartbeat task after.

This should not cause `onChannelReadIdle` to fail. One option would be to replace the OnChannelReadIdle handler first (my current workaround) or the API could provide a clear choice whether the new task should be added or used as a replacement.

**Comment by simonbasle** [comment]
72f4cbd doesn't completely fix this (as subsequent invocations of `onReadIdle` API went from failing to silently being discarded)...  It makes the workaround shorter, though, with the addition of `removeHandler`:

```java
public void onReadInactivity(Runnable runnable, long inactivityDuration) {

	// TODO: workaround for https://github.com/reactor/reactor-netty/issues/22
	this.inbound.removeHandler(NettyPipeline.OnChannelReadIdle);

	this.inbound.onReadIdle(inactivityDuration, runnable);
}
```

**Comment by rstoyanchev** [comment]
I'm fine with suggested workaround but silently ignoring the second invocation doesn't seem fine. I would rather see an IllegalStateException pointing to the need to explicitly remove the existing handler first.
