### ISSUE TITLE
Unexpected NPE on https post call

### ISSUE THREAD

**Issue by sergiords** [reactor/reactor-netty#224]
### Expected behavior
Following http call returns a response with status `200` using `cURL`:
```sh
curl -XPOST -d '{}' "https://api.weixin.qq.com/cgi-bin/component/api_authorizer_token?component_access_token=xxxxx"
{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest hint: [X0k_FA0762e606]"}
```

### Actual behavior
When using reactor-netty client (with `WebClient` from Spring) the client hangs for a few seconds (to a few minutes) before raising the following exception:
```sh
2017-11-21 23:25:23.944 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0x5666f0e5, L:/192.168.1.43:52486 - R:api.weixin.qq.com/203.205.147.177:443] FLUSH
2017-11-21 23:25:24.199 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0x5666f0e5, L:/192.168.1.43:52486 - R:api.weixin.qq.com/203.205.147.177:443] READ COMPLETE
2017-11-21 23:25:24.270 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0x5666f0e5, L:/192.168.1.43:52486 - R:api.weixin.qq.com/203.205.147.177:443] READ COMPLETE
2017-11-21 23:25:24.702 DEBUG   --- [ctor-http-nio-4] io.netty.handler.ssl.SslHandler          : [id: 0x5666f0e5, L:/192.168.1.43:52486 - R:api.weixin.qq.com/203.205.147.177:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2017-11-21 23:25:24.703 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0x5666f0e5, L:/192.168.1.43:52486 - R:api.weixin.qq.com/203.205.147.177:443] USER_EVENT: SslHandshakeCompletionEvent(SUCCESS)
2017-11-21 23:25:24.705 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0x5666f0e5, L:/192.168.1.43:52486 - R:api.weixin.qq.com/203.205.147.177:443] READ COMPLETE
2017-11-21 23:25:56.626 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0x5666f0e5, L:/192.168.1.43:52486 - R:api.weixin.qq.com/203.205.147.177:443] READ COMPLETE
SLF4J: Failed toString() invocation on an object of type [org.springframework.http.client.reactive.ReactorClientHttpResponse]
Reported exception:
java.lang.NullPointerException
	at org.springframework.http.client.reactive.ReactorClientHttpResponse.getStatusCode(ReactorClientHttpResponse.java:72)
	at org.springframework.http.client.reactive.ReactorClientHttpResponse.toString(ReactorClientHttpResponse.java:96)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:299)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:271)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:233)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:173)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.debug(Logger.java:494)
	at reactor.util.Loggers$Slf4JLogger.debug(Loggers.java:218)
	at reactor.core.publisher.SignalLogger.log(SignalLogger.java:177)
	at reactor.core.publisher.SignalLogger.lambda$onNextCall$2(SignalLogger.java:237)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:177)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:81)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:139)
	at reactor.ipc.netty.channel.PooledClientContextHandler.fireContextActive(PooledClientContextHandler.java:84)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:176)
	at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:342)
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:420)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.codec.http.HttpContentDecoder.channelInactive(HttpContentDecoder.java:205)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:281)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:978)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

Even though stack trace suggests issue is on `org.springframework.http.client.reactive.ReactorClientHttpResponse` side I still think there is an issue on reactor-netty side since same call using `cURL` succeeds and has an HTTP status code 200 which is retrieved by `reactor.ipc.netty.http.client.HttpClientResponse.status().code()`.

### Steps to reproduce
Launch code below:
```java
package com.issue.nettyissue;

import org.springframework.web.reactive.function.client.WebClient;

import static org.springframework.web.reactive.function.BodyInserters.fromObject;

public class ClientIssue {

    public static void main(String[] args) {

        String response = WebClient.create("https://api.weixin.qq.com")
                .post()
                .uri(uriBuilder -> uriBuilder
                        .path("/cgi-bin/component/api_authorizer_token")
                        .queryParam("component_access_token", "xxxxx")
                        .build())
                .body(fromObject("{}"))
                .retrieve()
                .bodyToMono(String.class)
                .block();

        System.out.println(response);

    }
}
```

### Reactor Netty version
io.projectreactor:reactor-bom:Bismuth-BUILD-SNAPSHOT
io.projectreactor.ipc:reactor-netty:0.7.3.BUILD-SNAPSHOT

With `io.projectreactor.ipc:reactor-netty:0.7.1.RELEASE`, the error raised is:
```sh
Exception in thread "main" reactor.core.Exceptions$ReactiveException: java.io.IOException: Connection closed prematurely
	at reactor.core.Exceptions.propagate(Exceptions.java:326)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Mono.block(Mono.java:1161)
	at com.issue.nettyissue.ClientIssue.main(ClientIssue.java:20)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:89)
		... 2 more
Caused by: java.io.IOException: Connection closed prematurely
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundComplete(HttpClientOperations.java:262)
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:425)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:105)
```

With version `0.7.1.RELEASE` this issue might be related to [this other issue](https://github.com/reactor/reactor-netty/issues/221).

### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)
Darwin . 17.2.0 Darwin Kernel Version ... 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

**Comment by sergiords** [comment]
Similar behaviour using raw `reactor.ipc.netty.http.client.HttpClient`.

```java
package com.issue.nettyissue;

import io.netty.handler.codec.http.HttpResponseStatus;
import reactor.core.publisher.Mono;
import reactor.ipc.netty.http.client.HttpClient;
import reactor.ipc.netty.http.client.HttpClientResponse;

public class ClientIssue {

    public static void main(String[] args) {

        HttpResponseStatus status = HttpClient.create()
                .post("https://api.weixin.qq.com/cgi-bin/component/api_authorizer_token?component_access_token=xxxxx",
                        httpClientRequest -> httpClientRequest.sendString(Mono.just("{}")))
                .map(HttpClientResponse::status)
                .block();

        System.out.println(status.code());
    }
}
```
```sh
2017-11-21 23:55:07.560 DEBUG   --- [ctor-http-nio-4] io.netty.handler.ssl.SslHandler          : [id: 0xd5d8f2ea, L:/192.168.1.43:52686 - R:api.weixin.qq.com/103.7.30.34:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2017-11-21 23:55:07.561 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0xd5d8f2ea, L:/192.168.1.43:52686 - R:api.weixin.qq.com/103.7.30.34:443] USER_EVENT: SslHandshakeCompletionEvent(SUCCESS)
2017-11-21 23:55:07.563 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0xd5d8f2ea, L:/192.168.1.43:52686 - R:api.weixin.qq.com/103.7.30.34:443] READ COMPLETE
2017-11-21 23:55:57.498 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0xd5d8f2ea, L:/192.168.1.43:52686 - R:api.weixin.qq.com/103.7.30.34:443] READ COMPLETE
2017-11-21 23:55:57.503 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0xd5d8f2ea, L:/192.168.1.43:52686 ! R:api.weixin.qq.com/103.7.30.34:443] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
2017-11-21 23:55:57.504 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0xd5d8f2ea, L:/192.168.1.43:52686 ! R:api.weixin.qq.com/103.7.30.34:443] INACTIVE
Exception in thread "main" java.lang.NullPointerException: The mapper returned a null value.
	at java.util.Objects.requireNonNull(Objects.java:228)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:81)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:139)
	at reactor.ipc.netty.channel.PooledClientContextHandler.fireContextActive(PooledClientContextHandler.java:84)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:176)
	at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:342)
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:420)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:281)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:978)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:89)
		at reactor.core.publisher.Mono.block(Mono.java:1162)
		at com.issue.nettyissue.ClientIssue.main(ClientIssue.java:16)
2017-11-21 23:55:57.510 DEBUG   --- [ctor-http-nio-4] r.ipc.netty.http.client.HttpClient       : [id: 0xd5d8f2ea, L:/192.168.1.43:52686 ! R:api.weixin.qq.com/103.7.30.34:443] USER_EVENT: [Handler Terminated]
2017-11-21 23:55:57.510 DEBUG   --- [ctor-http-nio-4] r.i.n.channel.ChannelOperationsHandler   : [id: 0xd5d8f2ea, L:/192.168.1.43:52686 ! R:api.weixin.qq.com/103.7.30.34:443] Disposing context reactor.ipc.netty.channel.PooledClientContextHandler@635bc6de
2017-11-21 23:55:57.510 DEBUG   --- [ctor-http-nio-4] r.i.n.c.PooledClientContextHandler       : Releasing channel: [id: 0xd5d8f2ea, L:/192.168.1.43:52686 ! R:api.weixin.qq.com/103.7.30.34:443]
```

**Comment by smaldini** [comment]
@violetagg if you have  a chance to look at this one

**Comment by sergiords** [comment]
Hi,

I do not think the expected behaviour should be `java.io.IOException: Connection closed prematurely`.
When executing the same request with `cURL` I get a `200` status code with a response body.

```bash
curl -d '{}' -si https://api.weixin.qq.com/cgi-bin/component/api_authorizer_token?component_access_token=xxxxx
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json; encoding=utf-8
Date: Wed, 29 Nov 2017 10:43:16 GMT
Content-Length: 109

{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest hint: [fZKoLa0196e514]"}
```

**Comment by violetagg** [comment]
Ok thanks

try disabling transfer encoding and tell us the result
```
HttpResponseStatus status = HttpClient.create()
                .post("https://api.weixin.qq.com/cgi-bin/component/api_authorizer_token?component_access_token=xxxxx",
                        httpClientRequest -> httpClientRequest.chunkedTransfer(false)
                                                              .sendString(Mono.just("{}")))
                .map(HttpClientResponse::status)
                .block();
```

**Comment by sergiords** [comment]
Thanks for the tip.
It works as expected without chunked transfer encoding.

**Comment by smaldini** [comment]
Awesome let us know if you need any more insight, we're working on making this option global as per #94 with the new API, but you shouldn't concern yourself with that if you use Spring WebClient anyway.
