### ISSUE TITLE
First request go slow

### ISSUE THREAD

**Issue by alexroitman** [reactor/reactor-netty#2245]
I develop a java microservice that make a request to an internal microservice(connected on VPN) and another request for generate a token to another microservice.
The first request(complete) take 2/3 second and the next requests takes 1 second or less.

## Expected Behavior

All requests take same time
## Actual Behavior

First request go slow and next request go faster
## Steps to Reproduce

WebClientConfig.java
```java
    @Bean
  private WebClient webClient(ObjectMapper baseObjectMapper) {
    var provider = ConnectionProvider.create("pool", maxConnections);

    var client = HttpClient.create(provider).responseTimeout(Duration.ofMillis(timeout));
    client.warmup().block();
    return WebClient.builder()
        .exchangeStrategies(exchangeStrategies)
        .clientConnector(new ReactorClientHttpConnector(client))
        .build();
  }


Might be linked to [this issue](https://github.com/reactor/reactor-netty/issues/1732)
```

## Your Environment

Using Java 17, macos Monterey, and conected to an internal VPN.
The hosts are resolved via DNS

**Comment by violetagg** [comment]
@alexroitman Please provide logs from the first request.
The issue that you mentioned is specific for Windows and not Mac OS.
Do you observe the problem when you do not use VPN?

**Comment by alexroitman** [comment]
Its importan to mention that in our server we observe the same issue(we are using Kotlin). In the server this logs does not appear
Local logs:
```
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:64) ~[netty-resolver-dns-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60) ~[netty-resolver-dns-4.1.63.Final.jar:4.1.63.Final]
	at reactor.netty.transport.NameResolverProvider.newNameResolverGroup(NameResolverProvider.java:432) ~[reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.tcp.TcpResources.getOrCreateDefaultResolver(TcpResources.java:306) ~[reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.http.HttpResources.getOrCreateDefaultResolver(HttpResources.java:140) ~[reactor-netty-http-1.0.6.jar:1.0.6]
	at reactor.netty.http.client.HttpClientConfig.defaultAddressResolverGroup(HttpClientConfig.java:380) ~[reactor-netty-http-1.0.6.jar:1.0.6]
	at reactor.netty.transport.ClientTransportConfig.resolverInternal(ClientTransportConfig.java:219) ~[reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.netty.http.client.HttpClientConfig.resolverInternal(HttpClientConfig.java:434) ~[reactor-netty-http-1.0.6.jar:1.0.6]
	at reactor.netty.transport.ClientTransport.lambda$warmup$3(ClientTransport.java:335) ~[reactor-netty-core-1.0.6.jar:1.0.6]
	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49) ~[reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150) ~[reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:160) ~[reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:99) ~[reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150) ~[reactor-core-3.4.5.jar:3.4.5]
	at reactor.core.publisher.Mono.block(Mono.java:1702) ~[reactor-core-3.4.5.jar:3.4.5]
	at la.pomelo.enduserauthenticator.client.WebClientConfig.getWebClient(WebClientConfig.java:57) ~[main/:na]
	at la.pomelo.enduserauthenticator.client.WebClientConfig.authWebClient(WebClientConfig.java:40) ~[main/:na]
	at la.pomelo.enduserauthenticator.client.WebClientConfig$$EnhancerBySpringCGLIB$$f755a128.CGLIB$authWebClient$1(<generated>) ~[main/:na]
	at la.pomelo.enduserauthenticator.client.WebClientConfig$$EnhancerBySpringCGLIB$$f755a128$$FastClassBySpringCGLIB$$781c57c.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.6.jar:5.3.6]
	at la.pomelo.enduserauthenticator.client.WebClientConfig$$EnhancerBySpringCGLIB$$f755a128.authWebClient(<generated>) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.5.jar:2.4.5]
	at la.pomelo.enduserauthenticator.EndUserAuthenticatorApplicationKt.main(EndUserAuthenticatorApplication.kt:16) ~[main/:na]
Caused by: java.lang.UnsatisfiedLinkError: 'io.netty.resolver.dns.macos.DnsResolver[] io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.resolvers()'
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.resolvers(Native Method) ~[netty-resolver-dns-native-macos-4.1.63.Final-osx-x86_64.jar:4.1.63.Final]
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.retrieveCurrentMappings(MacOSDnsServerAddressStreamProvider.java:107) ~[netty-resolver-dns-native-macos-4.1.63.Final-osx-x86_64.jar:4.1.63.Final]
	at io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.<init>(MacOSDnsServerAddressStreamProvider.java:103) ~[netty-resolver-dns-native-macos-4.1.63.Final-osx-x86_64.jar:4.1.63.Final]
	... 67 common frames omitted
```

**Comment by violetagg** [comment]
@alexroitman What is your Mac OS chip architecture?

**Comment by alexroitman** [comment]
is an Apple M1. Its important that as i said, in the server takes a lot time too.

**Comment by violetagg** [comment]
@alexroitman You have to upgrade your component versions and add a dependency to `netty-resolver-dns-native-macos` with classifier `osx-aarch_64` see this one https://github.com/netty/netty/issues/11693#issuecomment-923760401

**Comment by violetagg** [comment]
@alexroitman Were you able to test with the artifact that I mentioned in my previous comment?

**Comment by violetagg** [comment]
@alexroitman I'm closing this issue. We can reopen it if it is needed.
