### ISSUE TITLE
Issue with Spring Webclient 5: Executor not accepting a task

### ISSUE THREAD

**Issue by pavanpkp33** [reactor/reactor-netty#2293]
I'm running a Spring webflux app which makes http calls to another service. Under high load (atleast this is when I see these errors), http call from webclient 5 to another service fails with ` java.lang.IllegalStateException: executor not accepting a task` .

What could be the reason for this? Here's my HTTP call implementation.

```
public Mono<Context> doHttp(WebClient webClient, WBConfig webClientConfiguration, String data, Context ctx) {
     return getWebclient(webClient, webClientConfiguration, data, ctx)
        .headers(httpHeaders -> logHeadersAndPayload(ctx, data, httpHeaders))
        .retrieve()
        .bodyToMono(Object.class)
        .publishOn(SchedulerHelper.getSharedPool())
        .onErrorResume(getErrorHandleFunction(webClientConfiguration, ctx, taskName))
        .retryWhen(buildRetrySpec(webClientConfiguration))
        .flatMap(getResponseToContextMonoFunction(ctx, taskName, startTime));
}
```

SchedulerHelper class returns the following scheduler with configuration. Please note that this is shared app wise. This is created when the app boots up.
```
Schedulers.newBoundedElastic(100, Integer.MAX_VALUE, new ThreadFactoryBuilder().setNameFormat("http-threads").build(), 60)
```

I do not get any other information in the stack trace exception thatI have posted this on SO as well. 
@simonbasle  anything that we need to configure?

**Comment by simonbasle** [comment]
please provide the stack trace. you're mentioning an SO question but no link...

**Comment by pavanpkp33** [comment]
@simonbasle  - Here's the SO link. It's a copy of the same https://stackoverflow.com/questions/72581196/issue-with-spring-webclient-5-executor-not-accepting-a-task

Im finding it hard to get the stack trace since it is happening in production. I'm unable to replicate in my local and from PROD, this is what I get as an error.

**Comment by violetagg** [comment]
@simonbasle @pavanpkp33 I don't see how this is related to Reactor Netty project.

**Comment by simonbasle** [comment]
@pavanpkp33 having looked for that error message, it seems that Netty `AddressResolverGroup` is the one throwing it. I don't think this has anything to do with the `Scheduler` setup in your reactive chain. It sounds clear the activity spike is indeed triggering the issue though.

@violetagg I don't think we're doing any specific setup of that `AddressResolverGroup`'s `executor`. Maybe you have an idea how that underlying executor might get shut down.

In any case, @pavanpkp33 I would try to gather more information like stacktraces or events that occur around the issue, with that hypothesis in mind that this is somehow related to address resolution.
In parallel, I would raise this issue with the Netty team directly.

Closing as this doesn't seem directly related to Reactor (or Spring for that mater)

**Comment by violetagg** [comment]
@pavanpkp33 We need either some reproducible example or at least the stack trace otherwise it will be very hard to find what might be the issue only based on the Exception message.

**Comment by pavanpkp33** [comment]
@violetagg - Im trying to push debug level code to my PROD instances. It may take some time for next rollout but i will keep you posted.

**Comment by violetagg** [comment]
@pavanpkp33 I'm closing this one. We can reopen it when there is more information.

**Comment by tomekkra** [comment]
We've just came accross the same issue, here is our stacktrace:

```
org.springframework.web.reactive.function.client.WebClientRequestException: executor not accepting a task; nested exception is java.lang.IllegalStateException: executor not accepting a task
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Request to POST https://xxxxxxxxxx [DefaultWebClient]
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:537)
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:343)
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:308)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:158)
		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475)
		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:431)
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:548)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
		at reactor.core.publisher.Operators.error(Operators.java:198)
		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.Operators.error(Operators.java:198)
		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
		at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:596)
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:516)
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:394)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: executor not accepting a task
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:61)
	at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:278)
	at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:127)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:596)
	at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:516)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:394)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by zpaimon** [comment]
We've just come accross the same issue

> We've just come accross the same issue, here is our stacktrace:
> 
> ```
> org.springframework.web.reactive.function.client.WebClientRequestException: executor not accepting a task; nested exception is java.lang.IllegalStateException: executor not accepting a task
> 	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
> 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
> Error has been observed at the following site(s):
> 	*__checkpoint ? Request to POST https://xxxxxxxxxx [DefaultWebClient]
> Original Stack Trace:
> 		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
> 		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
> 		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
> 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
> 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
> 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
> 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
> 		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
> 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
> 		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
> 		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
> 		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
> 		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
> 		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
> 		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:537)
> 		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:343)
> 		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
> 		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
> 		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
> 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
> 		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:308)
> 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
> 		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:158)
> 		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475)
> 		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:431)
> 		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
> 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
> 		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:548)
> 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
> 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
> 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
> 		at reactor.core.publisher.Operators.error(Operators.java:198)
> 		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
> 		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
> 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
> 		at reactor.core.publisher.Operators.error(Operators.java:198)
> 		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
> 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
> 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
> 		at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:596)
> 		at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:516)
> 		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
> 		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
> 		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
> 		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:394)
> 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 		at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.lang.IllegalStateException: executor not accepting a task
> 	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:61)
> 	at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:278)
> 	at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:127)
> 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
> 	at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:596)
> 	at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:516)
> 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:394)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> ```

I haven the same problem!

**Comment by fmignone-appdirect** [comment]
Hi everyone! I got the same issue on my app, if you have discovered something it would be really helpful! Thanks!

**Comment by pavanpkp33** [comment]
@fmignone-appdirect  - One thing that i noticed in our org was that kubernetes issued a kill sig because health probes were failing due to timeouts and executors were shutting down gracefully. That is when we would experience these errors. The way we indirectly fixed this is by fixing the pod health check issue and stop kubernetes  from sending kill sigs. we have not seen that error since.

**Comment by Aggregationobsessed867** [comment]
@simonbasle https://stackdev.space/questions/run-mono-concurrently
