### ISSUE TITLE
407 Proxy Authentication Required should not trigger warning log

### ISSUE THREAD

**Issue by nandorsoma** [reactor/reactor-netty#2300]
When netty attempts to reach a resource through a proxy which requires authentication, initially it sends a request without authentication and then if it's needed an AuthorizationChallengeHandler will do the authentication. The problem is that between the first request and the authentication challenge handling HttpClientConnect logs a warning message which is misleading in that situation because it is part of the normal flow and doesn't necessarily mean that the authentication is failed or will fail. Therefore I ask you that is it possible to create a specific log message with INFO or TRACE level when the exception cause is HttpProxyConnectException?

Code part where the log happens:
https://github.com/reactor/reactor-netty/blob/21b300a21d2e5b6b5bcd3a3418a2e468b5c83e25/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L398

Example warning log with the exception:
```
[reactor-http-kqueue-2] WARN reactor.netty.http.client.HttpClientConnect - [d0f24979, L:/127.0.0.1:52841 - R:localhost/127.0.0.1:9080] The connection observed an error
javax.net.ssl.SSLException: failure when writing TLS control frames
	at io.netty.handler.ssl.SslHandler.setHandshakeFailureTransportFailure(SslHandler.java:1896)
	at io.netty.handler.ssl.SslHandler.access$600(SslHandler.java:168)
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:933)
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:928)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:288)
	at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:186)
	at io.netty.handler.proxy.ProxyHandler.failPendingWrites(ProxyHandler.java:434)
	at io.netty.handler.proxy.ProxyHandler.failPendingWritesAndClose(ProxyHandler.java:351)
	at io.netty.handler.proxy.ProxyHandler.setConnectFailure(ProxyHandler.java:346)
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:383)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:211)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: Failed to connect to proxy. Status: 407 Proxy Authentication Required
	at com.azure.core.http.netty.implementation.HttpProxyHandler.handleResponse(HttpProxyHandler.java:242)
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:257)
	... 22 more
```

**Comment by violetagg** [comment]
@nandorsoma Please provide reproducible example.

**Comment by pderop** [comment]
Hi @nandorsoma ,

Did you have a chance to try to provide a reproducible example ?
thanks

**Comment by nandorsoma** [comment]
> Hi @nandorsoma ,
> 
> 
> 
> Did you have a chance to try to provide a reproducible example ?
> 
> thanks

Hey @pderop !
I've experienced this issue transitively through an azure lib, I have an example with that, but I haven't got time yet to provide a pure netty example. But it is on my list!

**Comment by violetagg** [comment]
@nandorsoma I'm closing this one. We can reopen it when there is an example with vanilla Reactor Netty.

**Comment by nandorsoma** [comment]
Hi!
I was able to reproduce the issue, however it seems like a custom HttpProxyHandler is causing the bug in the azure-sdk-for-java so it is not related to that project. Sorry for the false alarm.
