### ISSUE TITLE
Connection prematurely closed BEFORE response after version upgrade

### ISSUE THREAD

**Issue by silvinoneto** [reactor/reactor-netty#2312]
Hello,

We have been using Spring Boot (2.3.3.RELEASE) + Reactor Netty (0.9.11.RELEASE) in one of our legacy projects for a long time. This system is live for over a few years now and we recently decided to upgrade some its libraries. So we bumped Spring Boot to 2.7.0 and Reactor Netty to 1.0.19.
We've done a load test using Gatling and running 40 requests/second over a 30-minutes interval, and we are currently struggling with "Connection prematurely closed BEFORE response" issue.

If we try the same test case with the previous version and the same target server, no issues occur.
No other code changes have been made in parallel. I've tried all timeout settings suggested at https://projectreactor.io/docs/netty/snapshot/reference/index.html#_timeout_configuration, but none of them appear to make much of a difference.

An interesting point, the test doesn't fail immediately, it runs without any errors for about 6 or 7 minutes, then it fails randomly from that moment on.

5 minutes of execution and no failures:
```
================================================================================
2022-06-20 10:13:59                                         300s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=7485   KO=0     )
---- Authorization -------------------------------------------------------------
[####-                                                                     ]  6%
          waiting: 41942  / active: 7      / done: 3026  
================================================================================
```

Past 6 minutes, we start to get failures:
```
================================================================================
2022-06-20 10:15:44                                         405s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=11172  KO=6     )
---- Errors --------------------------------------------------------------------
> status.find.is(200), but actually found 500                         6 (100.0%)

---- Authorization -------------------------------------------------------------
[#######-                                                                  ]  9%
          waiting: 40501  / active: 8      / done: 4466  
================================================================================
```

This is how we currently initialize our HttpClient:

```
    System.setProperty(ReactorNetty.POOL_MAX_CONNECTIONS, valueOf(requestsDefaults.getTcpConnectionPoolMaxSize()));
    // see https://github.com/reactor/reactor-netty/issues/390
    return ExchangeFunctions.create(new ReactorClientHttpConnector(resourceFactory, client ->
        client.protocol(H2, HTTP11)
            .secure()
            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, (int) requestsDefaults.getTcpConnectTimeout().toMillis())
            .wiretap(true)
            .option(ChannelOption.SO_KEEPALIVE, true)
            .responseTimeout(Duration.ofMillis(requestsDefaults.getTcpReadTimeout().toMillis()))
            .doOnConnected(connection -> connection
                .addHandlerLast(new WriteTimeoutHandler(
                    requestsDefaults.getTcpWriteTimeout().toMillis(),
                    MILLISECONDS
                ))
            )

            /*
            Legacy code from previous version

            .tcpConfiguration(tcp -> tcp.option(
                CONNECT_TIMEOUT_MILLIS,
                (int) requestsDefaults.getTcpConnectTimeout().toMillis()
            )
                .doOnConnected(connection -> connection
                    .addHandlerLast(new ReadTimeoutHandler(
                        requestsDefaults.getTcpReadTimeout().toMillis(),
                        MILLISECONDS
                    ))
                    .addHandlerLast(new WriteTimeoutHandler(
                        requestsDefaults.getTcpWriteTimeout().toMillis(),
                        MILLISECONDS
                    ))
                ))
            */
    ));
```

This is our config:
```
requests:
  defaults:
    tcpConnectionPoolMaxSize: 100
    tcpConnectTimeout: 5000ms
    tcpReadTimeout: 60000ms
    tcpWriteTimeout: 10000ms

reactor:
  netty:
    pool:
      maxConnections: ${requests.defaults.tcpConnectionPoolMaxSize} # 100
  tcp:
    sslHandshakeTimeout: ${requests.defaults.tcpConnectTimeoutMillis}
```

These are our error logs:
```
2022-06-20T13:15:44.369Z DEBUG: [id: 0x91d45c8f, L:/192.168.31.219:53133 - R:localhost/localhost:443] OUTBOUND HEADERS: streamId=20009 headers=DefaultHttp2Headers[:path: /oauth/token, :method: POST, :scheme: https, :authority: localhost, accept-encoding: gzip, user-agent: ReactorNetty/1.0.19, accept: */*, authorization: Basic <<REMOVED>>, content-type: application/x-www-form-urlencoded;charset=UTF-8, content-length: 97] padding=0 endStream=false | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=reactor.netty.http.client.h2, level=DEBUG
2022-06-20T13:15:44.369Z DEBUG: [91d45c8f, L:/192.168.31.219:53133 - R:localhost/localhost:443] WRITE: 9B

2022-06-20T13:15:44.369Z DEBUG: [id: 0x91d45c8f, L:/192.168.31.219:53133 - R:localhost/localhost:443] OUTBOUND DATA: streamId=20009 padding=0 endStream=true length=97 bytes=6772616e745f747970653d70617373776f726426757365726e616d653d6c6f63702d65642e6369312534306a656469782e636f6d2670617373776f72643d7825... | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=reactor.netty.http.client.h2, level=DEBUG
2022-06-20T13:15:44.369Z DEBUG: [91d45c8f, L:/192.168.31.219:53133 - R:localhost/localhost:443] WRITE: 9B

2022-06-20T13:15:44.370Z DEBUG: [91d45c8f/10004-1, L:/192.168.31.219:53133 - R:localhost/localhost:443] Added encoder [reactor.left.responseTimeoutHandler] at the beginning of the user pipeline, full pipeline: [reactor.left.h2ToHttp11Codec, reactor.left.httpTrafficHandler, reactor.left.httpDecompressor, reactor.left.responseTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0] | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=reactor.netty.ReactorNetty, level=DEBUG
2022-06-20T13:15:44.370Z DEBUG: [91d45c8f/10004-1, L:/192.168.31.219:53133 - R:R:localhost/localhost:443] Stream opened, now: 8 active streams and 128 max active streams. | logger=reactor.netty.http.client.Http2ConnectionProvider, level=DEBUG
2022-06-20T13:15:44.374Z DEBUG: [91d45c8f, L:/192.168.31.219:53133 - R:localhost/localhost:443] READ: 939B

2022-06-20T13:15:44.406Z DEBUG: [91d45c8f/10004-1, L:/192.168.31.219:53133 ! R:localhost/localhost:443] Non Removed handler: reactor.left.responseTimeoutHandler, context: ChannelHandlerContext(reactor.left.responseTimeoutHandler, [id: 0x91d45c8f, L:/192.168.31.219:53133 - R:localhost/localhost:443](H2 - 20009)), pipeline: AbstractHttp2StreamChannel$3{(reactor.left.h2ToHttp11Codec = io.netty.handler.codec.http2.Http2StreamFrameToHttpObjectCodec), (reactor.left.httpTrafficHandler = reactor.netty.http.client.Http2StreamBridgeClientHandler), (reactor.left.httpDecompressor = io.netty.handler.codec.http.HttpContentDecompressor), (reactor.left.responseTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)} | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=reactor.netty.ReactorNetty, level=DEBUG

2022-06-20T13:15:44.454Z ERROR: Internal error occurred: Unhandled exception! | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=com.logmein.api.transformation.logging.DefaultTransformationLogging, level=ERROR
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
Wrapped by: org.springframework.web.reactive.function.client.WebClientRequestException: Connection prematurely closed BEFORE response; nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
        at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP POST "/oauth/v2/token" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
                at java.base/java.lang.Thread.run(Thread.java:829) [75 skipped]
2022-06-20T13:15:44.454Z  INFO: Responding with status=500 Internal Server Error | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=com.logmein.api.transformation.logging.DefaultTransformationLogging, level=INFO
2022-06-20T13:15:44.454Z DEBUG: [5c3fce45-10177] Encoding [com.logmein.api.transformation.request.errorhandling.DefaultTransformationErrorResponse@1dd0b5b] | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=org.springframework.http.codec.json.Jackson2JsonEncoder, level=DEBUG
2022-06-20T13:15:44.455Z DEBUG: [2756e598-1, L:/127.0.0.1:8080 - R:/127.0.0.1:57970] Decreasing pending responses, now 0 | logger=reactor.netty.http.server.HttpServerOperations, level=DEBUG
2022-06-20T13:15:44.455Z DEBUG: [2756e598-10176] Completed 500 INTERNAL_SERVER_ERROR | requestId=245654e6-b34c-417f-94a2-5745311fc92a, logger=org.springframework.web.server.adapter.HttpWebHandlerAdapter, level=DEBUG
2022-06-20T13:15:44.455Z DEBUG: [2756e598-1, L:/127.0.0.1:8080 - R:/127.0.0.1:57970] Last HTTP response frame | requestId=245654e6-b34c-417f-94a2-5745311fc92a, logger=reactor.netty.http.server.HttpServerOperations, level=DEBUG
2022-06-20T13:15:44.455Z DEBUG: [2756e598-1, L:/127.0.0.1:8080 - R:/127.0.0.1:57970] Last HTTP packet was sent, terminating the channel | logger=reactor.netty.http.server.HttpServerOperations, level=DEBUG
2022-06-20T13:15:44.455Z ERROR: Internal error occurred: Unhandled exception! | requestId=63698486-8364-4b8e-bef7-666dbeb451a6, logger=com.logmein.api.transformation.logging.DefaultTransformationLogging, level=ERROR
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
Wrapped by: org.springframework.web.reactive.function.client.WebClientRequestException: Connection prematurely closed BEFORE response; nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
        at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP POST "/oauth/v2/token" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
                at java.base/java.lang.Thread.run(Thread.java:829) [75 skipped]
2022-06-20T13:15:44.455Z  INFO: Responding with status=500 Internal Server Error | requestId=63698486-8364-4b8e-bef7-666dbeb451a6, logger=com.logmein.api.transformation.logging.DefaultTransformationLogging, level=INFO
2022-06-20T13:15:44.456Z DEBUG: [5c3fce45-1, L:/127.0.0.1:8080 - R:/127.0.0.1:57971] Decreasing pending responses, now 0 | logger=reactor.netty.http.server.HttpServerOperations, level=DEBUG
2022-06-20T13:15:44.456Z DEBUG: [5c3fce45-10177] Completed 500 INTERNAL_SERVER_ERROR | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=org.springframework.web.server.adapter.HttpWebHandlerAdapter, level=DEBUG
2022-06-20T13:15:44.456Z DEBUG: [5c3fce45-1, L:/127.0.0.1:8080 - R:/127.0.0.1:57971] Last HTTP response frame | requestId=8625f73c-874c-4cf3-a53c-9a37e5fab64d, logger=reactor.netty.http.server.HttpServerOperations, level=DEBUG
```

Any help is much appreciated.

**Comment by violetagg** [comment]
@silvinoneto Can you provide a reproducible example?

**Comment by silvinoneto** [comment]
@violetagg I'll try to put in something together, cause right now this component is tightly couple with a lot of other stuff that we cannot leak to external audience. I'll need some time to create a working example. I ask you to kindly keep this ticket open as I create a reproducible example.

**Comment by violetagg** [comment]
@silvinoneto I'm closing this one. We can reopen it when there is more information.
