### ISSUE TITLE
Stabilize HttpProtocolsTests.testAccessLog

### ISSUE THREAD

**Issue by pderop** [reactor/reactor-netty#2373]
This test is flaky and it is observed that it fails from time to time on the CI fo version 2.0.x

Observed error:

```
HttpProtocolsTests > testAccessLog(HttpServer, HttpClient) > reactor.netty.http.HttpProtocolsTests.testAccessLog(HttpServer, HttpClient)[1] FAILED
    Wanted but not invoked:
    appender.doAppend(<Capturing argument>);
    -> at reactor.netty.http.HttpProtocolsTests.testAccessLog(HttpProtocolsTests.java:370)
    Actually, there were zero interactions with this mock.
        at app//reactor.netty.http.HttpProtocolsTests.testAccessLog(HttpProtocolsTests.java:370)
```

**Comment by violetagg** [comment]
We need to evaluate https://github.com/reactor/reactor-core/pull/3123
