### ISSUE TITLE
Stabilize PooledConnectionProviderDefaultMetricsTest#testConnectionPoolPendingAcquireSize

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#2374]
This test is flaky and it is observed that it fails from time to time on the CI for versions 2.0.x

Observed exception:

```
PooledConnectionProviderDefaultMetricsTest > testConnectionPoolPendingAcquireSize() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 0.0
     but was: 187.0
        at java.base@17.0.3/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@17.0.3/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base@17.0.3/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base@17.0.3/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at app//reactor.netty.resources.PooledConnectionProviderDefaultMetricsTest.testConnectionPoolPendingAcquireSize(PooledConnectionProviderDefaultMetricsTest.java:286)
```

**Comment by violetagg** [comment]
Fixed with eafbfefa190111bccc343b649cce4db3790cce26
