### ISSUE TITLE
ServerHttpResponse.headers updates not thread-safe

### ISSUE THREAD

**Issue by jgrgt** [reactor/reactor-netty#2466]
We recently had an issue where some `parallel` reactive code was writing headers to the response object on our reactive server. These caused a nullpointer exception deep inside of the HttpHeaders code:

```
Original Stack Trace:
	at io.netty.handler.codec.DefaultHeaders.remove0(DefaultHeaders.java:1003)
	at io.netty.handler.codec.DefaultHeaders.set(DefaultHeaders.java:434)
	at io.netty.handler.codec.DefaultHeaders.setObject(DefaultHeaders.java:481)
	at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:177)
		at java.base/java.util.Collections$SingletonMap.forEach(Unknown Source)
	at org.springframework.http.server.reactive.NettyHeadersAdapter.setAll(NettyHeadersAdapter.java:83)
	at org.springframework.http.HttpHeaders.setAll(HttpHeaders.java:1695)
```

We probably were abusing the `ServerHttpResponse.headers.setall(...)` method by calling it this way, and we'll do the updates from a single thread now. But I'm logging this because I can't find any mention that this code is thread-unsafe. While we were all expecting it to be. Maybe some documentation could be enhanced?

## Expected Behavior
The headers are updated without error even when this happens from multiple threads at the same time.

## Actual Behavior
A NPE happens.

## Steps to Reproduce
1. Run a reactive http server
2. Get a reference to the response object
3. Set headers (in our case the same header) from multiple threads at the same time.

## Possible Solution
We worked around it by restructuring our code.

## Your Environment
Spring boot 2.7.3, Java 17

**Comment by violetagg** [comment]
@jgrgt Can you check whether your Netty version contains this fix https://github.com/netty/netty/pull/11028

**Comment by violetagg** [comment]
@jgrgt Thanks
Please report this to Netty project as this functionality is not provided by Reactor Netty.
