### ISSUE TITLE
"Only one connection receive subscriber allowed." when using in Spring Gateway

### ISSUE THREAD

**Issue by re6exp** [reactor/reactor-netty#247]
### Expected behavior
Possibility to read request body twice - within the framework of Spring Gateway filter
### Actual behavior
Because of custom filter with [`NettyRoutingFilter`](https://github.com/spring-cloud/spring-cloud-gateway/blob/33bd6fff6935021db7b839656ac1668ede1a8b4d/spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java#L90) produces two subscribers, we have:
```
java.lang.IllegalStateException: Only one connection receive subscriber allowed.
	at reactor.ipc.netty.channel.FluxReceive.startReceiver(FluxReceive.java:276) ~[reactor-netty-0.7.2.RELEASE.jar:0.7.2.RELEASE]
	at reactor.ipc.netty.channel.FluxReceive.lambda$subscribe$2(FluxReceive.java:127) ~[reactor-netty-0.7.2.RELEASE.jar:0.7.2.RELEASE]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) ~[netty-transport-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.18.Final.jar:4.1.18.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```
### Steps to reproduce
see [here](https://github.com/spring-cloud/spring-cloud-gateway/issues/135)
### Reactor Netty version
0.7.2.RELEASE
### JVM version (e.g. `java -version`)
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version (e.g. `uname -a`)
Debian LInux 9.2

**Comment by rstoyanchev** [comment]
I think this ticket can be closed based. As [I commented](https://github.com/spring-cloud/spring-cloud-gateway/issues/135#issuecomment-352802735) from a Reactor Netty perspective the request body can be read only once, so "Works as designed".

**Comment by BlackHe** [comment]
here is solution  [https://github.com/spring-cloud/spring-cloud-gateway/issues/541#issuecomment-422917867](url)
