### ISSUE TITLE
Improve logging when connection closed due to cancel signal

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#2583]
In a pipeline with multiple client calls, it's possible for a cancel signal to close the connection, e.g. `Mono.zip` where one publisher completes empty. In this case, you might see a log messages for subscribing to the response stream, immediately followed by channel closing:

```
2022-11-18 08:58:52.678 DEBUG 41948 --- [tor-http-nio-16] reactor.netty.channel.FluxReceive        : FluxReceive{pending=0, cancelled=false, inboundDone=false, inboundError=null}: subscribing inbound receiver
2022-11-18 08:58:52.678 DEBUG 41948 --- [tor-http-nio-16] r.n.resources.PooledConnectionProvider   : Channel closed, now: 9 active connections, 136 inactive connections and 0 pending acquire requests.
```

It would have been helpful in this case to see a 3rd log message in between that shows there was a cancel signal. That would make it clear that something within the application pipeline caused the connection to be closed, and that the connection wasn't otherwise lost or closed from the remote end.

As an additional point, the Spring Framework `WebClient` uses `onErrorResume`, after an application `onStatus` handler is called, to ensure that response is consumed. It then ignores any errors that may result, if the was response was in fact consumed by the `onStatus` handler. That means in this scenario, you could also see the following in the logs:

```
2022-11-18 08:58:52.679 ERROR 41948 --- [tor-http-nio-16] reactor.core.publisher.Operators         : Operator called default onErrorDropped

java.lang.IllegalStateException: Only one connection receive subscriber allowed.
	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:182) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.channel.FluxReceive.subscribe(FluxReceive.java:143) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.netty.ByteBufFlux.subscribe(ByteBufFlux.java:340) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4455) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.24.jar:3.4.24]
```

As this is a scenario that's expected to occur, maybe the error message could be improved a little to something like "ignoring additional read. Response already consumed (or closed, or whatever the actual state)." to provide a little more context and hopefully guide better as to what happened.

**Comment by snicoll** [comment]
We were able to get this error with concurrent access on a service with something like `Mono#zip(first(),second())` where `second` would return `Mono.empty`

**Comment by pderop** [comment]
@snicoll , thanks for the hint, I have reproduced.

@rstoyanchev , for the `Only one connection receive subscriber allowed` log, can you please confirm that this log can be displayed, for example like in the spring-webflux [WebClientDataBufferAllocatingTests.onStatusWithBodyConsumed](https://github.com/spring-projects/spring-framework/blob/5.0.x/spring-webflux/src/test/java/org/springframework/web/reactive/function/client/WebClientDataBufferAllocatingTests.java#L104) test ? 

so, something like:


```
    @Test
    public void testOnceConnectionReceivedLog() throws InterruptedException {
        StepVerifier.create(webClient.get()
                        .uri("/notFound")
                        .accept(MediaType.APPLICATION_JSON)
                        .retrieve()
                        .onStatus(httpStatus -> httpStatus.is4xxClientError(), rsp -> rsp.bodyToMono(Void.class).thenReturn(new Exception("4XX")))
                        .bodyToMono(String.class))
                .expectError(Exception.class)
                .verify();
    }
```

 I'll try to submit a PR soon.

**Comment by rstoyanchev** [comment]
Yes, that should do it.
