### ISSUE TITLE
HTTP Client - EncoderException: unexpected message type: DefaultHttpRequest

### ISSUE THREAD

**Issue by philipWennerstrom** [reactor/reactor-netty#27]
After updating to reactor-netty 0.6.0.Release we started to get erro in Http Client, everything was working fine before. The error happens after the first request is made and keeps going the same behavior: one request is successfully processed and the next one fails. This issue happens when setting http content-length header in post request's with the following Exception:

`io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: DefaultHttpRequest
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:812)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:805)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.doWrite(ChannelOperationsHandler.java:245)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.drain(ChannelOperationsHandler.java:372)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.flush(ChannelOperationsHandler.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:787)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:813)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:805)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:842)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at reactor.ipc.netty.http.HttpOperations.lambda$sendHeaders$0(HttpOperations.java:96)
	at reactor.ipc.netty.FutureMono$DeferredFutureMono.subscribe(FutureMono.java:114)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:38)
	at reactor.core.publisher.MonoThenIgnore$MonoThenIgnoreMain.drain(MonoThenIgnore.java:166)
	at reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:54)
	at reactor.ipc.netty.NettyOutbound.subscribe(NettyOutbound.java:267)
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:465)
	at reactor.ipc.netty.http.client.HttpClientOperations.onHandlerStart(HttpClientOperations.java:415)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: unexpected message type: DefaultHttpRequest
	at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:69)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
	... 27 common frames omitted`

Please,we need a fix on this because we have to be able to work with content-length header in http client requests.

**Comment by spencergibb** [comment]
I can confirm the exact same behaviour. See https://github.com/spencergibb/spring-cloud-gateway/blob/master/src/test/java/org/springframework/cloud/gateway/test/GatewayIntegrationTests.java

**Comment by smaldini** [comment]
@philipWennerstrom can you retry with 0.6.1.BUILD-SNAPSHOT ?

**Comment by philipWennerstrom** [comment]
@smaldini I tried now with 0.6.1.BUILD-SNAPSHOT and its fixed :+1:

**Comment by smaldini** [comment]
Thanks a lot !
