### ISSUE TITLE
IllegalReferenceCountException refCnt: 0, decrement: 1  An exceptionCaught() event was fired, and it reached at the tail of the pipeline.

### ISSUE THREAD

**Issue by aonikiychuk** [reactor/reactor-netty#2738]
I am using 
Spring version 5.3.15
Netty 4.1.73

I've investigated few issues here about IllegalReferenceCountException trouble, but still do not find the solution for me.

I have some services which are intercommunicate with my trouble one.
The trouble one sends the request to another service. And i see that another one is sending back the response with code '200' and data.
But my trouble one do not get the response.

I can see an errors on the trouble one pod:   ( and i do not see this error on pods that works fine. Not all pods with the same service have troubles)
```
2023-03-10 14:59:03,855 [http-client-nio-2] [WARN] (io.netty.channel.DefaultChannelPipeline) [io.netty.channel.DefaultChannelPipeline::onUnhandledInboundException:1152] | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at reactor.netty.channel.AbstractChannelMetricsHandler.channelRead(AbstractChannelMetricsHandler.java:86)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
``` 
That is all I have in log.
Also I can notice that it happens in a different ways

Here we have
```
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
``` 
But i also saw
```
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
``` 
It is also not the "maxInMemorySize" trouble. Here is my code:
```java
@Value("${server.max-data-buffer-size:10MB}")
private DataSize maxDataBufferSize;

private WebClient webClient(String baseUrl, HttpClient httpClient) {
    if (enabledLoggingHttpClient) {
        httpClient = httpClient.wiretap(HTTP_CLIENT_FULL_NAME,
                LogLevel.DEBUG,
                AdvancedByteBufFormat.TEXTUAL);
    }
    return WebClient.builder()
            .baseUrl(baseUrl)
            .clientConnector(new ReactorClientHttpConnector(httpClient))
            .filter(openTracingExchangeFilterFunction)
            .codecs(c -> c.defaultCodecs().maxInMemorySize((int) maxDataBufferSize.toBytes()))
            .codecs(c -> c.customCodecs().registerWithDefaultConfig(new Jackson2JsonDecoder(jsonMapper)))
            .build();
}
``` 
Here is my HttpClient
```java
@Bean
public HttpClient nettyHttpClientTwallet(ConnectionProvider connectionProviderTwallet,
        LoopResources httpClientLoopTwallet) {
        HttpClient nettyHttpClient = HttpClient
            .create(connectionProviderTwallet)
            .runOn(httpClientLoopTwallet)
            .protocol(HttpProtocol.H2C)
            .compress(false)
            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, clientConnectionTimeout)
            .option(ChannelOption.TCP_NODELAY, true)
            .option(ChannelOption.SO_KEEPALIVE, true)
            .responseTimeout(Duration.ofMillis(responseTimeout))
            .wiretap(false)
            .metrics(true, s -> {
                if (metricProperties.clientPaths() == null) {
                    return s;
                }
                for (String clientPath : metricProperties.clientPaths()) {
                    if (s.startsWith(clientPath)) {
                        return clientPath;
                    }
                }
                return s;
            });
    nettyHttpClient.warmup().block();
    return nettyHttpClient;
}
``` 
And here is my WebClient call
```java
return webClient.get()
        .uri("/searchInfos/related/byClientId?clientId={clientId}", clientId)
        .header(RQ_UID, rqUID)
        .header(RQ_TM, rqTm)
        .accept(APPLICATION_JSON)
        .retrieve()
        .onStatus(HttpStatus::isError, this::logError)
        .bodyToMono(responseType)
        .map(responses -> responses.stream()
                .map(r -> new Response<>(cardProxyMapper.wrap(r.getBody()), r.getResultCode()))
                .collect(toList()));
``` 
It looks like i have IllegalReferenceCountException decrement trouble but i do not understand what should i do to fix it.

**Comment by violetagg** [comment]
@aonikiychuk This is a different problem - check this issue https://github.com/spring-projects/spring-framework/issues/26699

**Comment by aonikiychuk** [comment]
@violetagg  I've fixed 
```
java.lang.IllegalStateException: Only one connection receive subscriber allowed.
``` 
using your https://github.com/spring-projects/spring-framework/issues/26699 document. Thank you.

But I still can see a lot of
```
2023-03-30 07:19:24,854 [http-client-nio-3] [WARN] (io.netty.channel.DefaultChannelPipeline) [io.netty.channel.DefaultChannelPipeline::onUnhandledInboundException:1152] | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
``` 

I've added your _reactor.netty.channel.LeakDetection logger, but see no any "leak" in the log.
```
ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected.
Recent access records: 1
``` 

What else can I do?

**Comment by violetagg** [comment]
@aonikiychuk Are you able to provide a reproducible example?

**Comment by aonikiychuk** [comment]
@violetagg The reproducible example is described in my code above.
But I can reproduce it only under high load with other services. Not sure I can easily reproduce it and provide inbox solution for you.

I have only two more logs. The same error but in different places
1
```
2023-03-30 07:19:23,554 [http-client-nio-3] [WARN] (io.netty.channel.DefaultChannelPipeline) [io.netty.channel.DefaultChannelPipeline::onUnhandledInboundException:1152] | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at reactor.netty.channel.AbstractChannelMetricsHandler.channelRead(AbstractChannelMetricsHandler.java:86)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
at io.netty.buffer.AbstractByteBuf.checkNewCapacity(AbstractByteBuf.java:1432)
at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:103)
at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:305)
at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1103)
at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:99)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:277)
... 24 common frames omitted
``` 
2
```
2023-03-30 07:19:23,611 [http-client-nio-3] [WARN] (io.netty.channel.DefaultChannelPipeline) [io.netty.channel.DefaultChannelPipeline::onUnhandledInboundException:1152] | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at reactor.netty.channel.AbstractChannelMetricsHandler.channelRead(AbstractChannelMetricsHandler.java:86)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by aonikiychuk** [comment]
I've found one interesting log.
```
2023-04-06 09:39:18,448 [http-client-nio-3] [DEBUG] (reactor.netty.http.client.HttpClient) [io.netty.util.internal.logging.AbstractInternalLogger::log:145] | [2ea5ecca, L:/[29.64.148.29:49090](http://29.64.148.29:49090/) - R:cpc-card-search-svc.ci01871805-lt-ds-cpc.svc.cluster.local/[29.66.103.251:8080](http://29.66.103.251:8080/)] READ: 14B    Sň�־�
2023-04-06 09:39:18,448 [http-client-nio-3] [DEBUG] (reactor.netty.http.client.HttpClient) [io.netty.util.internal.logging.AbstractInternalLogger::log:145] | [2ea5ecca, L:/[29.64.148.29:49090](http://29.64.148.29:49090/) - R:cpc-card-search-svc.ci01871805-lt-ds-cpc.svc.cluster.local/[29.66.103.251:8080](http://29.66.103.251:8080/)] READ: 14B    Sň�־�
2023-04-06 09:39:18,448 [http-client-nio-3] [WARN] (io.netty.channel.DefaultChannelPipeline) [io.netty.channel.DefaultChannelPipeline::onUnhandledInboundException:1152] | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
``` 
I've found that entity " [2ea5ecca" always READ: 14B before  IllegalReferenceCountException.
And it is one to one.

So, no other entities generate IllegalReferenceCountException in this log.

The trouble is that 
1. I do not know what the entity it is
2. WebClient with doOnError does not catch IllegalReferenceCountException. So, I can not catch the moment of error.

It looks for me like if i can catch the " [2ea5ecca" and catch the moment of IllegalReferenceCountException it probably available to kill or restart this broken entity

**Comment by aonikiychuk** [comment]
@violetagg Violeta, do you understand what does that part of log mean?  2ea5ecca

**Comment by aonikiychuk** [comment]
As the result I've found out that connection restart can resolve the issue. I've set connection lifetime to 1 minute and the trouble dissapeares. For some time. But under the highload restarting connections are accumulating and than pod is restarting.

So the next step was to downgrade HTTP2 to HTTP1.1. And the trouble dissapeares.

**Comment by violetagg** [comment]
@aonikiychuk Your last comment might be related to #2760.

**Comment by violetagg** [comment]
I'm closing this one as a duplicate to #2760. We can reopen this issue if needed.
