### ISSUE TITLE
IllegalArgumentException: Channel [...] was not acquired from this ChannelPool

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#280]
The exception below happens from time to time:

```
Jan 05, 2018 5:55:04 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by reactor.ipc.netty.channel.PooledClientContextHandler$$Lambda$109/1329857275.operationComplete()
reactor.core.Exceptions$BubblingException: java.lang.IllegalArgumentException: Channel [id: 0xe19d8d88, L:/someIp:56991 - R:someUrl.com/someip:443] was not acquired from this ChannelPool
    at reactor.core.Exceptions.bubble(Exceptions.java:154)
    at reactor.core.publisher.Operators.onErrorDropped(Operators.java:256)
    at reactor.core.publisher.DirectProcessor.onError(DirectProcessor.java:117)
    at reactor.ipc.netty.channel.PooledClientContextHandler.lambda$release$3(PooledClientContextHandler.java:273)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
    at io.netty.channel.pool.SimpleChannelPool.closeAndFail(SimpleChannelPool.java:365)
    at io.netty.channel.pool.SimpleChannelPool.doReleaseChannel(SimpleChannelPool.java:300)
    at io.netty.channel.pool.SimpleChannelPool.access$300(SimpleChannelPool.java:42)
    at io.netty.channel.pool.SimpleChannelPool$5.run(SimpleChannelPool.java:286)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Channel [id: 0xe19d8d88, L:/someIp:56991 - R:someUrl.com/someIp:443] was not acquired from this ChannelPool
    ... 8 more
```

**Comment by violetagg** [comment]
Fixed #266
