### ISSUE TITLE
Question about WebSocket: How to `sendClose` in `onErrorResume` to tell client how connection was interrupted?

### ISSUE THREAD

**Issue by hu-chia** [reactor/reactor-netty#2869]
This is an minimal sample to reproduce my question:

version: 1.1.8
expected behavior: client received a close frame with code `4001` and reason text `Interrupted`
in fact: console output is ```1005 Empty```

How to make the behavior here as expected? 

```java
import io.netty.handler.codec.http.websocketx.WebSocketCloseStatus;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Sinks;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.WebsocketClientSpec;
import reactor.netty.http.server.HttpServer;

import java.time.Duration;

public class TestSendClose {

    public static void main(String... args) throws InterruptedException {
        int port = 8080;

        var sink = Sinks.<byte[]>one();

        HttpServer.create()
                .port(port)
                .route(routes -> routes.ws("/", (i, o) -> i.receive()
                                .asByteArray()
                                .mergeWith(sink.asMono())
                                .then()
                                .onErrorResume(Interrupted.class, e -> o.sendClose(e.status().code(), e.status().reasonText()))))
                .bind()
                .subscribe();

        HttpClient.create()
                .wiretap(true)
                .websocket(WebsocketClientSpec.builder().build())
                .uri("http://localhost:" + port + "/")
                .handle((i, o) -> {
                    o.sendByteArray(Flux.interval(Duration.ofSeconds(3)).map(number -> new byte[] { number.byteValue() } )).then().subscribe();
                    return i.receiveCloseStatus();
                })
                .subscribe(System.out::println);

        sink.tryEmitError(new Interrupted()).orThrow();

        System.out.println("Waiting for a while");

        Thread.currentThread().join();
    }

    static class Interrupted extends RuntimeException {

        public WebSocketCloseStatus status() {
            return new WebSocketCloseStatus(4001, "Interrupted");
        }
    }
}
```

**Comment by guyeu** [comment]
PS: tried to catch the Exceptions then emit a `WebSocketCloseStatus` by `Sink`, now I got an `io.netty.util.IllegalReferenceCountException`

```java
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.ByteBufUtil.ensureAccessible(ByteBufUtil.java:126)
	at io.netty.buffer.DefaultByteBufHolder.content(DefaultByteBufHolder.java:35)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameEncoder.encode(WebSocket08FrameEncoder.java:107)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameEncoder.encode(WebSocket08FrameEncoder.java:73)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:295)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

but, I cannot reproduce it in a sample

**Comment by violetagg** [comment]
@hu-chia Can you try the modified example below

```
HttpServer.create()
        .port(port)
        .route(routes -> routes.ws("/", (i, o) -> i.receive()
                       .asByteArray()
                       .publish()
                       .autoConnect()
                       .mergeWith(sink.asMono())
                       .then()
                       .onErrorResume(Interrupted.class, e -> o.sendClose(e.status().code(), e.status().reasonText())).log()))
        .bind()
        .subscribe();
```

With this the connection will not be closed automatically when an exception occurs but you will be in control to close it as you want.

You can check also these #337 and #967

**Comment by hu-chia** [comment]
@violetagg Could you please explain the `publish` and `autoConnect` actually do?

**Comment by violetagg** [comment]
> @violetagg Could you please explain the `publish` and `autoConnect` actually do?

Can you take a look at this https://projectreactor.io/docs/core/release/reference/#advanced-broadcast-multiple-subscribers-connectableflux

Also check the mentioned issues above.

**Comment by hu-chia** [comment]
Thank you
