### ISSUE TITLE
Malformed log formats cause NullPointerException

### ISSUE THREAD

**Issue by telendt** [reactor/reactor-netty#336]
### Expected behavior

Log message format should have equal number of placeholders to number of given values.

Normally this should not cause any major issues (other that "incomplete" log messages) but with combination of buggy ConsoleLogger from reactor-core (bug to be reported) it causes NullPointerExceptions.

### Actual behavior

```
Exception in thread "main" java.lang.NullPointerException
	at reactor.util.Loggers$ConsoleLogger.format(Loggers.java:457)
	at reactor.util.Loggers$ConsoleLogger.debug(Loggers.java:497)
	at reactor.ipc.netty.ReactorNetty.removeHandler(ReactorNetty.java:172)
	at reactor.ipc.netty.NettyContext.removeHandler(NettyContext.java:270)
	at EventSource.main(EventSource.java:37)
```

### Steps to reproduce

```
import io.netty.channel.local.LocalChannel;
import reactor.ipc.netty.NettyContext;
import reactor.util.Loggers;

// main
Loggers.useConsoleLoggers();
NettyContext context = LocalChannel::new;
context.removeHandler("nonexistent");  // throws NPE
```

### Reactor Netty version

`0.7.6.RELEASE` (reactor-core: 3.1.6.RELEASE)

### JVM version (e.g. `java -version`)

```
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

(same thing on java 9 and 8)

### OS version (e.g. `uname -a`)

```Darwin XXX 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64```

**Comment by telendt** [comment]
These are the malformed log formats that I found. 

- [ReactorNetty.java:172](https://github.com/reactor/reactor-netty/blob/74021b06fa575783d85182772754f0c7cbb8ec4b/src/main/java/reactor/ipc/netty/ReactorNetty.java#L172) - 3 placeholders, 4 arguments
- [ReactorNetty.java:194](https://github.com/reactor/reactor-netty/blob/74021b06fa575783d85182772754f0c7cbb8ec4b/src/main/java/reactor/ipc/netty/ReactorNetty.java#L194) - 3 placeholders, 4 arguments
- [PooledClientContextHandler.java:181](https://github.com/reactor/reactor-netty/blob/39cbb8c4e3db66e9f3c45176a9a651570077e5b7/src/main/java/reactor/ipc/netty/channel/PooledClientContextHandler.java#L181) - 2 placeholders, 1 argument
- [HttpClientOperations.java:543](https://github.com/reactor/reactor-netty/blob/f4422439057ef453843fb3a919a181a0893ca1a2/src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java#L543) - 1 placeholder, 2 arguments
- [HttpClientOperations.java:606](https://github.com/reactor/reactor-netty/blob/f4422439057ef453843fb3a919a181a0893ca1a2/src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java#L606) - 1 placeholder, 2 arguments

@smaldini: What text editor/IDE do you use? Do you think you could set it up somehow so it could help you detect such issues in the future?
