### ISSUE TITLE
Failed to connect to APNS [Unexpected HTTP/1.x request]

### ISSUE THREAD

**Issue by enricosecondulfo** [reactor/reactor-netty#399]
I'm trying to send a request to apns  with following code:

```
HttpClient
                .create()
                .tcpConfiguration { tcpClient ->
                    tcpClient.proxy {
                        options ->
                        options.type(ProxyProvider.Proxy.HTTP)
                                .host("127.0.0.1")
                                .port(8888)
                    }
                }
                // .create(ConnectionProvider.fixed("test", 1000))
                .headers { headerBuilder ->
                    headerBuilder.add("Authorization", token)
                    headerBuilder.add("apns-topic", boundleId)
                    headerBuilder.add("apns-expiration", "0")
                    headerBuilder.add("apns-priority", "10")

                }
                .secure { t -> t.sslContext(sslContext) }
                .post()

                .uri("https://api.development.push.apple.com/3/device/8439483094830498309")

                .response()
                .doOnError { error -> print(error)}
                .log()
                .subscribe { response -> print(response) }

```
but the server answers with the following message  
`Unexpected HTTP/1.x request: POST /3/device/XXXXXXXXXXXXXXXXX`

Can I explicitly specify the http\2 protocol version? 

Thanks

**Comment by violetagg** [comment]
@enricosecondulfo I see you provide your own `sslContext`. Please ensure it has the necessary configuration.
For example https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientSecure.java#L80-L89

**Comment by enricosecondulfo** [comment]
@violetagg Using the configuration specified in the file you submitted to me,
i have the following error:
```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:255) [netty-handler-proxy-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:255) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at java.base/sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1602) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:497) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:745) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:680) ~[na:na]
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626) ~[na:na]
	at io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:90) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.Java9SslEngine.unwrap(Java9SslEngine.java:139) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
	... 28 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1830) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1735) ~[na:na]
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:347) ~[na:na]
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:339) ~[na:na]
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1968) ~[na:na]
	at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1777) ~[na:na]
	at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:264) ~[na:na]
	at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1098) ~[na:na]
	at java.base/sun.security.ssl.Handshaker$1.run(Handshaker.java:1031) ~[na:na]
	at java.base/sun.security.ssl.Handshaker$1.run(Handshaker.java:1028) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1540) ~[na:na]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1435) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	... 32 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290) ~[na:na]
	at java.base/sun.security.validator.Validator.validate(Validator.java:264) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:343) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:284) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:145) ~[na:na]
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1952) ~[na:na]
	... 41 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:na]
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:na]
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380) ~[na:na]
	... 47 common frames omitted
```

**Comment by smaldini** [comment]
Http Client is not yet supporting H2 unfortunately. It should be in the next milestone (M2)

**Comment by enricosecondulfo** [comment]
Thanks for the reply and for the hard work

**Comment by juanpmarin** [comment]
@smaldini Is there a workaround for this ?

**Comment by violetagg** [comment]
HTTP/2 for the client will be tracked here #639
