### ISSUE TITLE
"Operator called default onErrorDropped" when stream is cancelled

### ISSUE THREAD

**Issue by madgnome** [reactor/reactor-netty#472]
### Expected behavior
Cancellation should be propagated and we shouldn't get `onErrorDropped`

### Actual behavior

After cancellation we're getting `onErrorDropped`

```
11:14:26.811 [reactor-http-nio-5] INFO  reactor.Mono.Map.1 - onNext(GET{uri=/a, connection=PooledConnection{channel=[id: 0xe285a984, L:/127.0.0.1:51635 - R:localhost/127.0.0.1:6666]}})
11:14:26.814 [reactor-http-nio-5] INFO  reactor.Mono.Map.1 - cancel()
11:14:26.814 [reactor-http-nio-7] INFO  reactor.Mono.Map.1 - cancel()
11:14:26.815 [reactor-http-nio-7] DEBUG r.n.http.client.HttpClientOperations - [id: 0xd1fd37a4, L:/127.0.0.1:51634 - R:localhost/127.0.0.1:6666] Received last HTTP packet
11:14:26.815 [reactor-http-nio-7] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd1fd37a4, L:/127.0.0.1:51634 - R:localhost/127.0.0.1:6666] onStateChange(GET{uri=/b, connection=PooledConnection{channel=[id: 0xd1fd37a4, L:/127.0.0.1:51634 - R:localhost/127.0.0.1:6666]}}, [disconnecting])
11:14:26.815 [reactor-http-nio-7] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd1fd37a4, L:/127.0.0.1:51634 - R:localhost/127.0.0.1:6666] Releasing channel
11:14:26.815 [reactor-http-nio-7] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd1fd37a4, L:/127.0.0.1:51634 - R:localhost/127.0.0.1:6666] Channel cleaned, now 1 active connections and 1 inactive connections
11:14:26.821 [reactor-http-nio-5] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
java.lang.RuntimeException: A failed
	at reactor.netty.http.NettyTest.lambda$name$1(NettyTest.java:46) ~[classes/:na]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.2.2.BUILD-SNAPSHOT.jar:3.2.2.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) [reactor-core-3.2.2.BUILD-SNAPSHOT.jar:3.2.2.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) [reactor-core-3.2.2.BUILD-SNAPSHOT.jar:3.2.2.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:81) [reactor-core-3.2.2.BUILD-SNAPSHOT.jar:3.2.2.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:147) [reactor-core-3.2.2.BUILD-SNAPSHOT.jar:3.2.2.BUILD-SNAPSHOT]
	at reactor.netty.http.client.HttpClientConnect$HttpObserver.onStateChange(HttpClientConnect.java:386) [classes/:na]
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:498) [classes/:na]
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:440) [classes/:na]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:493) [classes/:na]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:141) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

### Steps to reproduce

```
package reactor.netty.http;

import org.junit.Test;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.netty.DisposableServer;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.server.HttpServer;
import reactor.test.StepVerifier;

import java.time.Duration;


public class NettyTest {

    @Test
    public void name() throws InterruptedException {

        HttpClient client = HttpClient.create();


        DisposableServer blockingFacade = HttpServer.create()
                                                    .port(6666)
                                                    .host("localhost")
                                                    .handle((req, resp) -> {
                                                        if (req.path().startsWith("a")) {
                                                            return resp.status(400).send()
                                                                       .delaySubscription(Duration.ofMillis(50));
                                                        } else {
                                                            return resp.status(410).send()
                                                                       .delaySubscription(Duration.ofMillis(50));
                                                        }
                                                    })
                                                    .wiretap()
                                                    .bindNow();


        StepVerifier.create(
                Flux.merge(
                        client
                                .get()
                                .uri("http://localhost:6666/a")
                                .response()
                                .log()
                                .flatMap(
                                        httpClientResponse -> Mono.error(new RuntimeException("A failed")))
                        ,
                        client.get().uri("http://localhost:6666/b").response()
                              .flatMap(httpClientResponse -> Mono.error(new RuntimeException("B failed"))))
                    .take(1)
                    .single())
                    .verifyError();

        Thread.sleep(5000);

        blockingFacade.disposeNow();
    }
}
```

### Reactor Netty version
0.7.8 and 0.8.2.BUILD-SNAPSHOT

**Comment by madgnome** [comment]
@smaldini would it make sense to change the default log message to `warn` as it's not an error per se.

```
public static void onErrorDropped(Throwable e, Context context) {
		Consumer<? super Throwable> hook = context.getOrDefault(Hooks.KEY_ON_ERROR_DROPPED,null);
		if (hook == null) {
			hook = Hooks.onErrorDroppedHook;
		}
		if (hook == null) {
			log.error("Operator called default onErrorDropped", e);
			throw Exceptions.bubble(e);
		}
		hook.accept(e);
	}
```

**Comment by smaldini** [comment]
I think it makes sense we opened https://github.com/reactor/reactor-core/issues/1431 in order to introduce that change after a round of discussion this morning. We thought that this bubbling up is not a behavior you can rely on as a user anyway so it could be part of a next patch release. thoughts ?

**Comment by madgnome** [comment]
As long as https://github.com/reactor/reactor-core/issues/1431 action `onErrorDropped` as well of `onOperatorError` that sounds good!
