### ISSUE TITLE
Connection closed before flushing the response body

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#508]
### Expected behavior

If an HTTP client sends a request with a `Connection: close` header and then when the server responds with both `Connection: close` and `Content-Length: 0`, trying to write an empty body, the HTTP response is empty and the server managed to properly flush the response body before closing the connection.

### Actual behavior

This comes from a Spring Framework report, [SPR-17493](https://jira.spring.io/browse/SPR-17493).
When the server responds with both `Connection: close` and `Content-Length: 0`, the connection is closed before the body is written and flushed. From the client's point of view, the response is fine.

But we're seeing the following in the logs:

```
16:24:37.944 [reactor-http-nio-2] DEBUG reactor.netty.http.server.HttpServerOperations - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:50515] New http connection, requesting read
16:24:37.948 [reactor-http-nio-2] DEBUG reactor.netty.channel.BootstrapHandlers - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:50515] Initialized pipeline DefaultChannelPipeline{(BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpServerCodec), (reactor.left.httpTrafficHandler = reactor.netty.http.server.HttpTrafficHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
16:24:37.953 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
16:24:37.953 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
16:24:37.953 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
16:24:37.953 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
16:24:37.972 [reactor-http-nio-2] DEBUG reactor.netty.http.server.HttpServerOperations - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:50515] Increasing pending responses, now 1
16:24:38.061 [reactor-http-nio-2] DEBUG reactor.netty.http.server.HttpServer - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:50515] Handler is being applied: Scratch$$Lambda$8/57494364@5d705e87
16:24:38.069 [reactor-http-nio-2] DEBUG reactor.netty.channel.ChannelOperationsHandler - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:50515] Writing object DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
HTTP/1.1 200 OK
content-length: 0
16:24:38.077 [reactor-http-nio-2] DEBUG reactor.netty.http.server.HttpServerOperations - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 - R:/0:0:0:0:0:0:0:1:50515] Detected non persistent http connection, preparing to close
16:24:38.085 [reactor-http-nio-2] DEBUG reactor.netty.channel.ChannelOperationsHandler - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 ! R:/0:0:0:0:0:0:0:1:50515] Writing object MonoCallable
16:24:38.087 [reactor-http-nio-2] DEBUG reactor.netty.channel.ChannelOperationsHandler - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 ! R:/0:0:0:0:0:0:0:1:50515] Terminated ChannelOperation. Dropping Pending Write: MonoCallable
16:24:38.092 [reactor-http-nio-2] DEBUG reactor.netty.channel.ChannelOperations - [id: 0x82bfddd4, L:/0:0:0:0:0:0:0:1:8080 ! R:/0:0:0:0:0:0:0:1:50515] An outbound error could not be processed
reactor.netty.channel.AbortedException: Connection has been closed
	at reactor.netty.channel.ChannelOperationsHandler.discard(ChannelOperationsHandler.java:358)
	at reactor.netty.channel.ChannelOperationsHandler.drain(ChannelOperationsHandler.java:368)
	at reactor.netty.channel.ChannelOperationsHandler.handlerRemoved(ChannelOperationsHandler.java:210)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:670)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:922)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:888)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:880)
	at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1416)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:865)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:830)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
```

In this **very** specific use case, the only issue is this `AbortedException` since the empty body couldn't be written. A single byte body works as expected. Removing the `Content-Length` response header works around the issue.

### Steps to reproduce

Start the following server:

```java
HttpServer.create().port(8080).handle((req, res) -> {
			res.header("Content-Length", "0");
			return res.sendByteArray(Mono.just(new byte[]{}));
		}).bindUntilJavaShutdown(Duration.ofSeconds(10), disposableServer -> {});
```

Typing the following in a terminal triggers the issue:

```
$ curl -H "Connection: close" -v localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Connection: close
>
< HTTP/1.1 200 OK
< content-length: 0
< connection: close
<
* Closing connection 0
```

At that point, you should see an exception in the server logs.

### Reactor Netty version

`0.8.2.RELEASE`

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-macosx) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-macosx) (build 25.181-b02, mixed mode)
```

### OS version (e.g. `uname -a`)

```
Darwin 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
```

**Comment by violetagg** [comment]
Hi,

This behaviour is expected.
As `Content-Length: 0` is specified the server will not attempt to write anything.
As `Connection: close` is specified, the server will close the connection immediately after sending the response.
The provided content will be dropped.

However we made one optimisation in the code and we will drop the content on an early stage as we know the connection is not alive.

Regards,
Violeta

**Comment by bm3780** [comment]
@violetagg  I had originally submitted SPR-17493 reporting this issue.  We reported the issue because we saw that the client was indeed receiving the correct response (with `Content-Length: 0` and `Connection: close`), but was confused by the errors in our log.  We thought possibly the error logging was a mistake since the response was indeed written.  Are you saying this error logging is expected, even when the response is successfully written to the client?

**Comment by violetagg** [comment]
@bm3780 With my commit we made the exception more explicit 

```
13:53:17.237 [reactor-http-nio-6] DEBUG r.netty.channel.ChannelOperations - [id: 0x26b6c5db, L:/0:0:0:0:0:0:0:1:63348 ! R:/0:0:0:0:0:0:0:1:63349] An outbound error could not be processed
reactor.netty.channel.AbortedException: Cannot publish the content FluxMapFuseable, the connection has been closed
```

The message is with `DEBUG` log level and the idea is to notify you that the content that the client was supposed to send is not sent.

Reactor Netty cannot make assumption whether this is an issue or not.

Regards,
Violeta

**Comment by bm3780** [comment]
@violetagg  ok that make sense

@bclozel Any plans to handle this logging better on the Spring side?  I'm still seeing log errors in the latest 5.1.2 release.  I believe you mentioned [SPR-17341](https://jira.spring.io/browse/SPR-17341) being related to this issue.

`2018-12-05 07:04:37 [reactor-http-nio-2] ERROR o.s.w.s.a.HttpWebHandlerAdapter - [0e35896f] Error [reactor.netty.channel.AbortedException: Cannot publish the contentFluxMap, the connection has been closed] for HTTP GET "/foo", but ServerHttpResponse already committed (200 OK)`

**Comment by bclozel** [comment]
@bm3780 which version of Reactor are you using? Are you using the Spring Boot dependency management?

**Comment by bm3780** [comment]
@bclozel <https://github.com/bclozel> I'm using the Spring Boot dependency
management.  It's bringing in reactor-netty 0.8.3, and reactor-core 3.2.3.

**Comment by rstoyanchev** [comment]
SPR-17341 is related indeed but it more about differentiating between client side vs server side (e.g. 
talking to remote host via WebClient) connection issues. In the mean time we might add `AbortedException` to the list of `DISCONNECTED_CLIENT_EXCEPTIONS` in `HttpWebHandlerAdapter`.

**Comment by swallretu** [comment]
@violetagg @bclozel Hi i still hit this issue when i use springboot dependency management with reactor-netty 0.8.6.RELEASE version, my springboot version is 2.1.4 with springcloud Greenwich.SR1, could i know in which reactor-netty version this issue had been fixed and released? blow this my issue
`reactor.netty.channel.AbortedException: Connection has been closed
	at reactor.netty.channel.ChannelOperationsHandler.discard(ChannelOperationsHandler.java:356)
	at reactor.netty.channel.ChannelOperationsHandler.drain(ChannelOperationsHandler.java:366)
	at reactor.netty.channel.ChannelOperationsHandler.handlerRemoved(ChannelOperationsHandler.java:210)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:961)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:638)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:887)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:853)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:845)
	at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1390)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:178)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:164)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:830)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:835)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)

2021-12-11 13:05:57.281 ERROR 27785 --- [or-http-epoll-5] o.s.w.s.adapter.HttpWebHandlerAdapter    : [8d36ff6a] Error [java.lang.UnsupportedOperationException] for HTTP POST "/sws/webhook/hws/alert", but ServerHttpResponse already committed (200 OK)`
