### ISSUE TITLE
Pooled connection observed an error

### ISSUE THREAD

**Issue by dave-fl** [reactor/reactor-netty#534]
I am testing using version:

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <spring-cloud.version>Greenwich.BUILD-SNAPSHOT</spring-cloud.version>
        <reactor-bom.version>Californium-BUILD-SNAPSHOT</reactor-bom.version>
        <netty.version>4.1.31.Final</netty.version>
    </properties>

And am seeing the following in my logs.

	   2018-11-28T17:02:10.72-0500 [APP/PROC/WEB/0] OUT io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	   2018-11-28T17:02:10.72-0500 [APP/PROC/WEB/0] OUT     at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[netty-transport-native-unix-common-4.1.31.Final.jar!/:4.1.31.Final]
	   2018-11-28T17:02:15.70-0500 [APP/PROC/WEB/0] OUT 2018-11-28 22:02:15.701 ERROR 20 --- [or-http-epoll-3] r.n.resources.PooledConnectionProvider   : [id: 0x4a2190b7, L:/10.254.0.22:59054 - R:myhost/myip:443] Pooled connection observed an error

**Comment by violetagg** [comment]
@dave-fl Any chance to extract some reproducible scenario? Thanks

**Comment by violetagg** [comment]
@dave-fl Except this logging message do you observe some problems?

It appeared that we log with `ERROR` log level even exceptions that we will retry (`RedirectClientException`, `Connection reset by peer`) #535

**Comment by dave-fl** [comment]
I experience no issues at all.  Maybe the endpoint is just being forcibly closed.

**Comment by darekurlik** [comment]
Hi All, I've just experienced something similar. I have two reactive spring-boot 2 apps lets call those A and B. A is talking to B over http using spring web client.  Initially A got error following error when calling B:
`io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Connection reset by peer
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
	at io.netty.channel.unix.Errors.ioResult(Errors.java:146)`
So I've modified client in A as someone else suggested to disable KEEP ALIVE .
And now sometimes I got following on A:
`Pooled connection observed an error io.netty.handler.timeout.ReadTimeoutException: null` any ideas?

**Comment by violetagg** [comment]
@darekurlik Open a new issue with reproducible scenario and logs/tcpdump. Do you have load balancers/proxies between A and B.

**Comment by darekurlik** [comment]
@violetagg Not reproducible I am afraid, its "random". I've experienced that on  0.8.3.RELEASE. Will increment to 0.8.4.RELEASE and let you know if I notice any difference. There is no LB or proxy between A and B. Those are two spring boot 2 apps running on two separate docker containers.
