### ISSUE TITLE
IOException when client application terminates

### ISSUE THREAD

**Issue by urferr** [reactor/reactor-netty#555]
### Actual behavior
When the client application terminates I get a "IOException: An existing connection has been closed by the remote host".

java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.base/java.lang.Thread.run(Thread.java:834)

Also each time I run the client again a new Daemon Thread called "reactor-http-nio-#" is created in the server application.

### Expected behavior
No IOException is thrown and that the number of threas in the server stays constant.

### Steps to reproduce
The issue can be reproduced with the client/server example available under https://github.com/poutsma/web-function-sample.git. I have upgraded this example to use io.projectreactor:Californium-SR3 and spring-framework:5.1.3.RELEASE.

### Reactor Netty version
0.8.3.RELEASE

### JVM version (e.g. `java -version`)
11.0.1

### OS version (e.g. `uname -a`)
Windows 10 Pro

**Comment by violetagg** [comment]
@urferr This exception is logged with DEBUG level so it just tells you that the client closes the connection. Here in this example when the program exits (client) the connection is closed.
About the threads, I see the server operated correctly with all 4 threads and no more. I see only threads with numbers 1 to 4.

**Comment by violetagg** [comment]
@urferr I see the level is ERROR in 0.8.x
