### ISSUE TITLE
UnresolvedAddressException when using HttpClient

### ISSUE THREAD

**Issue by WiedemannA** [reactor/reactor-netty#615]
### Expected behavior
`WebClient` created from `ClientHttpConnector` using `reactor.netty.http.client.HttpClient` doesn't cause `UnresolvedAddressException` when used.

### Actual behavior
Using the HttpClient causes the following exception:
```
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
        at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
        at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
        at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:312)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
        at io.netty.handler.ssl.SslHandler.connect(SslHandler.java:715)
...
```

### Steps to reproduce
The Problem occurs in a spring boot webflux service:
1. We create a TcpClient with the ProxyBuilder to configure a proxy:
```
tcpClient = TcpClient.create().secure(sslProvider).proxy(ts -> buildProxy(ts, proxyHost, proxyPort, proxyUser, proxyPassword))
...
private Builder buildProxy(TypeSpec ts, String proxyHost, Integer proxyPort, String proxyUser, String proxyPassword) {
    return ts.type(ProxyProvider.Proxy.HTTP).address(new InetSocketAddress(proxyHost, proxyPort));
}
```
2. We use this `tcpClient` to provide the `ClientHttpConnector`
```
@Bean
public ClientHttpConnector proxyClientHttpConnector(@Autowired TcpClient tcpClient) {
    HttpClient httpClient = HttpClient.from(tcpClient);
    return new ReactorClientHttpConnector(httpClient);
}
```
3. We initialize the `WebClient` we use with this autowired `ClientHttpConnector`
```
WebClient.builder().clientConnector(clientHttpConnector).build()
```

### Reactor Netty version
0.8.3.RELEASE

### JVM version
1.8.0_171

### OS version
Windows-10 64 Bit

### Possible Problem cause + solution:
We've analysed the source why this exception is thrown and found out,
that [HttpClientConnect.java](https://github.com/reactor/reactor-netty/blob/295c8587cd4fd062c04d315157cf6854e4205e89/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L975) uses hardcoded `InetSocketAddressUtil::createUnresolved`
and therefore the addresses are unresolved.
A locally build version of Reactor Netty using `InetSocketAddressUtil::createResolved` fixes the problem!

**Comment by violetagg** [comment]
@WiedemannA I cannot reproduce the issue with the latest Reactor Netty `0.8.5.RELEASE` (Spring Boot `2.1.3.RELEASE`).
https://github.com/violetagg/ReactorNettyIssue615

May be there is a missing configuration?

**Comment by WiedemannA** [comment]
@violetagg: I've updated our Project to Spring Boot from `2.1.1.RELEASE` to `2.1.3.RELEASE` and that solved the problem.
-> I've debugged the code and in the new version the 'remoteAddress'-Parameter given to 'Bootstrap.doConnect' is already a resolved Address, which fixes the probem...
I didn't think that a minor outdated version could cause the problem :neutral_face:

Huge thank you for the fast response and sorry for the inconvenience 👍
