### ISSUE TITLE
100-Continue bug ?

### ISSUE THREAD

**Issue by Crystark** [reactor/reactor-netty#62]
Following https://gitter.im/reactor/reactor?at=58c928a5872fc8ce62083bae

This doesn't work when a 100-Continue is issued by the client:

```java
return HttpServer.create(port).newHandler((request, response) ->  request.receive()
	.doOnNext(ByteBuf::retain)
	.compose(bb -> response.send(bb));
);
```

Server responds with a 200 OK instead of a 100-Continue.

```
> POST / HTTP/1.1
> User-Agent: curl/7.26.0
> Host: localhost:9100
> Accept: */*
> Content-Length: 1828
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< transfer-encoding: chunked
<
* additional stuff not fine transfer.c:1037: 0 0
* Done waiting for 100-continue
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* Operation timed out after 5000 milliseconds with 0 bytes received
* Closing connection #0
curl: (28) Operation timed out after 5000 milliseconds with 0 bytes received
```

If I do the following it works though

```java
return HttpServer.create(port).newHandler((request, response) ->  request.receive()
	.doOnNext(ByteBuf::retain)
	.flatMap(bb -> response.send(Mono.just(bb)));
);
```

I'm using version `0.6.2.RELEASE`
Also please note that if the client doesn't expect a 100-Continue (for instance, sent content is small enough to fit in one chunk) both solution work.

**Comment by Crystark** [comment]
Additional information in case it's linked:

If I do 

```java
return request.receive()
	.doOnCancel(() -> System.out.println("doOnCancel"))
	.doOnError(t -> System.out.println("doOnError"))
	.doOnSubscribe(s -> System.out.println("doOnSubscribe"))
	.doOnEach(s -> System.out.println("doOnEach " + s))
	.doOnRequest(l -> System.out.println("doOnRequest " + l))
	.doOnTerminate(() -> System.out.println("doOnTerminate"))
	.doOnComplete(() -> System.out.println("doOnComplete"))
	.doOnNext(b -> System.out.println("doOnNext"))
	.compose(bb -> response.send(bb));
```

then I only get 
```
doOnSubscribe
doOnRequest 32
```

**Comment by smaldini** [comment]
if you have SLF4J enable DEBUG on reactor.ipc.netty and paste the trace if you can. I'll try to have a look next week otherwise.

**Comment by Crystark** [comment]
There you go. From server start to execution of request.
```
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ testreactornetty ---
2017-03-20 10:33:08 DEBUG InternalLoggerFactory:71 - Using SLF4J as the default logging framework
2017-03-20 10:33:08 DEBUG PlatformDependent:76 - -Dio.netty.noUnsafe: false
2017-03-20 10:33:08 DEBUG PlatformDependent0:71 - java.nio.Buffer.address: available
2017-03-20 10:33:08 DEBUG PlatformDependent0:71 - sun.misc.Unsafe.theUnsafe: available
2017-03-20 10:33:08 DEBUG PlatformDependent0:71 - sun.misc.Unsafe.copyMemory: available
2017-03-20 10:33:08 DEBUG PlatformDependent0:71 - direct buffer constructor: available
2017-03-20 10:33:08 DEBUG PlatformDependent0:76 - java.nio.Bits.unaligned: available, true
2017-03-20 10:33:08 DEBUG PlatformDependent0:76 - java.nio.DirectByteBuffer.<init>(long, int): available
2017-03-20 10:33:08 DEBUG Cleaner0:76 - java.nio.ByteBuffer.cleaner(): available
2017-03-20 10:33:08 DEBUG PlatformDependent:76 - Java version: 8
2017-03-20 10:33:08 DEBUG PlatformDependent:76 - sun.misc.Unsafe: available
2017-03-20 10:33:08 DEBUG PlatformDependent:76 - -Dio.netty.noJavassist: false
2017-03-20 10:33:08 DEBUG PlatformDependent:71 - Javassist: unavailable
2017-03-20 10:33:08 DEBUG PlatformDependent:71 - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
2017-03-20 10:33:08 DEBUG PlatformDependent:76 - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
2017-03-20 10:33:08 DEBUG PlatformDependent:76 - -Dio.netty.bitMode: 64 (sun.arch.data.model)
2017-03-20 10:33:08 DEBUG PlatformDependent:76 - -Dio.netty.noPreferDirect: false
2017-03-20 10:33:08 DEBUG PlatformDependent:76 - io.netty.maxDirectMemory: 7484735488 bytes
2017-03-20 10:33:08 DEBUG OpenSsl:71 - netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
2017-03-20 10:33:08 DEBUG JdkSslContext:76 - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1]
2017-03-20 10:33:08 DEBUG JdkSslContext:76 - Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA]
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.numHeapArenas: 16
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.numDirectArenas: 16
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.pageSize: 8192
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.maxOrder: 11
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.chunkSize: 16777216
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.tinyCacheSize: 512
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.smallCacheSize: 256
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.normalCacheSize: 64
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.cacheTrimInterval: 8192
2017-03-20 10:33:08 DEBUG PooledByteBufAllocator:76 - -Dio.netty.allocator.useCacheForAllThreads: true
2017-03-20 10:33:08 DEBUG MultithreadEventLoopGroup:76 - -Dio.netty.eventLoopThreads: 16
2017-03-20 10:33:08 DEBUG NioEventLoop:76 - -Dio.netty.noKeySetOptimization: false
2017-03-20 10:33:08 DEBUG NioEventLoop:76 - -Dio.netty.selectorAutoRebuildThreshold: 512
2017-03-20 10:33:08 DEBUG PlatformDependent:71 - org.jctools-core.MpscChunkedArrayQueue: available
2017-03-20 10:33:08 DEBUG Loggers$LoggerFactory:120 - Using Slf4j logging framework
2017-03-20 10:33:08 DEBUG NativeLibraryLoader:71 - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
2017-03-20 10:33:08 DEBUG NativeLibraryLoader:71 - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
2017-03-20 10:33:08 DEBUG NativeLibraryLoader:81 - Unable to load the library 'netty-transport-native-epoll', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty-transport-native-epoll in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:273)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:264)
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:252)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:199)
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:269)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:64)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at reactor.ipc.netty.resources.DefaultLoopEpollDetector.<clinit>(DefaultLoopEpollDetector.java:47)
        at reactor.ipc.netty.resources.LoopResources.preferNative(LoopResources.java:205)
        at reactor.ipc.netty.resources.DefaultLoopResources.onServerSelect(DefaultLoopResources.java:110)
        at reactor.ipc.netty.tcp.TcpResources.onServerSelect(TcpResources.java:138)
        at reactor.ipc.netty.options.ServerOptions.groupAndChannel(ServerOptions.java:270)
        at reactor.ipc.netty.options.ServerOptions.get(ServerOptions.java:122)
        at reactor.ipc.netty.tcp.TcpServer.lambda$newHandler$1(TcpServer.java:144)
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:47)
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:2700)
        at reactor.core.publisher.Mono.subscribe(Mono.java:2661)
        at reactor.core.publisher.Mono.subscribe(Mono.java:2636)
        at reactor.core.publisher.Mono.subscribe(Mono.java:2594)
        at testreactornetty.Server.<init>(Server.java:65)
        at testreactornetty.Server.main(Server.java:40)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
2017-03-20 10:33:08 DEBUG DefaultLoopEpollDetector:120 - Default epoll support : false
2017-03-20 10:33:08 DEBUG DefaultChannelId:76 - -Dio.netty.processId: 13922 (auto-detected)
2017-03-20 10:33:08 DEBUG NetUtil:76 - -Djava.net.preferIPv4Stack: false
2017-03-20 10:33:08 DEBUG NetUtil:76 - -Djava.net.preferIPv6Addresses: false
2017-03-20 10:33:08 DEBUG NetUtil:86 - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
2017-03-20 10:33:08 DEBUG NetUtil:81 - /proc/sys/net/core/somaxconn: 128
2017-03-20 10:33:08 DEBUG ThreadLocalRandom:71 - -Dio.netty.initialSeedUniquifier: 0x0fb5af3c50eac072
2017-03-20 10:33:08 WARN  MacAddressUtil:136 - Failed to find a usable hardware address from the network interfaces; using random bytes: a0:cc:dc:92:4e:d5:61:23
2017-03-20 10:33:08 DEBUG DefaultChannelId:76 - -Dio.netty.machineId: a0:cc:dc:92:4e:d5:61:23 (auto-detected)
2017-03-20 10:33:08 DEBUG ResourceLeakDetector:81 - -Dio.netty.leakDetection.level: simple
2017-03-20 10:33:08 DEBUG ResourceLeakDetector:81 - -Dio.netty.leakDetection.maxRecords: 4
2017-03-20 10:33:08 DEBUG ByteBufUtil:76 - -Dio.netty.allocator.type: pooled
2017-03-20 10:33:08 DEBUG ByteBufUtil:76 - -Dio.netty.threadLocalDirectBufferSize: 65536
2017-03-20 10:33:08 DEBUG ByteBufUtil:76 - -Dio.netty.maxThreadLocalCharBufferSize: 16384
2017-03-20 10:33:08 DEBUG CloseableContextHandler:125 - Connecting new channel: AbstractBootstrap$PendingRegistrationPromise@41ab46a9(incomplete)
2017-03-20 10:33:08 INFO  Server:68 - Started on port 9100
2017-03-20 10:33:09 DEBUG HttpServer:71 - [id: 0xd03bffcc] REGISTERED
2017-03-20 10:33:09 DEBUG HttpServer:71 - [id: 0xd03bffcc] BIND: /0.0.0.0:9100
2017-03-20 10:33:09 INFO  Server:66 - received context reactor.ipc.netty.channel.ServerContextHandler@1f046905
2017-03-20 10:33:09 DEBUG HttpServer:71 - [id: 0xd03bffcc, L:/0:0:0:0:0:0:0:0:9100] ACTIVE
2017-03-20 10:33:14 DEBUG HttpServer:71 - [id: 0xd03bffcc, L:/0:0:0:0:0:0:0:0:9100] RECEIVED: [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998]
2017-03-20 10:33:14 DEBUG AbstractByteBuf:81 - -Dio.netty.buffer.bytebuf.checkAccessible: true
2017-03-20 10:33:14 DEBUG ResourceLeakDetectorFactory:76 - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@2cbdd834
2017-03-20 10:33:14 DEBUG HttpServerOperations:120 - New http connection, requesting read
2017-03-20 10:33:14 DEBUG ContextHandler:125 - After pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (ServerContextHandler#0 = reactor.ipc.netty.channel.ServerContextHandler), (reactor.left.httpDecoder = io.netty.handler.codec.http.HttpRequestDecoder), (reactor.left.httpEncoder = io.netty.handler.codec.http.HttpResponseEncoder), (reactor.left.httpServerHandler = reactor.ipc.netty.http.server.HttpServerHandler), (reactor.right.reactiveBridge = reactor.ipc.netty.channel.ChannelOperationsHandler)}
2017-03-20 10:33:14 DEBUG HttpServer:71 - [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] REGISTERED
2017-03-20 10:33:14 DEBUG HttpServer:71 - [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] ACTIVE
2017-03-20 10:33:14 DEBUG Recycler:76 - -Dio.netty.recycler.maxCapacityPerThread: 32768
2017-03-20 10:33:14 DEBUG Recycler:76 - -Dio.netty.recycler.maxSharedCapacityFactor: 2
2017-03-20 10:33:14 DEBUG Recycler:76 - -Dio.netty.recycler.linkCapacity: 16
2017-03-20 10:33:14 DEBUG Recycler:76 - -Dio.netty.recycler.ratio: 8
2017-03-20 10:33:14 DEBUG HttpServer:71 - [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] RECEIVED: 168B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 53 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d |POST / HTTP/1.1.|
|00000010| 0a 55 73 65 72 2d 41 67 65 6e 74 3a 20 63 75 72 |.User-Agent: cur|
|00000020| 6c 2f 37 2e 32 36 2e 30 0d 0a 48 6f 73 74 3a 20 |l/7.26.0..Host: |
|00000030| 65 69 67 68 74 3a 39 31 30 30 0d 0a 41 63 63 65 |eight:9100..Acce|
|00000040| 70 74 3a 20 2a 2f 2a 0d 0a 43 6f 6e 74 65 6e 74 |pt: */*..Content|
|00000050| 2d 4c 65 6e 67 74 68 3a 20 31 31 36 30 0d 0a 43 |-Length: 1160..C|
|00000060| 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 70 |ontent-Type: app|
|00000070| 6c 69 63 61 74 69 6f 6e 2f 78 2d 77 77 77 2d 66 |lication/x-www-f|
|00000080| 6f 72 6d 2d 75 72 6c 65 6e 63 6f 64 65 64 0d 0a |orm-urlencoded..|
|00000090| 45 78 70 65 63 74 3a 20 31 30 30 2d 63 6f 6e 74 |Expect: 100-cont|
|000000a0| 69 6e 75 65 0d 0a 0d 0a                         |inue....        |
+--------+-------------------------------------------------+----------------+
2017-03-20 10:33:14 DEBUG ChannelOperations:125 - [HttpServer] [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] handler is being applied: testreactornetty.Server$$Lambda$17/1662612871@3a848364
2017-03-20 10:33:14 DEBUG ChannelOperationsHandler:125 - [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] Writing object DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
transfer-encoding: chunked
2017-03-20 10:33:14 DEBUG HttpServer:71 - [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] WRITE: 47B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
|00000010| 0a 74 72 61 6e 73 66 65 72 2d 65 6e 63 6f 64 69 |.transfer-encodi|
|00000020| 6e 67 3a 20 63 68 75 6e 6b 65 64 0d 0a 0d 0a    |ng: chunked.... |
+--------+-------------------------------------------------+----------------+
2017-03-20 10:33:14 DEBUG HttpServer:71 - [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] FLUSH
2017-03-20 10:33:14 DEBUG ChannelOperationsHandler:125 - [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] Writing object { operator : "Peek" }
doOnSubscribe
doOnRequest 32
2017-03-20 10:33:14 DEBUG ChannelOperationsHandler:125 - [id: 0x93dbfc49, L:/172.16.202.246:9100 - R:/172.16.202.246:8998] Writing object DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
HTTP/1.1 100 Continue
```

This was the request:
```
curl -v -XPOST http://eight:9100 -d 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
* About to connect() to eight port 9100 (#0)
*   Trying 172.16.202.246...
* connected
* Connected to eight (172.16.202.246) port 9100 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.26.0
> Host: eight:9100
> Accept: */*
> Content-Length: 1160
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< transfer-encoding: chunked
<
* additional stuff not fine transfer.c:1037: 0 0
* Done waiting for 100-continue
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
^C
```

**Comment by mostroverkhov** [comment]
I am wondering if this should be called bug at all - 100-Continue response write `Flux` is returned in `in.receive` (upstream), but `compose()` lambda is always executed first as it does not have to wait any upstream signal (`Flux<ByteBuf>` is available already). `bb -> response.send(bb)` echoes request as response, after that 100-continue write gets a chance, but is ignored because response in written already.

**Comment by Crystark** [comment]
I see you point. FYI I'm trying to respect as much as possible the ["don't break the chain" policy](http://blog.danlew.net/2015/03/02/dont-break-the-chain/).

I'm not sure how everything works under the hood but would it be possible to start sending the response only when the first Signal of the Flux arrives ?

**Comment by mostroverkhov** [comment]
That is possible now - as you mentioned in question using `in.receive().flatMap()` - flatMap subscribes to its argument `Publisher` only after upstream pushes item. Code in question does what it supposed to, and reordering operations under the hood to fix one particular use case can be surprising and confusing.

**Comment by Crystark** [comment]
I understand that, but `flatMap` forces the instanciation of a couple more `Flux` / `Mono` and deepens the call stack. That's what I was trying to avoid by using `compose`. Maybe instead of reordering the operations under the hood, it could be an opt-in method for instance `sendOnSignal`.

Re-reading the java doc though it is clearly stated that the `send` method actually does start sending stuff so that's something I overlooked.

**Comment by simonbasle** [comment]
@Crystark doesn't this work:
```
return HttpServer.create(port).newHandler((request, response) ->  response.send(
        request.receive()
               .retain()
	);
);
```

Is it still occurring on more recent versions of reactor-netty btw?

**Comment by smaldini** [comment]
Closing for now
