### ISSUE TITLE
Handle "IllegalReferenceCountException: refCnt: 0, decrement: 1" when ByteBufFlux#aggregate

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#636]
`IllegalReferenceCountException: refCnt: 0, decrement: 1` can happen under load when there is `cancel` signal to `ByteBufFlux#aggregate` 

```
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
    at io.netty.buffer.AbstractReferenceCountedByteBuf.toLiveRealCnt(AbstractReferenceCountedByteBuf.java:190)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:142)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:133)
    at io.netty.buffer.CompositeByteBuf$Component.free(CompositeByteBuf.java:1813)
    at io.netty.buffer.CompositeByteBuf$Component.transferTo(CompositeByteBuf.java:1795)
    at io.netty.buffer.CompositeByteBuf.consolidateIfNeeded(CompositeByteBuf.java:464)
    at io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:266)
    at io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:222)
    at io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:165)
    at reactor.netty.ByteBufFlux.lambda$aggregate$7(ByteBufFlux.java:259)
```

```
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
    at io.netty.buffer.AbstractReferenceCountedByteBuf.toLiveRealCnt(AbstractReferenceCountedByteBuf.java:190)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:142)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:133)
    at io.netty.buffer.CompositeByteBuf$Component.free(CompositeByteBuf.java:1813)
    at io.netty.buffer.CompositeByteBuf.deallocate(CompositeByteBuf.java:2122)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:145)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:133)
    at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.cleanup(FluxUsing.java:331)
    at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.cancel(FluxUsing.java:325)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.cancel(FluxMapFuseable.java:351)
    at reactor.core.publisher.FluxHandle$HandleSubscriber.cancel(FluxHandle.java:260)
    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1935)
    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1904)
    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1716)
    at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:287)
    at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273)
    at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390)
    at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
    at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
    at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

Related to https://github.com/spring-projects/spring-framework/issues/22384

**Comment by RajyalaxmiK** [comment]
Hey, 
I faced a big problem with Spring Boot 2.2.2.Release and Cloudfoundry with Reactor,

Thank god, after 10 days I found the solution & its worked.
Below are the dependencies I used


		<dependency>
			<groupId>org.cloudfoundry</groupId>
			<artifactId>cloudfoundry-client-reactor</artifactId>
			<version>4.1.0.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.cloudfoundry</groupId>
			<artifactId>cloudfoundry-operations</artifactId>
			<version>4.1.0.RELEASE</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>spring-boot-starter-reactor-netty</artifactId>
					<groupId>org.springframework.boot</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
		</dependency>
