### ISSUE TITLE
After upgrade of reactor-netty from 0.8.3 to 0.8.8 got some tests broken in _feign-reactive_ project

### ISSUE THREAD

**Issue by kptfh** [reactor/reactor-netty#736]
@smaldini  After upgrade of reactor-netty from 0.8.3 to 0.8.8 got some tests broken in _feign-reactive_ project with below mentioned exception.

### Steps to reproduce
Checkout project and run [test ](https://github.com/Playtika/feign-reactive/blob/feature/reactor-netty-0.8.8/feign-reactor-webclient/src/test/java/reactivefeign/webclient/allfeatures/AllFeaturesTest.java)

### Reactor Netty version
0.8.8

### JVM version
1.8

```
java.lang.UnsupportedOperationException: null
	at reactor.netty.channel.MonoSendMany$SendManyInner.addListener(MonoSendMany.java:423) ~[reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at io.netty.handler.timeout.WriteTimeoutHandler.scheduleTimeout(WriteTimeoutHandler.java:138) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.timeout.WriteTimeoutHandler.write(WriteTimeoutHandler.java:111) ~[netty-handler-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at reactor.netty.channel.MonoSendMany$SendManyInner.run(MonoSendMany.java:284) [reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at reactor.netty.channel.MonoSendMany$SendManyInner.trySchedule(MonoSendMany.java:362) [reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at reactor.netty.channel.MonoSendMany$SendManyInner.onSubscribe(MonoSendMany.java:220) [reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:53) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:59) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:7799) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.netty.channel.MonoSendMany.subscribe(MonoSendMany.java:80) [reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:146) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoIgnoreElements.subscribe(MonoIgnoreElements.java:37) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:441) [reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:470) [reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:566) [reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [netty-common-4.1.36.Final.jar:4.1.36.Final]
```

**Comment by smaldini** [comment]
Confirmed will look at it, thanks and sorry for that unfortunate regression

**Comment by kptfh** [comment]
@smaldini Do you have snapshot artifact with this issue fixed? I'd like to check all my tests against it to be sure that there are no other issues.

**Comment by bsideup** [comment]
@kptfh every master build gets deployed to `repo.spring.io/snapshot`, check the README for the details
