### ISSUE TITLE
HTTP2 request with json not working using Webflux and Netty

### ISSUE THREAD

**Issue by philwebb** [reactor/reactor-netty#744]
See https://github.com/spring-projects/spring-boot/issues/16897 for details and sample to reproduce.

Make just and endpoint that receive request in the body and you will get the same error that I have :

```
curl -X POST -k -H 'Content-Type: application/json' -i 'https://localhost.direct:10000/login' --data '{"username":"test","password":"test"}' return 500 Internal Server Error
```

```
2019-05-17 11:14:39.636 DEBUG [or-http-epoll-2] [SLOG] r.u.Loggers$Slf4JLogger                  : [id: 0xeae659cf, L:/127.0.0.1:10000 - R:/127.0.0.1:55538](H2 - 15) Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
2019-05-17 11:14:39.708 DEBUG [or-http-epoll-2] [SLOG] o.s.c.l.CompositeLog                     : [eae659cf/1] Resolved [IllegalArgumentException: Object io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame@b288dcc of type class io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame cannot be converted to ByteBuf] for HTTP POST /login
2019-05-17 11:14:39.708 ERROR [or-http-epoll-2] [SLOG] o.s.c.l.CompositeLog                     : [eae659cf/1] 500 Server Error for HTTP POST "/login"

java.lang.IllegalArgumentException: Object io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame@b288dcc of type class io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame cannot be converted to ByteBuf
	at reactor.netty.ByteBufFlux.lambda$static$10(ByteBufFlux.java:322)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:206)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:322)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:335)
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:463)
	at reactor.netty.http.server.HttpToH2Operations.onInboundNext(HttpToH2Operations.java:73)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at reactor.netty.http.server.Http2StreamBridgeHandler.channelRead(Http2StreamBridgeHandler.java:90)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.handler.codec.http2.Http2MultiplexCodec$DefaultHttp2StreamChannel$Http2ChannelUnsafe.doRead0(Http2MultiplexCodec.java:1062)
	at io.netty.handler.codec.http2.Http2MultiplexCodec$DefaultHttp2StreamChannel.fireChildRead(Http2MultiplexCodec.java:771)
	at io.netty.handler.codec.http2.Http2MultiplexCodec.onHttp2Frame(Http2MultiplexCodec.java:234)
	at io.netty.handler.codec.http2.Http2FrameCodec$FrameListener.onWindowUpdateRead(Http2FrameCodec.java:549)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onWindowUpdateRead(DefaultHttp2ConnectionDecoder.java:541)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onWindowUpdateRead(DefaultHttp2ConnectionDecoder.java:703)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readWindowUpdateFrame(DefaultHttp2FrameReader.java:601)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:275)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:148)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:242)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.handler.codec.http2.Http2MultiplexCodec.channelRead(Http2MultiplexCodec.java:401)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1239)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1276)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ com.iwellsite.core.security.authentication.LoginWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/login" [ExceptionHandlingWebHandler]


2019-05-17 11:14:39.742 DEBUG [or-http-epoll-2] [SLOG] o.s.c.l.CompositeLog                     : [eae659cf/1] Encoding [{timestamp=Fri May 17 11:14:39 MDT 2019, path=/login, status=500, error=Internal Server Error, messa (truncated)...]
2019-05-17 11:14:39.846 DEBUG [or-http-epoll-2] [SLOG] r.u.Loggers$Slf4JLogger                  : [id: 0xeae659cf, L:/127.0.0.1:10000 - R:/127.0.0.1:55538](H2 - 15) Dropping frame DefaultLastHttpContent(data: UnpooledSlicedByteBuf(ridx: 0, widx: 37, cap: 37/37, unwrapped: PooledUnsafeDirectByteBuf(ridx: 435, widx: 444, cap: 560)), decoderResult: success), 0 in buffer
2019-05-17 11:14:39.848 DEBUG [or-http-epoll-2] [SLOG] i.n.c.DefaultChannelPipeline             : Discarded inbound message DefaultHttp2SettingsAckFrame that reached at the tail of the pipeline. Please check your pipeline configuration.
```

**Comment by philwebb** [comment]
This is the HTTP2 configuration we set

https://github.com/spring-projects/spring-boot/blob/cce8c45ae63d2d10f781963e40b6a65c18abc112/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/netty/SslServerCustomizer.java#L65

**Comment by violetagg** [comment]
@belkirdi I cannot find Spring Boot version that you are using neither here in this issue nor in the original issue.

I tried the example that you provided and it is working with Spring Boot `2.1.5.RELEASE`

What JDK you are using and what you are using for ALPN?

I tried with JDK 8 and 
```
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative-boringssl-static</artifactId>
			<version>2.0.25.Final</version>
		</dependency>
```

**Comment by belkirdi** [comment]
@violetagg I am using spring 2.2.0.M3 and openjdk 11
