### ISSUE TITLE
Error “reactiveBridge is not installed” 

### ISSUE THREAD

**Issue by benitocm** [reactor/reactor-netty#768]
Hi,

I have a Spring Boot 2.1.5 reactive service. That service basically receives from client devices a high rate of small packets (50 bytes long) through websocket connections and forwards them to another external service through websocket connections. 
We are seeing sometims that the following error:
“reactiveBridge is not installed”

The only clue that we have is that it seems more probable to happen after a long websocket handshake with the external service.

Any clue about what is causing that error?

**Comment by benitocm** [comment]
For testing that service, we did a reactive test driver based on the same Spring Boot version. This test drive basically open websocket connections against the service under test and injects the small messages to that service. We have obtained the same error with the following stacktrace:
java.lang.NullPointerException: reactiveBridge is not installed
at java.util.Objects.requireNonNull(Objects.java:228)
at reactor.netty.channel.MonoSend.<init>(MonoSend.java:49)
at reactor.netty.channel.MonoSendMany.<init>(MonoSendMany.java:73)
at reactor.netty.channel.MonoSendMany.objectSource(MonoSendMany.java:62)
at reactor.netty.channel.ChannelOperations.sendObject(ChannelOperations.java:248)
at org.springframework.web.reactive.socket.adapter.ReactorNettyWebSocketSession.send(ReactorNettyWebSocketSession.java:94)
at com.miviewtv.simulators.wsstb.GwClientWebSocketHandler.lambda$9(GwClientWebSocketHandler.java:183)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:350)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:275)
at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:849)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1510)
at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.signal(MonoDelayUntil.java:211)
at reactor.core.publisher.MonoDelayUntil$DelayUntilTrigger.onComplete(MonoDelayUntil.java:290)
at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:118)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by violetagg** [comment]
@benitocm Do you cache `ReactorNettyWebSocketSession`?
When sending a close frame, the `reactiveBridge` is removed from the pipeline:
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java#L205

**Comment by violetagg** [comment]
@benitocm with #776 I removed the code that removes the reactive bridge from the pipeline.
So now if you use a cached `ReactorNettyWebSocketSession` and try to send something when a connection is closed you should receive an exception pointing that the connection is closed.
