### ISSUE TITLE
`httpServerResponse.sendString(Mono.error(...))` stucks

### ISSUE THREAD

**Issue by tokuhirom** [reactor/reactor-netty#8]
reactor-netty doesn't handle `httpServerResponse.sendString(Mono.error(new IllegalArgumentException()))` correctly.

Reproduction code is here:

```java
package reactor.ipc.netty.http;

import org.junit.Test;
import reactor.core.publisher.Mono;
import reactor.ipc.netty.NettyState;
import reactor.ipc.netty.config.ClientOptions;

import java.nio.charset.StandardCharsets;

public class HttpErrorTests {
    @Test
    public void test() {
        NettyState server = HttpServer.create(0).newRouter(httpServerRoutes
                -> httpServerRoutes.get("/", (httpServerRequest, httpServerResponse) -> {
            return httpServerResponse.sendString(Mono.error(new IllegalArgumentException()));
        })).block();
        HttpClient client = HttpClient.create(ClientOptions.to("localhost", server.address().getPort()));
        client.get("/")
                .flatMap(httpClientResponse -> {
                    return httpClientResponse.receive()
                            .asString(StandardCharsets.UTF_8)
                            .collectList();
                })
                .doOnNext(it -> System.out.println("GOT!!!!!!" + it))
                .doOnError(Throwable::printStackTrace)
                .blockLast();
        server.dispose();
    }
}
```

Output log is:

```
11:13:52.025 [main] DEBUG r.ipc.netty.util.NettyNativeDetector - Default Netty Epoll support : false
11:13:52.028 [main] DEBUG reactor.ipc.netty.tcp.TcpServer - Server is not managed (Not directly introspectable)
11:13:52.488 [reactor-tcp-server-select-1] DEBUG reactor.ipc.netty.tcp.TcpServer - BIND OK /0:0:0:0:0:0:0:0:65069
11:13:52.800 [reactor-tcp-client-io-1] DEBUG reactor.ipc.netty.http.HttpClient - [id: 0x26b03022] REGISTERED
11:13:52.801 [reactor-tcp-client-io-1] DEBUG reactor.ipc.netty.http.HttpClient - [id: 0x26b03022] CONNECT: localhost/127.0.0.1:65069
11:13:52.807 [reactor-tcp-server-io-2] DEBUG reactor.ipc.netty.tcp.TcpServer - CONNECT [id: 0xc8e06f1d, L:/127.0.0.1:65069 - R:/127.0.0.1:65070]
11:13:52.809 [reactor-tcp-client-io-1] DEBUG reactor.ipc.netty.tcp.TcpClient - CONNECT OK localhost/127.0.0.1:65069
11:13:52.809 [reactor-tcp-client-io-1] DEBUG reactor.ipc.netty.http.HttpClient - [id: 0x26b03022, L:/127.0.0.1:65070 - R:localhost/127.0.0.1:65069] ACTIVE
11:13:52.817 [reactor-tcp-server-io-2] DEBUG reactor.ipc.netty.http.HttpServer - [id: 0xc8e06f1d, L:/127.0.0.1:65069 - R:/127.0.0.1:65070] REGISTERED
11:13:52.817 [reactor-tcp-server-io-2] DEBUG reactor.ipc.netty.http.HttpServer - [id: 0xc8e06f1d, L:/127.0.0.1:65069 - R:/127.0.0.1:65070] ACTIVE
11:13:52.838 [reactor-tcp-client-io-1] DEBUG reactor.ipc.netty.http.HttpClient - [id: 0x26b03022, L:/127.0.0.1:65070 - R:localhost/127.0.0.1:65069] WRITE: 48B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a |GET / HTTP/1.1..|
|00000010| 68 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 74 0d |host: localhost.|
|00000020| 0a 61 63 63 65 70 74 3a 20 2a 2f 2a 0d 0a 0d 0a |.accept: */*....|
+--------+-------------------------------------------------+----------------+
11:13:52.839 [reactor-tcp-client-io-1] DEBUG reactor.ipc.netty.http.HttpClient - [id: 0x26b03022, L:/127.0.0.1:65070 - R:localhost/127.0.0.1:65069] FLUSH
11:13:52.843 [reactor-tcp-server-io-2] DEBUG reactor.ipc.netty.http.HttpServer - [id: 0xc8e06f1d, L:/127.0.0.1:65069 - R:/127.0.0.1:65070] RECEIVED: 48B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a |GET / HTTP/1.1..|
|00000010| 68 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 74 0d |host: localhost.|
|00000020| 0a 61 63 63 65 70 74 3a 20 2a 2f 2a 0d 0a 0d 0a |.accept: */*....|
+--------+-------------------------------------------------+----------------+
11:13:52.861 [reactor-tcp-server-io-2] DEBUG reactor.ipc.netty.http.HttpServer - [id: 0xc8e06f1d, L:/127.0.0.1:65069 - R:/127.0.0.1:65070] WRITE: 66B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
|00000010| 0a 74 72 61 6e 73 66 65 72 2d 65 6e 63 6f 64 69 |.transfer-encodi|
|00000020| 6e 67 3a 20 63 68 75 6e 6b 65 64 0d 0a 63 6f 6e |ng: chunked..con|
|00000030| 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a |nection: close..|
|00000040| 0d 0a                                           |..              |
+--------+-------------------------------------------------+----------------+
11:13:52.861 [reactor-tcp-server-io-2] DEBUG reactor.ipc.netty.http.HttpServer - [id: 0xc8e06f1d, L:/127.0.0.1:65069 - R:/127.0.0.1:65070] FLUSH
11:13:52.867 [reactor-tcp-client-io-1] DEBUG reactor.ipc.netty.http.HttpClient - [id: 0x26b03022, L:/127.0.0.1:65070 - R:localhost/127.0.0.1:65069] RECEIVED: 66B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
|00000010| 0a 74 72 61 6e 73 66 65 72 2d 65 6e 63 6f 64 69 |.transfer-encodi|
|00000020| 6e 67 3a 20 63 68 75 6e 6b 65 64 0d 0a 63 6f 6e |ng: chunked..con|
|00000030| 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a |nection: close..|
|00000040| 0d 0a                                           |..              |
+--------+-------------------------------------------------+----------------+
11:13:52.869 [reactor-tcp-client-io-1] DEBUG r.i.netty.http.HttpClientOperations - Received response (auto-read:false) : io.netty.handler.codec.http.DefaultHttpHeaders@bfebfb1b
Got response
200 OK
11:13:52.881 [reactor-tcp-server-io-2] ERROR r.ipc.netty.channel.NettyOperations - Write error
java.lang.IllegalArgumentException: null
	at reactor.ipc.netty.http.HttpErrorTests.lambda$null$0(HttpErrorTests.java:16) ~[test/:na]
	at reactor.ipc.netty.http.DefaultHttpServerRoutes$HttpRouteHandler.apply(DefaultHttpServerRoutes.java:80) ~[main/:na]
	at reactor.ipc.netty.http.DefaultHttpServerRoutes$HttpRouteHandler.apply(DefaultHttpServerRoutes.java:60) ~[main/:na]
	at reactor.ipc.netty.http.HttpServer.routeRequestResponse(HttpServer.java:214) ~[main/:na]
	at reactor.ipc.netty.http.HttpServer.lambda$newRouter$0(HttpServer.java:139) ~[main/:na]
	at reactor.ipc.netty.http.HttpServerOperations.onNext(HttpServerOperations.java:199) ~[main/:na]
	at reactor.ipc.netty.channel.NettyChannelHandler.channelRead(NettyChannelHandler.java:69) [main/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) [netty-all-4.1.3.Final.jar:4.1.3.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
11:13:52.883 [reactor-tcp-server-io-2] DEBUG r.ipc.netty.channel.NettyOperations - Pausing read due to lack of request
11:13:52.883 [reactor-tcp-server-io-2] DEBUG reactor.ipc.netty.http.HttpServer - [id: 0xc8e06f1d, L:/127.0.0.1:65069 - R:/127.0.0.1:65070] WRITE: 0B
11:13:52.884 [reactor-tcp-server-io-2] DEBUG reactor.ipc.netty.http.HttpServer - [id: 0xc8e06f1d, L:/127.0.0.1:65069 - R:/127.0.0.1:65070] FLUSH
11:13:52.885 [reactor-tcp-server-io-2] ERROR r.i.netty.http.HttpServerOperations - Error processing connection. Closing the channel.
java.lang.IllegalArgumentException: null
	at reactor.ipc.netty.http.HttpErrorTests.lambda$null$0(HttpErrorTests.java:16) ~[test/:na]
	at reactor.ipc.netty.http.DefaultHttpServerRoutes$HttpRouteHandler.apply(DefaultHttpServerRoutes.java:80) ~[main/:na]
	at reactor.ipc.netty.http.DefaultHttpServerRoutes$HttpRouteHandler.apply(DefaultHttpServerRoutes.java:60) ~[main/:na]
	at reactor.ipc.netty.http.HttpServer.routeRequestResponse(HttpServer.java:214) ~[main/:na]
	at reactor.ipc.netty.http.HttpServer.lambda$newRouter$0(HttpServer.java:139) ~[main/:na]
	at reactor.ipc.netty.http.HttpServerOperations.onNext(HttpServerOperations.java:199) ~[main/:na]
	at reactor.ipc.netty.channel.NettyChannelHandler.channelRead(NettyChannelHandler.java:69) ~[main/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_77]
11:13:52.886 [reactor-tcp-client-io-1] DEBUG r.ipc.netty.channel.NettyOperations - Pausing read due to lack of request
11:13:52.886 [reactor-tcp-client-io-1] DEBUG r.ipc.netty.channel.NettyOperations - Subscribing inbound receiver [pending: 0, done: false]
```

The log says `Error processing connection. Closing the channel.` but it doesn't close the socket.

As a result, client request stucks forever.

```
$ curl -vvv http://localhost:65069/
*   Trying ::1...
* Connected to localhost (::1) port 65069 (#0)
> GET / HTTP/1.1
> Host: localhost:65069
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< transfer-encoding: chunked
< connection: close
<
```

[![https://gyazo.com/d6b920d1126f423bb97d2c2a273aa290](https://i.gyazo.com/d6b920d1126f423bb97d2c2a273aa290.gif)](https://gyazo.com/d6b920d1126f423bb97d2c2a273aa290)

**Comment by smaldini** [comment]
@tokuhirom updated your test and added it, with the latest api updates to be released.

**Comment by tokuhirom** [comment]
Thanks!
