### ISSUE TITLE
Chaining methods in NettyOutbound has weird results

### ISSUE THREAD

**Issue by nictas** [reactor/reactor-netty#811]
This is a continuation of a discussion that started on [Gitter](https://gitter.im/reactor/reactor-netty).

I'm trying to migrate an [existing project](https://github.com/cloudfoundry/cf-java-client) from Reactor Netty 0.7.x to 0.8.10. In it, there's this class that's supposed to generate multipart upload requests with a **body** with the following structure:
```
-- BOUNDARY
content-disposition: form-data; name="<name>"; filename="<filename>"
content-length: 12
content-type: application/zip

<file content>
-- BOUNDARY
content-disposition: form-data; name="<name>"; filename="<filename>"
content-length: 354
content-type: application/zip

<file content>
-- BOUNDARY --
```
Each "part" has a dedicated section containing some "headers" and the actual file content that needs to be uploaded. The sections themselves are separated by a delimiter (`-- BOUNDARY`) and after the last part there's a special delimiter, that's the same as the other one but with `--` at the end.

With version 0.7.x the code looked like this (`outbound` is of type `NettyOutbound`):
```
for (PartHttpClientoutbound part : parts) {
    outbound = outbound.sendObject(Unpooled.wrappedBuffer(delimiter.toByteArray()));
    outbound = outbound.sendObject(Unpooled.wrappedBuffer(CRLF.toByteArray()));
    outbound = outbound.sendObject(part.renderedHeaders);
    outbound = outbound.sendFile(part.file);
}
outbound = outbound.sendObject(Unpooled.wrappedBuffer(closeDelimiter.toByteArray()));
```
With version 0.8.10 the same code compiles, but the request that gets sent contains only a part of what is expected. The following class can be used to reproduce/illustrate the issue (the headers are omitted for brevity):
```
package org.cloudfoundry.reactor.util;

import static io.netty.handler.codec.http.HttpHeaderNames.CONTENT_TYPE;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;

import org.reactivestreams.Publisher;

import io.netty.buffer.Unpooled;
import io.netty.handler.codec.http.HttpHeaderValues;
import io.netty.util.AsciiString;
import reactor.netty.NettyOutbound;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientRequest;

public class Reproduce {

    private static final AsciiString CRLF = new AsciiString("\r\n");
    private static final AsciiString DOUBLE_DASH = new AsciiString("--");

    public static void main(String[] args) throws IOException {
        String response = HttpClient.create()
                                    .post()
                                    .uri("https://postman-echo.com/post")
                                    .send(Reproduce::sendGeneratedContent)
                                    .responseContent()
                                    .aggregate()
                                    .asString()
                                    .block();
        System.out.println(response);
    }

    private static Publisher<Void> sendGeneratedContent(HttpClientRequest request, NettyOutbound outbound) {
        try {
            AsciiString boundary = new AsciiString("xkVpCHkqWbNBJT6_bW8venxnA6mBYmAz");
            AsciiString delimiter = getDelimiter(boundary);
            AsciiString closeDelimiter = getCloseDelimiter(boundary);

            request.header(CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);

            for (Path part : generateParts()) {
                outbound = sendPart(outbound, part, delimiter);
            }
            return outbound.sendObject(Unpooled.wrappedBuffer(closeDelimiter.toByteArray()));
        } catch (IOException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }

    private static AsciiString getDelimiter(AsciiString boundary) {
        return CRLF.concat(DOUBLE_DASH)
                   .concat(boundary);
    }

    private static AsciiString getCloseDelimiter(AsciiString boundary) {
        return CRLF.concat(DOUBLE_DASH)
                   .concat(boundary)
                   .concat(DOUBLE_DASH);
    }

    private static List<Path> generateParts() throws IOException {
        return Arrays.asList(generatePart("foo"));
    }

    private static Path generatePart(String content) throws IOException {
        Path part = Files.createTempFile(null, null);
        try (BufferedWriter writer = Files.newBufferedWriter(part)) {
            writer.write(content);
        }
        return part;
    }

    private static NettyOutbound sendPart(NettyOutbound outbound, Path part, AsciiString delimiter) {
        return outbound.sendObject(Unpooled.wrappedBuffer(delimiter.toByteArray()))
                       .sendObject(Unpooled.wrappedBuffer(CRLF.toByteArray()))
                       .sendFile(part);
    }

}
```
The request's body contains just the content after `NettyOutbound#sendFile`.
Expected:
```
--xkVpCHkqWbNBJT6_bW8venxnA6mBYmAz
foo
--xkVpCHkqWbNBJT6_bW8venxnA6mBYmAz--
```
Actual:
```
foo
--xkVpCHkqWbNBJT6_bW8venxnA6mBYmAz--
```
It's like that call erased every previous call to `NettyOutbound`. Furthermore, if I try to add even one more file to the request, everything goes horribly wrong and I get the following exception:
```
Exception in thread "main" io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:305)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:135)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
	at reactor.netty.http.HttpOperations.lambda$sendObject$1(HttpOperations.java:124)
	at reactor.netty.FutureMono$DeferredFutureMono.subscribe(FutureMono.java:162)
	at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:71)
	at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:71)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3848)
	at reactor.netty.NettyOutbound.subscribe(NettyOutbound.java:307)
	at reactor.core.publisher.MonoSource.subscribe(MonoSource.java:51)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3848)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3848)
	at reactor.netty.NettyOutbound.subscribe(NettyOutbound.java:307)
	at reactor.core.publisher.MonoSource.subscribe(MonoSource.java:51)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3848)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3848)
	at reactor.netty.NettyOutbound.subscribe(NettyOutbound.java:307)
	at reactor.core.publisher.MonoSource.subscribe(MonoSource.java:51)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:443)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:470)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:512)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:451)
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:62)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelActive(CombinedChannelDuplexHandler.java:414)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.CombinedChannelDuplexHandler.channelActive(CombinedChannelDuplexHandler.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1530)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1494)
		at org.cloudfoundry.reactor.util.Reproduce.main(Reproduce.java:34)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	... 80 more
```
This is also easily reproducible by modifying the `generateParts` method to:
```
    private static List<Path> generateParts() throws IOException {
        return Arrays.asList(generatePart("foo"), generatePart("bar"));
    }
```
@violetagg suggested a really nice workaround, which makes use of the `NettyOutbound#send` method in conjunction with `ByteBufFlux#fromPath`:
```
package org.cloudfoundry.reactor.util;

import static io.netty.handler.codec.http.HttpHeaderNames.CONTENT_TYPE;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;

import org.reactivestreams.Publisher;

import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.handler.codec.http.HttpHeaderValues;
import io.netty.util.AsciiString;
import reactor.core.publisher.Flux;
import reactor.netty.ByteBufFlux;
import reactor.netty.NettyOutbound;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientRequest;

public class Reproduce {

    private static final AsciiString CRLF = new AsciiString("\r\n");
    private static final AsciiString DOUBLE_DASH = new AsciiString("--");

    public static void main(String[] args) throws IOException {
        String response = HttpClient.create()
                                    .post()
                                    .uri("https://postman-echo.com/post")
                                    .send(Reproduce::sendGeneratedContent)
                                    .responseContent()
                                    .aggregate()
                                    .asString()
                                    .block();
        System.out.println(response);
    }

    private static Publisher<Void> sendGeneratedContent(HttpClientRequest request, NettyOutbound outbound) {
        try {
            AsciiString boundary = new AsciiString("xkVpCHkqWbNBJT6_bW8venxnA6mBYmAz");
            AsciiString delimiter = getDelimiter(boundary);
            AsciiString closeDelimiter = getCloseDelimiter(boundary);

            request.header(CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);

            Flux<ByteBuf> body = Flux.empty();
            for (Path part : generateParts()) {
                body = addPart(body, part, delimiter);
            }
            body = body.concatWithValues(Unpooled.wrappedBuffer(closeDelimiter.toByteArray()));
            return outbound.send(body);
        } catch (IOException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }

    private static AsciiString getDelimiter(AsciiString boundary) {
        return CRLF.concat(DOUBLE_DASH)
                   .concat(boundary);
    }

    private static AsciiString getCloseDelimiter(AsciiString boundary) {
        return CRLF.concat(DOUBLE_DASH)
                   .concat(boundary)
                   .concat(DOUBLE_DASH);
    }

    private static List<Path> generateParts() throws IOException {
        return Arrays.asList(generatePart("foo"), generatePart("bar"));
    }

    private static Path generatePart(String content) throws IOException {
        Path part = Files.createTempFile(null, null);
        try (BufferedWriter writer = Files.newBufferedWriter(part)) {
            writer.write(content);
        }
        return part;
    }

    private static Flux<ByteBuf> addPart(Flux<ByteBuf> body, Path part, AsciiString delimiter) {
        return body.concatWithValues(Unpooled.wrappedBuffer(delimiter.toByteArray()))
                   .concatWithValues(Unpooled.wrappedBuffer(CRLF.toByteArray()))
                   .concatWith(ByteBufFlux.fromPath(part));
    }

}
```
This works almost perfectly (even with more than one file), but has one major flaw, which prevents us from using it. `ByteBufFlux#fromPath` apparently loads the entire file in-memory before uploading it, which leads to `OutOfDirectMemoryErrors` for large files. Scaling the direct memory is not an option, since we upload hundreds of files each minute that can be up to 1 GB in size **each**.

For us, this means that we cannot migrate from Reactor Netty 0.7.x to 0.8.10 as this will be a major gap in the two versions (one would be able to scale and the other not so much).

## Your Environment

* Reactor version(s) used: 0.8.10.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): Reactor core: 3.2.10.RELEASE
* JVM version (`javar -version`): 1.8
* OS and version (eg `uname -a`): Windows 10, but also:
Linux 0a11e1d5-6f0b-4efa-7045-8ecc 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
@nictas 
The code below works for me (using `send` instead of `sendObject`).
I see the following response:

```
{
    "args":{},
    "data":"\r\n--xkVpCHkqWbNBJT6_bW8venxnA6mBYmAz\r\nfoo\r\n--xkVpCHkqWbNBJT6_bW8venxnA6mBYmAz--",
    "files":{},
    "form":{},
    "headers":{
        "x-forwarded-proto":"https",
        "host":"postman-echo.com",
        "content-length":"79",
        "accept":"*/*",
        "content-type":"text/plain",
        "user-agent":"ReactorNetty/dev",
        "x-forwarded-port":"443"
    },
    "json":null,
    "url":"https://postman-echo.com/post"
}
```

```
import io.netty.buffer.Unpooled;
import io.netty.handler.codec.http.HttpHeaderValues;
import io.netty.util.AsciiString;
import org.reactivestreams.Publisher;
import reactor.core.publisher.Flux;
import reactor.netty.http.client.HttpClient;
import reactor.netty.http.client.HttpClientRequest;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;

import static io.netty.handler.codec.http.HttpHeaderNames.CONTENT_TYPE;

public class Reproduce {

    private static final AsciiString CRLF = new AsciiString("\r\n");
    private static final AsciiString DOUBLE_DASH = new AsciiString("--");

    public static void main(String[] args) throws IOException {
        String response = HttpClient.create()
                                    .wiretap(true)
                                    .post()
                                    .uri("https://postman-echo.com/post")
                                    .send(Reproduce::sendGeneratedContent)
                                    .responseContent()
                                    .aggregate()
                                    .asString()
                                    .block();
        System.out.println(response);
    }

    private static Publisher<Void> sendGeneratedContent(HttpClientRequest request, NettyOutbound outbound) {
        try {
            AsciiString boundary = new AsciiString("xkVpCHkqWbNBJT6_bW8venxnA6mBYmAz");
            AsciiString delimiter = getDelimiter(boundary);
            AsciiString closeDelimiter = getCloseDelimiter(boundary);

            request.header(CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);

            for (Path part : generateParts()) {
                outbound = sendPart(outbound, part, delimiter);
            }
            return outbound.send(Flux.just(Unpooled.wrappedBuffer(closeDelimiter.toByteArray())));
        } catch (IOException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }

    private static AsciiString getDelimiter(AsciiString boundary) {
        return CRLF.concat(DOUBLE_DASH)
                   .concat(boundary);
    }

    private static AsciiString getCloseDelimiter(AsciiString boundary) {
        return CRLF.concat(DOUBLE_DASH)
                   .concat(boundary)
                   .concat(DOUBLE_DASH);
    }

    private static List<Path> generateParts() throws IOException {
        return Arrays.asList(generatePart("foo"));
    }

    private static Path generatePart(String content) throws IOException {
        Path part = Files.createTempFile(null, null);
        try (BufferedWriter writer = Files.newBufferedWriter(part)) {
            writer.write(content);
        }
        return part;
    }

    private static NettyOutbound sendPart(NettyOutbound outbound, Path part, AsciiString delimiter) {
        return outbound.send(Flux.just(Unpooled.wrappedBuffer(delimiter.toByteArray()), Unpooled.wrappedBuffer(CRLF.toByteArray())))
                       .sendFile(part);
    }

}
```

**Comment by nictas** [comment]
Yes, the workaround seems to work (at least the unit tests in https://github.com/cloudfoundry/cf-java-client pass)! Big thanks! I'll run some load tests to make sure that everything is working as it should and I'll update this ticket again afterwards.

I assume that you'll still fix the chaining though, right? It's still weird that I'm allowed to do:
```
outbound.send(something)
        .sendFile(somethingElse);
```
But not:
```
outbound.sendObject(something)
        .sendFile(somethindElse);
```

**Comment by violetagg** [comment]
> I assume that you'll still fix the chaining though, right? It's still weird that I'm allowed to do:
> 
> ```
> outbound.send(something)
>         .sendFile(somethingElse);
> ```
> 
> But not:
> 
> ```
> outbound.sendObject(something)
>         .sendFile(somethindElse);
> ```

We do not intend to change anything for 0.8.x.
For 0.9.x we are going to change NettyOutbound - the send* operations will return `Mono<Void>` and not NettyOutbound.

**Comment by violetagg** [comment]
I'm closing this one. If there is a problem with the workaround we can reopen it.
