### ISSUE TITLE
reactiveBridge is not installed

### ISSUE THREAD

**Issue by AndreasMager** [reactor/reactor-netty#821]
I am using spring-boot and found the following stacktrace repeating in the log on a dying machine.

#768 seem to be similar.

```
pool-2-thread-1 WebSocketHandler:70 - lambda$handle$2: Catching java.lang.NullPointerException: reactiveBridge is not installed
	at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at reactor.netty.channel.MonoSend.<init>(MonoSend.java:49) ~[reactor-netty-0.8.10.RELEASE.jar!/:0.8.10.RELEASE]
	at reactor.netty.channel.MonoSendMany.<init>(MonoSendMany.java:74) ~[reactor-netty-0.8.10.RELEASE.jar!/:0.8.10.RELEASE]
	at reactor.netty.channel.MonoSendMany.objectSource(MonoSendMany.java:63) ~[reactor-netty-0.8.10.RELEASE.jar!/:0.8.10.RELEASE]
	at reactor.netty.channel.ChannelOperations.sendObject(ChannelOperations.java:257) ~[reactor-netty-0.8.10.RELEASE.jar!/:0.8.10.RELEASE]
	at org.springframework.web.reactive.socket.adapter.ReactorNettyWebSocketSession.send(ReactorNettyWebSocketSession.java:92) ~[spring-webflux-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	XXXX
```

* Reactor version(s) used: reactor-netty-0.8.10.RELEASE.jar!
* Other relevant libraries versions (eg. `netty`, ...): netty 4.1.38 spring-boot 2.1.7

* JVM version (`javar -version`): 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

* OS and version (eg `uname -a`):
Linux XXX 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
@AndreasMager Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem?

**Comment by AndreasMager** [comment]
The Problem occurs when the session is closed and a thread tries to send a message.
Here is the sample https://gitlab.com/amager/websocktest/-/jobs/277733341

**Comment by AndreasMager** [comment]
Thank you @violetagg
