### ISSUE TITLE
Null returned by HttpClientOperations.status()

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#85]
Hi,

I use Spring Framework 5 WebClient. The code is the following:
```
WebClient.create().get()
        .uri(url)
        .exchange()
        .doOnError(...)
        .flatMapMany(r -> {
                int responseCode = r.statusCode().value();        <= NPE happens here
                return r.bodyToFlux(ByteBuffer.class);
        })
```

I specify also `HttpResources.set(PoolResources.elastic("elastic"))`

When under load I receive NPE from time to time when I try to obtain the status code.
```
java.lang.NullPointerException/java.lang.NullPointerException
 at org.springframework.http.client.reactive.ReactorClientHttpResponse.getStatusCode(ReactorClientHttpResponse.java:73)
 at org.springframework.web.reactive.function.client.DefaultClientResponse.statusCode(DefaultClientResponse.java:67)
 at com.example.jmeter.plugin.reactive.sampler.ReactiveWebClient.lambda$getBody$0(ReactiveWebClient.java:70)
 at reactor.core.publisher.MonoFlatMapMany$FlatMapMain.onNext(MonoFlatMapMany.java:154)
 at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:173)
 at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
 at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:173)
 at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
 at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
 at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:79)
 at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:125)
 at reactor.ipc.netty.channel.PooledClientContextHandler.fireContextActive(PooledClientContextHandler.java:83)
 at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:170)
 at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:335)
 at reactor.ipc.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:339)
 at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:415)
 at reactor.ipc.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:101)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
 at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
 at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
 at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
 at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 at java.lang.Thread.run(Thread.java:745)
```

I would expect that if there is some problem with the response I will receive an error that I will handle in  `doOnError`.

Regards,
Violeta

**Comment by violetagg** [comment]
Hi,

Here is part of the trace file with Reactor Netty traces.
[trace.txt](https://github.com/reactor/reactor-netty/files/958271/trace.txt)


Regards,
Violeta

**Comment by molk** [comment]
Is this really fixed? The following snippet shows the same NPE when under load (Groovy):

    Mono<String> retrieveWeatherData(String latitude, String longitude) {
        WebClient.create('http://api.met.no/weatherapi/locationforecast/1.9')
            .get().uri('?lat={lat}&lon={lon}', latitude, longitude)
            .exchange()
            // .bodyToMono(String)
            .flatMap { ClientResponse response ->
                // response.statusCode() -> NPE
                // DefaultClientResponse.ReactorClientHttpResponse.HttpClientOperations.status()
                if (response.response.response.status() == null) {
                    log.error 'Status code is null'
                }
               response.bodyToMono(String)
            }
    }

I am using SpringBoot M7 -> Spring 5.0.2.RELEASE -> reactor-netty 0.7.2.RELEASE

**Comment by violetagg** [comment]
Most probably you face this issue #230 
Can you try 0.7.3.BUILD-SNAPSHOT?

**Comment by molk** [comment]
Cheers. Will try the snapshot. Thanks!

**Comment by Aleksandr-Filichkin** [comment]
@molk @violetagg for the last spring boot 2.0.0.M7 helps:
<dependencyManagement>
		<dependencies>
			
			<dependency>
				<groupId>io.projectreactor.ipc</groupId>
				<artifactId>reactor-netty</artifactId>
				<version>0.7.3.RELEASE</version>
			</dependency>

		</dependencies>
	</dependencyManagement>

**Comment by violetagg** [comment]
@Aleksandr-Filichkin Do you have exceptions/connection close from the server side?

**Comment by violetagg** [comment]
Also are you able to test with the current snapshot as we did several changes.
