### ISSUE TITLE
rest service call with ssl blocks reactive thread

### ISSUE THREAD

**Issue by urferr** [reactor/reactor-netty#906]
when using Spring webflux with reactor-netty i get a blocking exception when calling another rest service using ssl. Adding allowBlockingCallsInside("io.netty.handler.ssl.SslHandler", "handshake") to the Blockhound builder can be used as workaround

Stack trace:
at reactor.blockhound.BlockHound$Builder.lambda$new$0(BlockHound.java:196)
at reactor.blockhound.BlockHound$Builder.lambda$install$6(BlockHound.java:318)
at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:46)
at java.base/java.io.FileInputStream.readBytes(FileInputStream.java)
at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
at java.base/sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
at java.base/sun.security.provider.NativePRNG$RandomIO.ensureBufferValid(NativePRNG.java:526)
at java.base/sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:545)
at java.base/sun.security.provider.NativePRNG.engineNextBytes(NativePRNG.java:220)
at java.base/java.security.SecureRandom.nextBytes(SecureRandom.java:741)
at java.base/sun.security.ssl.RandomCookie.(RandomCookie.java:67)
at java.base/sun.security.ssl.ClientHello$ClientHelloMessage.(ClientHello.java:93)
at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:639)
at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:515)
at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:104)
at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:228)
at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:103)
at io.netty.handler.ssl.SslHandler.handshake(SslHandler.java:1987)
at io.netty.handler.ssl.SslHandler.startHandshakeProcessing(SslHandler.java:1906)
at io.netty.handler.ssl.SslHandler.channelActive(SslHandler.java:2042)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:907)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)

* Reactor version(s) used: 3.3.0, reactor-netty 0.9.1
* Other relevant libraries versions: netty 4.1.43, spring 5.2.1
* JVM version (`javar -version`): openjdk version "11.0.2" 2018-10-16
* OS and version (eg `uname -a`): Linux pdvmdev15.profidatagroup.com 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
@urferr I would recommend you to report this to Netty project

**Comment by violetagg** [comment]
I'm closing this one. If it appears a Reactor Netty issue we can reopen it.

**Comment by rstoyanchev** [comment]
Link to Netty issue https://github.com/netty/netty/issues/9834.

**Comment by violetagg** [comment]
Reopening in order to evaluate the suggested solution in netty/netty#9834

**Comment by violetagg** [comment]
need more clarification here https://github.com/netty/netty/issues/9834#issuecomment-565140560

**Comment by violetagg** [comment]
@urferr Fix will be available in Netty 4.1.46.Final https://github.com/netty/netty/pull/9969
It would be great if you can test 4.1.46.Final-SNAPSHOT

**Comment by urferr** [comment]
Unfortunately i am not able to reproduce the original problem. Maybe its because some thirdparty library versions have slightly changed in the meantime:

- Reactor version(s) used: 3.3.1, reactor-netty 0.9.2
- Other relevant libraries versions: netty 4.1.43, spring 5.2.2
- JVM version (java -version): openjdk version "13.0.2"

**Comment by violetagg** [comment]
Netty updated to 4.1.46.Final 5fde036f7b81825e36e1b2c815846a54df13c2b5

**Comment by violetagg** [comment]
@estigma88 Please report this in a separate issue as it is not the same problem

**Comment by estigma88** [comment]
Created https://github.com/reactor/reactor-netty/issues/1148
