### ISSUE TITLE
timeout-triggered cancellation causes ref cnt error

### ISSUE THREAD

**Issue by vy** [reactor/reactor-netty#944]
When a `ByteBufFlux` derived `Flux` is cancelled via `Flux#take(Duration)`, `IllegalReferenceCountException` is thrown and hangs the caller. The thrown exception is logged thanks to the default `onErrorDropped`, though I could not catch the exception myself no matter what I did.

[vy/reactor-netty-ref-cnt-bug-repro](/vy/reactor-netty-ref-cnt-bug-repro) project provides an isolated test case where reproduction instructions are shared.

* Reactor version(s) used: `reactor-core-3.3.1.RELEASE`
* Other relevant libraries versions (eg. `netty`, ...): `reactor-netty-0.9.2.RELEASE`
* JVM version (`javar -version`): 13.0.1+9
* OS and version (eg `uname -a`): `Linux ... 4.15.0-70-generic #79-Ubuntu SMP ... x86_64 GNU/Linux`

**Comment by violetagg** [comment]
@vy It was a race between `handle` and `doFinally` (`reactor.netty.ByteBufFlux#aggregate`)
In `handle` there is `output.addComponent(...) (consolidateIfNeeded)` and this may release the internal buffers. In `doFinally`, `output.release()` also releases the internal buffers.
When you have such issues you can try to follow the paths where `release` might happen.

**Comment by vy** [comment]
Thanks so much for the great work and explanation, @violetagg! I still cannot explain why was the thrown `IllegalReferenceCountException` able to collapse the client given there is a `retry()`? I was expecting `BenchmarkClient` to recover and keep on pushing even after the exception.

**Comment by vy** [comment]
@violetagg, I once in while still get the following *warning*:
```
21:27:53.685 [com.vlkan.workbench.BenchmarkClient.main()] INFO  com.vlkan.workbench.BenchmarkClient - starting
21:28:03.954 [parallel-1] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: CompositeByteBuf(freed, components=2001)
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74) ~[netty-common-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138) ~[netty-common-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100) ~[netty-buffer-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.buffer.CompositeByteBuf$Component.free(CompositeByteBuf.java:1915) ~[netty-buffer-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.buffer.CompositeByteBuf.deallocate(CompositeByteBuf.java:2220) ~[netty-buffer-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:110) ~[netty-buffer-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100) ~[netty-buffer-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-common-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113) ~[netty-common-4.1.44.Final.jar:4.1.44.Final]
        at reactor.netty.ByteBufFlux.lambda$aggregate$9(ByteBufFlux.java:290) ~[reactor-netty-0.9.3.RELEASE.jar:0.9.3.RELEASE]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.cancel(FluxDoFinally.java:145) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.cancel(FluxMap.java:286) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.cancel(FluxHandle.java:259) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:160) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:500) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.cancel(FluxDoFinally.java:144) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.Operators.terminate(Operators.java:1108) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.cancel(MonoFlatMap.java:264) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:181) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:500) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.Operators.terminate(Operators.java:1108) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.cancel(FluxFlatMap.java:1008) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:332) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:212) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FlatMapTracker.unsubscribe(FluxFlatMap.java:1068) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.cancel(FluxFlatMap.java:352) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:500) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.cancel(FluxPeekFuseable.java:152) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2051) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2020) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1832) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.cancelMain(FluxTakeUntilOther.java:173) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.cancel(FluxTakeUntilOther.java:190) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onComplete(FluxTakeUntilOther.java:234) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxTakeUntilOther$TakeUntilOtherSubscriber.onComplete(FluxTakeUntilOther.java:112) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.FluxTakeUntilOther$TakeUntilOtherSubscriber.onNext(FluxTakeUntilOther.java:94) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
21:28:03.985 [com.vlkan.workbench.BenchmarkClient.main()] INFO  com.vlkan.workbench.BenchmarkClient - completed (totalResponsePayloadLength=77201408)
```
Note that the warning occurs at the end of the session, that is, after 10s. This doesn't hurt the functionality AFAIC, but doesn't leave a good taste either.

**Comment by violetagg** [comment]
@vy yep that's the `safeRelease` that we are using now.
In your case it is OK, as you can see the buffer is freed.
`Failed to release a message: CompositeByteBuf(freed, components=2001)
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1`
I don't feel like we want to remove the info for `ByteBuf.release` failure. Wdyt?

**Comment by violetagg** [comment]
> Thanks so much for the great work and explanation, @violetagg! I still cannot explain why was the thrown `IllegalReferenceCountException` able to collapse the client given there is a `retry()`? I was expecting `BenchmarkClient` to recover and keep on pushing even after the exception.

Errors in `doFinally` are dropped as the completion has already happened.

**Comment by vy** [comment]
The message is logged at level `WARN`. Receiving a warning message from such a core library creates an impression that *"something has happened that should not have happened and I better fix it as a user"*, which is not the case. Hence, I would encourage lowering it to level `DEBUG`.

**Comment by vy** [comment]
Quoting from [The DevOps Handbook](https://books.google.nl/books?id=ui8hDgAAQBAJ&pg=PT244&lpg=PT244&dq=%22These+will+likely+initiate+an+alert+and+troubleshooting,+while+other+logging+messages%22&source=bl&ots=WudlbbOtTO&sig=ACfU3U301bv3fJfkR8yqbZYNKARlXNbm-w&hl=en&sa=X&ved=2ahUKEwi26ICUjIPnAhXD0aQKHfaqAgAQ6AEwAHoECAMQAQ#v=onepage&q=%22These%20will%20likely%20initiate%20an%20alert%20and%20troubleshooting%2C%20while%20other%20logging%20messages%22&f=false):

> WARN level: Information at this level tells us of conditions that could potentially become an error (e.g., a database call taking longer than some predefined time). These will likely initiate an alert and troubleshooting, ...

**Comment by violetagg** [comment]
Try the current 0.8.16.BUILD-SNAPSHOT/0.9.4.BUILD-SNAPSHOT
