### ISSUE TITLE
NoClassDefFoundError in Cloud Foundry applications

### ISSUE THREAD

**Issue by gaathiyo** [reactor/reactor-netty#97]
For a CF application, I am using [cf java client](https://github.com/cloudfoundry/cf-java-client) which uses reactor-netty library. I use reactor-netty version 0.6.2.RELEASE for my application.

After pushing a cf application to cloud foundry, it sometimes fails at the time of class loading with following error.

```
[reactor-http-nio-1] WARN io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x13423355]
         at reactor.ipc.netty.http.client.HttpClient$TcpBridgeClient.accept(HttpClient.java:377)
         at reactor.ipc.netty.channel.ContextHandler.accept(ContextHandler.java:319)
         at reactor.ipc.netty.channel.ContextHandler.accept(ContextHandler.java:55)
         at reactor.ipc.netty.resources.DefaultPoolResources$Pool.channelCreated(DefaultPoolResources.java:177)
         at io.netty.channel.pool.SimpleChannelPool$1.initChannel(SimpleChannelPool.java:99)
         at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
         at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
         at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
         at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
         at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
         at reactor.ipc.netty.http.client.HttpClient$TcpBridgeClient.accept(HttpClient.java:377)
         at reactor.ipc.netty.channel.ContextHandler.accept(ContextHandler.java:319)
         at io.netty.channel.pool.SimpleChannelPool$1.initChannel(SimpleChannelPool.java:99)
         at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
         at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
         at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
         at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
 java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.codec.http.HttpRequestEncoder
         at reactor.ipc.netty.http.client.HttpClient$TcpBridgeClient.accept(HttpClient.java:338)
         at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
         at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
         at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
         at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
         at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
         at java.lang.Thread.run(Thread.java:748)
```

If the application starts properly then sometimes it gets following error while requesting cloud controller.

```
 io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
         at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
         at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
         at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
         at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
         at io.netty.channel.pool.SimpleChannelPool.connectChannel(SimpleChannelPool.java:251)
         at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:164)
         at io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:149)
         at io.netty.channel.pool.FixedChannelPool.acquire0(FixedChannelPool.java:230)
         at io.netty.channel.pool.FixedChannelPool.access$300(FixedChannelPool.java:37)
         at io.netty.channel.pool.FixedChannelPool$3.run(FixedChannelPool.java:204)
         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
         at java.lang.Thread.run(Thread.java:748)
 Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.DefaultChannelId
         at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
         at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
         at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
         at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:54)
         at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:98)
         at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:88)
         at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:81)
         at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:74)
         at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source)
         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
         at java.lang.Class.newInstance(Class.java:442)
         at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
         ... 14 more
         at reactor.ipc.netty.http.client.HttpClient$TcpBridgeClient.accept(HttpClient.java:338)
         at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
         at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
         at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
         at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
         at java.lang.Thread.run(Thread.java:748)
         at reactor.ipc.netty.channel.ContextHandler.accept(ContextHandler.java:55)
         at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
         at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
         at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
         at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:127)
         at io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:112)
         at io.netty.channel.pool.FixedChannelPool.decrementAndRunTaskQueue(FixedChannelPool.java:291)
         at io.netty.channel.pool.FixedChannelPool.access$600(FixedChannelPool.java:37)
         at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
         at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:438)
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
         at java.lang.Thread.run(Thread.java:748)
```

Kindly let us know about NoClassDefFoundError issue, what it is about and why it is coming and also help us with how to avoid it.

**Comment by smaldini** [comment]
It does look like the version used by cf java client is not what you expect, lets see with @nebhale.

**Comment by nebhale** [comment]
@gaathiyo Can you please ensure list the versions of the dependencies listed in our [documentation](https://github.com/cloudfoundry/cf-java-client#dependencies)?

**Comment by gaathiyo** [comment]
@nebhale We use following dependencies:

```
<dependency>
	<groupId>org.cloudfoundry</groupId>
	<artifactId>cloudfoundry-client-reactor</artifactId>
	<version>2.3.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>org.cloudfoundry</groupId>
	<artifactId>cloudfoundry-operations</artifactId>
	<version>2.3.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.projectreactor</groupId>
	<artifactId>reactor-core</artifactId>
	<version>3.0.4.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.projectreactor.ipc</groupId>
	<artifactId>reactor-netty</artifactId>
	<version>0.6.2.RELEASE</version>
</dependency>
```

Earlier we used to use reactor-netty version 0.6.0.RELEASE. But due to `Connection has been aborted by the remote peer` Exception (probably due to too many open connections), we upgraded reactor-netty to 0.6.2.RELEASE since it has [this fix](https://github.com/reactor/reactor-netty/issues/57).

Do you see any issues with above mentioned dependencies? Would you recommend to use reactor-netty 0.6.3.RELEASE for productive use?

**Comment by nebhale** [comment]
The problem isn't that you're using too new a version of `reactor-netty`, it's that Java Client 2.3.0 isn't designed to work with any `reactor-netty` version [other than the one it shipped with](https://github.com/cloudfoundry/cf-java-client/blob/v2.3.0.RELEASE/pom.xml#L60).  If you want to upgrade dependencies, you must upgrade the core dependencies in lockstep.  We're now at:

```
<dependencies>
    <dependency>
        <groupId>org.cloudfoundry</groupId>
        <artifactId>cloudfoundry-client-reactor</artifactId>
        <version>2.11.0.RELEASE</version>
    </dependency>
    <dependency>
        <groupId>org.cloudfoundry</groupId>
        <artifactId>cloudfoundry-operations</artifactId>
        <version>2.11.0.RELEASE</version>
    </dependency>
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-core</artifactId>
        <version>3.0.7.RELEASE</version>
    </dependency>
    <dependency>
        <groupId>io.projectreactor.ipc</groupId>
        <artifactId>reactor-netty</artifactId>
        <version>0.6.3.RELEASE</version>
    </dependency>
    ...
</dependencies>
```
